### ISSUE TITLE
clean examples

### ISSUE THREAD

**Issue by fserra** [scipopt/PySCIPOpt#176]
On top of #49, we should differentiate between basic and advanced examples. The idea would be that the basic ones could serve as tutorials for how to set up something: a constraint, use re-optimization, etc.
The advanced ones would be more in the spirit of what we currently have as examples, that is, small applications showing how to solve some problem.

**Comment by fserra** [comment]
Yes, you are right, I also don't like advanced and basic.    
Maybe is just best to add a directory called `tutorial` with the "basic" examples.

**Comment by ramabile** [comment]
So `finished`, `unfinished` and `tutorial`?
May I update my last open pull request or should I make a new one?
(the latter means branching my fork at some point? github newcomer here...)
