### ISSUE TITLE
SCIP specific exception classes for return codes in PY_SCIP_CALL

### ISSUE THREAD

**Issue by ambros-gleixner** [scipopt/PySCIPOpt#207]
Didier Chételat @dchetelat recommended that it would be better Python practice if PY_SCIP_CALL() did not return generic Exceptions but derive one Exception class for each SCIP return code.

**Comment by CGraczyk** [comment]
@mattmilten has this ever happened or was this considered and the issue can be closed?

**Comment by mattmilten** [comment]
I don't recall what this was about. PY_SCIP_CALL already raises Exceptions of different kinds. See https://github.com/scipopt/PySCIPOpt/blob/4cd44fc412c2597e432ea8b20871084fc26381db/src/pyscipopt/scip.pyx#L228

**Comment by CGraczyk** [comment]
Ill consider this done then.
