### ISSUE TITLE
"write" methods don't work after `redirectOutput()`

### ISSUE THREAD

**Issue by mattmilten** [scipopt/PySCIPOpt#243]
After calling `redirectOutput()`, e.g. `writeProblem()` does not produce a file but prints the problem description to the outstream.

Apparently, we redirect *everything* to the new messagehandler.

**Comment by fserra** [comment]
interseting my search didn't tell me about this

**Comment by CGraczyk** [comment]
I assume this is still relevant so i will leave this open.

**Comment by Joao-Dionisio** [comment]
Is this still relevant, @mattmilten @fserra?

**Comment by LuizSuzana** [comment]
A possible related issue happens when calling `setLogfile` and `writeProblem`. The problem description is written to a file (argument of `writeProblem`), and also to the logfile. I would expect it to not be included in the logfile.
```python
import pyscipopt
m = pyscipopt.Model("test2")
x = m.addVar("x", vtype="B")
m.addCons(x >= 1, name="C1")
m.setLogfile('file.log')
m.optimize()
m.writeProblem("test.lp")
# file.log is created with the output from the solver, but it also contains the problem description in the lp format
# test.lp is correctly created with the problem description in the lp format
```

**Comment by DominikKamp** [comment]
I guess `relayMessage()` in scip.pxi should still write to file if it is not NULL because in SCIP the convention is to only write to the console if it is NULL.
