### ISSUE TITLE
release variable, constraints, rows, etc

### ISSUE THREAD

**Issue by fserra** [scipopt/PySCIPOpt#26]
this is the follow up of issue 55 on gitlab.

In `addVar` we create a SCIP var and then release it. The same happens in `addCons`.  
So the idea is then to have a `__dealloc__`, as in `class Model`, for variables, constraints, rows, etc, right?

**Comment by fserra** [comment]
btw, we have in `class Model`: `def releaseVar`. We should probably organize a cleaning day

**Comment by fserra** [comment]
So one issue is that to call `releaseVar` or `releaseRow` or `releaseCons` you need a `scip` pointer. However, the classes `Variable`, `Constraint`, `Row` don't have a `scip` pointer.  
Should we just have a weakref to Model in those classes?

**Comment by leethargo** [comment]
So your point is that we release the variables too early and might risk that the `Variable` objects becomes broken when `Model` is gc'd?

For cleaning, I suggest removing methods you dislike as long as the tests pass ;-)

I don't understand why one would need a SCIP to release a var, but with a weakref we also risk a segfault, right?

**Comment by fserra** [comment]
I think the problem is that if SCIP decides to remove the variable, then we don't have access to it any more and the object is broken. Benny's original comment was:

>I don't know if this is related to the problem but the SCIPreleaseVar call in model.addVar() seems to be strange (wrong?). How could you implement a separator if the variables will be directly released after their creation?

>Edit: I meant for an algorithm that uses the knowledge of the problem structure, e.g., where you need to keep track of some important variables
  
The SCIP is needed because SCIP knows the memory where the object was allocated. And yes, one could risk a segfault because SCIP could get free'd first... so now I am unsure about the `__dealloc__` solution... @mattmilten

**Comment by fserra** [comment]
So what are we going to do about this?

It doesn't really make sense that variables don't know the scip pointer/model, since actually, you can only create a variable in a model:
```
scip = Model()
x = scip.addVar(...)
```
Also, it seems one can give callbacks to weakreferences so that they are called when the wearrefereed object is freed... this way we can ensure that variables get freed when freeing the main scip...

**Comment by mattmilten** [comment]
Yes, it seems to make a lot of sense to give the Constraint and Variable classes a scip pointer. What could be the downside?
