### ISSUE TITLE
Evaluate Expressions

### ISSUE THREAD

**Issue by mattmilten** [scipopt/PySCIPOpt#280]
This is a feature request to evaluate any expressions using some variable assignment:

https://stackoverflow.com/questions/55843123/evaluating-pyscipopt-expr-after-optimization/55891698?noredirect=1#comment98644665_55891698

**Comment by mcitoler** [comment]
Hi, @mattmilten do you mind if I take a crack at this?

**Comment by mattmilten** [comment]
Absolutely not! I would be very happy to accept your pull request. :tada:

**Comment by mcitoler** [comment]
I wanted to follow up on @fserra's suggestion at the end of #308 to make the Solution __getitem__ accept Expr instances as well. I could make another PR to cover that.

**Comment by mattmilten** [comment]
You are very welcome to implement this!
