### ISSUE TITLE
Weird weakreferencing issue for Event handlers

### ISSUE THREAD

**Issue by pg2455** [scipopt/PySCIPOpt#297]
I am catching NODEBRANCHED event using this class .- 
```
class NodeEnd(scip.Eventhdlr):
    def __init__(self):
        pass

    def eventinit(self):
        self.model.catchEvent(scip.SCIP_EVENTTYPE.NODEBRANCHED, self)

    def eventexit(self):
        self.model.dropEvent(scip.SCIP_EVENTTYPE.NODEBRANCHED, self)

    def eventexec(self, event):
        self.model.data.close_node("branched")
```
In the solving process, I am observing these errors somewhere in the middle of a run - 
```
Traceback (most recent call last):
  File "/home/mip/classes/events.py", line 11, in eventexit
    self.model.dropEvent(scip.SCIP_EVENTTYPE.NODEBRANCHED, self)
ReferenceError: weakly-referenced object no longer exists
Exception ignored in: 'pyscipopt.scip.PyEventExit'

```
Why will the reference to model not exist when it has not yet finished?
And I can't explain why the process keeps running even after throwing this error. It throws this error and continues solving the problem. 

I understand that the model has been weakly referenced within `model.includeEventhndlr()`. A weak reference doesn't count towards reference-count of the object so if there are no strong references, weak reference will be `None`. But in this case, my strong reference to the model is defined at the very beginning when I created the model object. At any point, my model object should exist and therefore weakref shouldn't be `None`  until the `model.optimize()` returns something.

**Comment by fserra** [comment]
yeah this is weird. I have no idea right now. I guess it keeps on going because, as it says there, the exception is ignored.

Do you have a minimal working example to reproduce this?

**Comment by pg2455** [comment]
I am unable to reproduce this error. When I run a script that sequentially handles problems for a time limit of 1800 seconds, I see this error in some of the instances. But when I separately run those instances in which I saw that error, I don't see this error. 

To prevent this error from occurring again, would you suggest making using a strong reference for the model?

**Comment by fserra** [comment]
hi @pg2455 does this still happen with the latest version?
