### ISSUE TITLE
How to use the unfinished examples such as vrp.py?

### ISSUE THREAD

**Issue by kendu605** [scipopt/PySCIPOpt#298]
How to use the unfinished examples such as vrp.py?

**Comment by fserra** [comment]
what happens when you just run it?

**Comment by kendu605** [comment]
When I ran the code file vrp.py directly, it comes out with the error as following:
`TypeError: conslock() takes 4 positional arguments but 5 were given
Exception ignored in: 'pyscipopt.scip.PyConsLock'
TypeError: conslock() takes 4 positional arguments but 5 were given
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.1\scip\src\scip\cons.c:4168] ERROR: Error <0> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.1\scip\src\scip\prob.c:585] ERROR: Error <0> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.1\scip\src\scip\scip_solve.c:452] ERROR: Error <0> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.1\scip\src\scip\scip_solve.c:2440] ERROR: Error <0> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.1\scip\src\scip\scip_solve.c:2660] ERROR: Error <0> in function call
Traceback (most recent call last):
  File "F:/PycharmProjects/vrp_opt/vrp_scip.py", line 127, in <module>
    model.optimize()
  File "src\pyscipopt\scip.pyx", line 2570, in pyscipopt.scip.Model.optimize
  File "src\pyscipopt\scip.pyx", line 217, in pyscipopt.scip.PY_SCIP_CALL
Exception: SCIP: unspecified error!`

**Comment by mattmilten** [comment]
In general, these codes might have been outdated with respect to API changes - like in your case - or may rely on not yet implemented features. The examples have been adapted from another solver interface and this is why they are not all working. They can still be useful as starting point when trying to implement a similar feature or model.

**Comment by fserra** [comment]
you can have a look at finished/tsp.py which is similar.

Also, you can try adding `model.freeTransform()` before the `for` at line 38

Also, I guess you are running a different vrp file: your error says
`File "F:/PycharmProjects/vrp_opt/vrp_scip.py", line 127, in <module>`
while the file only has 111 lines.

**Comment by kendu605** [comment]
Sorry, I actually ran the vrp_lazy.py file and got the error above.
I can run the finished/tsp.py successfully,but still got error when running unfinished/vrp.py:
`[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.1\scip\src\scip\scip_cons.c:1069] ERROR: invalid SCIP stage <10>
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.1\scip\src\scip\cons_linear.c:17695] ERROR: Error <-8> in function call
Traceback (most recent call last):
  File "F:/PycharmProjects/vrp_opt/vrp_scip.py", line 108, in <module>
    z, edges = solve_vrp(V, c, m, q, Q)
  File "F:/PycharmProjects/vrp_opt/vrp_scip.py", line 74, in solve_vrp
    if addcut(edges) == False:
  File "F:/PycharmProjects/vrp_opt/vrp_scip.py", line 43, in addcut
    add = model.addCons(quicksum(x[i, j] for i in S for j in S if j > i) <= S_card - NS)
  File "src\pyscipopt\scip.pyx", line 1572, in pyscipopt.scip.Model.addCons
  File "src\pyscipopt\scip.pyx", line 1587, in pyscipopt.scip.Model._addLinCons
  File "src\pyscipopt\scip.pyx", line 233, in pyscipopt.scip.PY_SCIP_CALL
Exception: SCIP: method cannot be called at this time in solution process!`

**Comment by kendu605** [comment]
And when I added the model.freeTransform() before the for at line 38 as you suggested, I got another error:
`Traceback (most recent call last):
  File "F:/PycharmProjects/vrp_opt/vrp_scip.py", line 109, in <module>
    z, edges = solve_vrp(V, c, m, q, Q)
  File "F:/PycharmProjects/vrp_opt/vrp_scip.py", line 78, in solve_vrp
    return model.getObjVal(), edges
  File "src\pyscipopt\scip.pyx", line 3519, in pyscipopt.scip.Model.getObjVal
Warning: method cannot be called before problem is solved`

**Comment by fserra** [comment]
So what the vrp is doing is creating a model, solving it, adding constraints, solving again.

The issue is that when SCIP solves a problem, it goes to the "solved stage".
In that stage, you cannot add constraints.
So you call freeTransform to go back to a stage where you can add constraints.

You just need to take care not to call freeTransform when you do not want to add more constraints.

**Comment by kendu605** [comment]
Thanks for your explanations, but I  don't quite understand, and have tried many methods , and still couldn't make it work.
Hava you run the example vrp.py successfully at your side?

**Comment by fserra** [comment]
Yes.. well I didn't have to patience to let it run till the end

If you can write a small example where your problem appears I could
probably give better comments, but the idea is the following.

You do model.optimize()
and after is solved you check whether you can add extra constraints.
 you should call model.freeTransform() **only** when you can add extra
constraints,

You can add a flag, notfreed, that is set to true at the beginning of your
method that adds constraints. Then you check if there is a constraint that
you can add. Before the line "model.addCons..." you add
if notfreed:
  model.freeTransform()
  notfree = False

Something like that should make it work.

**Comment by mattmilten** [comment]
closed due to inactivity
