### ISSUE TITLE
remove _bestsol from model class

### ISSUE THREAD

**Issue by mueldgog** [scipopt/PySCIPOpt#314]

**Comment by mueldgog** [comment]
Right now, we are storing the best solution in a separate variable in the model class after calling `optimize()` or `getBestSol()`. This makes the python interface much more complicated because we need to add conditions like

```
        if not self.getStage() >= SCIP_STAGE_SOLVING:
            raise Warning("method cannot be called before problem is solved")
        return self.getSolObjVal(self._bestSol, original)
``` 

to functions like `getObjVal()`. Even worse, there are a lot of corner cases that are not covered by this. For example, if we just add a solution to a SCIP instance then this `_bestsol` variable is not updated and we get wrong results when calling `getObjVal()`. I also observed that `test_customizedbenders.py` fails if we add the assertion `assert SCIPgetNSols(self._scip) > 0` to the function. The function should only be called if there is a feasible solution, but it seems that in some cases it might return the last LP solution value? @stephenjmaher, you might want to have a look at this.

Anyway, it is fairly straight forward to adapt the code. There is only one thing that is getting complicated:

The function `getVal` calls `getSolVal` and then `expr._evaluate(...)` with the `_bestsol` solution that I want to remove. Creating a solution in `getVal` with `getBestSol()` is not a possibility because this might lead to a large overhead. My suggestion would be to either

- remove `getVal()` or
- to add the possibility that an expression can be evaluated with a SCIP_SOL*. This would allow me to use something like `expr._evaluate(SCIPgetBestSol(self._scip))` in `getVal()`.

Removing `getVal()` sounds drastic, but I think that it would avoid a lot of errors because you are forced to use `getSolVal()`, which ensures that there is actually a solution after calling `optimize()`.

Any opinion about this?

**Comment by fserra** [comment]
mmm, I find this tricky. Removing convenience functions always makes the interface easier to maintain, but harder to use. I find it also a bit awkward to write code like
```
model.optimize()
bestsol = model.getbestsol()
model.getval(bestsol, x)
```
it is a bit redundant.

Of course the idea is to avoid creating all the time a Solution object and this is achieved with `_bestsol`.

I would try to find a solution that keeps `getVal` (and so `_bestsol`) but maybe restricts its use only to `getVal`. What do you think?

**Comment by mueldgog** [comment]
I find this kind of redundancy not problematic because you need to do the same when using SCIP with C. Anyway, we can keep `getVal` and use `_bestsol` only there.

**Comment by mueldgog** [comment]
An alternative would be to add `SCIPgetBestSolVal()` to SCIP and then wrap only this function ... What do you say?

**Comment by mueldgog** [comment]
> An alternative would be to add `SCIPgetBestSolVal()` to SCIP and then wrap only this function ... What do you say?

Forget it. This is not enough if we want to evaluate any expression with a solution. Let us stick yo your suggestion.
