### ISSUE TITLE
Difficulties installing and Illegal instruction error for README.md example

### ISSUE THREAD

**Issue by mlangiu** [scipopt/PySCIPOpt#349]
Hello and first of all thank you for providing PySCIPOpt!
I am trying to get up and running and encountered some issues installing pyscipopt on a mac 10.12.6 running Sierra.
After finding some fidgety 'solutions' to these issues I tried running the example which failed with an Illegal Instruction error when trying to optimize...

Here are the steps I've taken so far:

---

1. Downloaded self extracting archive for mac from scip website
2. from `~/Downloads/`
3. `chmod 755 SCIPOptSuite-6.0.2-Darwin.sh`
4. `./SCIPOptSuite-6.0.2-Darwin.sh`
5. accept license and follow instructions and a new directory named `SCIPOptSuite-6.0.2-Darwin` is created
6. cd `SCIPOptSuite-6.0.2-Darwin`
7. `export SCIPOPTDIR=$PWD`
8. `pip3 install pyscipopt`
9. first try... `python3`
  ```python
  Python 3.7.5 (default, Dec  6 2019, 14:23:26)
  [Clang 9.0.0 (clang-900.0.39.2)] on darwin
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import pyscipopt
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib/python3.7/site-packages/pyscipopt/__init__.py", line 5, in <module>
      from pyscipopt.scip      import Model
  ImportError: dlopen(/usr/local/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so, 2): Library not   loaded: libscip.6.0.dylib
    Referenced from: /usr/local/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so
    Reason: image not found
  ```
10. `export DYLD_LIBRARY_PATH="/Users/admin/Downloads/SCIPOptSuite-6.0.2-Darwin/lib/"`
11. second try... `python3`
  ```python
  Python 3.7.5 (default, Dec  6 2019, 14:23:26)
  [Clang 9.0.0 (clang-900.0.39.2)] on darwin
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import pyscipopt
  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyscipopt/__init__.py", line 5, in <module>
    from pyscipopt.scip      import Model
  ImportError: dlopen(/usr/local/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/gcc/lib/gcc/8/libgfortran.5.dylib
  Referenced from: /Users/admin/Downloads/SCIPOptSuite-6.0.2-Darwin/lib//libscip.6.0.dylib
  Reason: image not found
  ```
12. Hmm why is an old gcc version being used? Well, let's try faking it... `mkdir -p /usr/local/opt/gcc/lib/gcc/8/` (create new subdirectory `8`)
13. `ln -s /usr/local/opt/gcc/lib/gcc/9/libgfortran.5.dylib /usr/local/opt/gcc/lib/gcc/8/libgfortran.5.dylib`
14. third try... `python3`
```python
  Python 3.7.5 (default, Dec  6 2019, 14:23:26) 
  [Clang 9.0.0 (clang-900.0.39.2)] on darwin
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import pyscipopt
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib/python3.7/site-packages/pyscipopt/__init__.py", line 5, in <module>
      from pyscipopt.scip      import Model
  ImportError: dlopen(/usr/local/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so, 2): Library   not loaded: /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib
    Referenced from: /Users/admin/Downloads/SCIPOptSuite-6.0.2-Darwin/lib//libscip.6.0.dylib
    Reason: image not found
  >>> 
  ```
15. Ok, one more time `ln -s /usr/local/opt/gcc/lib/gcc/9/libquadmath.0.dylib /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib`
16. fourth try... `python3`
  ```python
  Python 3.7.5 (default, Dec  6 2019, 14:23:26) 
  [Clang 9.0.0 (clang-900.0.39.2)] on darwin
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import pyscipopt
  >>> 
  ```
17. Nice so let's try the example...
  ```python
>>> from pyscipopt import Model
>>> model = Model("Example")  # model name is optional
>>> x = model.addVar("x")
>>> y = model.addVar("y", vtype="INTEGER")
>>> model.setObjective(x + y)
>>> model.addCons(2*x - y*y >= 0)
c1
>>> model.optimize()
Illegal instruction: 4
  ```

**Comment by fserra** [comment]
ufff I am sorry. I don't really now. I can only imagine that the binary that we provide was compiled on a version different than yours? You could try to compile scip from source. Using Cmake should be possible. Maybe then linking that SCIP works?

**Comment by mattmilten** [comment]
@mlangiu, could you please installing again using version 3.0 and SCIP 7.0?

**Comment by mattmilten** [comment]
closed due to inactivity
