### ISSUE TITLE
How to access current variable values in functions

### ISSUE THREAD

**Issue by mangoon91** [scipopt/PySCIPOpt#370]
Hello,

I am using a property library as part of my model, which needs a real number as an input. How can I  get the current value from a variable instance?
Here is a minimal example code:
~
from pyscipopt import Model
from CoolProp.CoolProp import PropsSI

def fun1(x):
    # use given temperature x to calculate saturation pressure using library Coolprop
    return PropsSI("P", "T", x + 273.15, "Q", 0, "Water")

model = Model("Example") 
x = model.addVar("x",lb=10,ub=40)   # Temperature of water
y = model.addVar("y")               # saturation pressure of water at temperature x
model.setObjective(y)               # minimize saturation pressure
model.addCons(fun1(x) == y)         # define y as saturation pressure using fun1
model.optimize()
sol = model.getBestSol()
print("x: {}".format(sol[x]))
print("y: {}".format(sol[y]))
~

Coolprop in fun1 throws a type error because the input "must be real number, not pyscipopt.scip.Expr".

Thanks much!

**Comment by mattmilten** [comment]
Hi! Unfortunately, this is not as easy as that. You cannot use PySCIPOpt Variable objects as input for other modules and you also cannot use external functions as constraints like that.

You would need to implement a proper constraint handler to do this. You can check our examples for getting an idea on how to do this.

cheers,
Matthias

**Comment by mangoon91** [comment]
Hey, thank you for your quick reply. You must be referring to the  lotsizing_lazy.py example: http://scip-interfaces.github.io/PySCIPOpt/docs/html/lotsizing__lazy_8py_source.html ?

I have difficulties understanding  that example. Can you estimate whether constraint handlers are a straightforward and good solution for my problem or should I better try an entirely different optimization suite? I will have several external functions similar to the one in my example, but mostly with two inputs and one output instead of only one input as above.

**Comment by mattmilten** [comment]
Hard to tell what could be best. The SCIP Opt Suite grants you access to the entire source code and enables very deep customizations. If you need something more straightforward you may want to check out something like Gurobi or Pyomo or cvxopt. Your mileage may vary.

**Comment by mangoon91** [comment]
Hi Matthias,
I will have a look into those.
Thank you very much,
Leon
