### ISSUE TITLE
numerical precision for objective function evaluation/comparison

### ISSUE THREAD

**Issue by cyberghz** [scipopt/PySCIPOpt#376]
For certain model SCIP returned as optimal solution a suboptimal one. I know this because I compared its value with that of a previously known better feasible solution. The relative difference between their values is in the order of 1e-6.

What parameter should I change to make SCIP work with a greater precision when comparing different values of the objective function? Feasibility is not a problem since the constraints defining the feasible set are not numerically hard.

**Comment by fserra** [comment]
the comparison of objectives values is a hard comparison (there is no tolerance). Where does this previously known better feasible solution come from?

**Comment by mattmilten** [comment]
closed due to inactivity
