### ISSUE TITLE
scip Model support pickle dump

### ISSUE THREAD

**Issue by dikar** [scipopt/PySCIPOpt#406]
hi !
   when I in python multiprocessing for scip ,there is error for scip model .

   TypeError: self._scip,self._valid cannot be converted to a Python object for pickling

**Comment by fserra** [comment]
Hi. I have no idea what this is. I did a quick google search and end up here: https://ask.sagemath.org/question/8376/pickling-extension-classes/ 
It seems we need to implement `__reduce__` for the Model class?
Can you give it  a try?
