### ISSUE TITLE
Optimal solution does not satisfy constraints consisted of priced variables.

### ISSUE THREAD

**Issue by purin0604** [scipopt/PySCIPOpt#408]
Hi,

Thanks to your advise so far, I have completed building my branch-cut-price model.
However, I found the optimal solution does not satisfy some constraints, especially when they have priced variables.

For example, I have a constraint such as

> eq1 :  `\sum_{i} x_i <= y`

where y is an original binary variable and x_i are priced binary variables. These constraints are defined as` modifiable = True`.

I added a new variable using 
`self.model.addVar(vtype="B",  obj = optimal_m, name= newVar_name, pricedVar=True)`
and added this new variable to the above constraint
`self.model.addConsCoeff(eq1, newVar, 1 )`

However, the optimal solution is  `y=0 `and `x_i=1 `for some i, which does not satisfy the above constraint. 

When I wrote out the model into `.cip` file, I can see the constraints changed properly. 
I tried to read the file again within the SCIP console, however, there was an error saying that x_i variables (priced variables) were not defined in the `cip` file. 

What am I missing here?

**Comment by fserra** [comment]
can you share some (hopefully small) code to reproduce?

**Comment by mattmilten** [comment]
closed due to inactivity
