### ISSUE TITLE
Does Getsolvingtime() return cpu time?

### ISSUE THREAD

**Issue by gbasal** [scipopt/PySCIPOpt#411]
That might be very easy question and cannot be regarded as an issue. However, the thing is, I get different solution times for every execution of my same model. I have 4 different models and want to compare their cpu time performances. However, i get different time values for the same models in different days of execution. 

In SCIP parameters list, I see the default clock type is cpu clock. Am I missing something? Could anyone please help me on this?

My code to get the CPU time:

model.getSolvingTime()

Thanks in advance

**Comment by fserra** [comment]
the default is wall time... what scip version are you using? How different are the times?

**Comment by gbasal** [comment]
I am using the latest version. The differences occur up to 50%. For some instances, times are highly close to each other. 

The following is from the parameters list:

 # default clock type (1: CPU user seconds, 2: wall clock time)
# [type: int, advanced: FALSE, range: [1,2], default: 1]
timing/clocktype = 1

Does that refer something different? 

I measured the cpu time by time.process_time() function and the variation still occurs. Can it be memory related? SCIP runs iteratively for a set of instances. I run my model for 10 instances iteratively in a for loop. Is there anything I should do after each iteration except freeing the problem?

Thank you.

**Comment by fserra** [comment]
I guess you are looking at an old parameter list. in https://www.scipopt.org/doc/html/PARAMETERS.php it shows that the default is 2.

But what is the magnitude of the numbers that we are talking about? 50% of 0.0001 seconds is not the same as 50% of 20 seconds

So what exactly are you doing?
Do you have 1 problem that you are solving 10 times in a loop? Or do you have 10 different problems that you are solving in a loop? When you say freeing the problem you mean calling free transform or creating a new Model?

Do you see a different statistic apart from time? Like different number of nodes, or different number of LP iterations?

**Comment by gbasal** [comment]
You are right, mine was old. Thanks! I switch to the new one.

I could not explain my problem clearly, sorry for that. Let me tell the whole story briefly:

1) I previously construct 4 different mathematical models for the same problem (each giving different number of DVs and constraints) in SCIP version 6. I recorded the cpu times by using the function model.getSolvingTime(). I compared the performances of those four models. 
2) Then, like 6 months later, I updated SCIP to version 7. I ran my models again and see that the times are different. Then, I ran again, and again. I see in each execution the times are different. Take Model 1, Instance 5 in SCIP version 7 for example. The cpu time is 120 seconds in one execution, and I execute it again after some time and I got 149 seconds. (In the same version. I could be wrong about the numbers, I will check later)
3) The CPU time of Instance 1 is pretty consistent actually, (3.7seconds, 3.9 seconds, 4.2seconds) so I think that might be memory related issue. 
4) I have 4 different files for four different models and execute them manually. I keep and execute all those four independently. The only loop constructed is for set of instances for the same model. My first part of the code is dedicated to take the inputs (parameters of the instance) then the model comes. The code is like this for each model (independently). 
     for input file number in range(1,11): 
              take the inputs
              create new model 
              execute model
              model.freeprob()  (_It can be unnecessary because i create new model in each iteration, but still, i included it_)
              keep the stats

Thanks again!

**Comment by fserra** [comment]
So I don't really know. I guess the experiment that would make the most sense is to run the same fixed instance many times and check the execution time of each run. Also, it would be good to know if there is anything else that changes in the run apart from the time. So maybe you could print the output of two runs that have different time behavior (including the statistics), or write if you find out that actually there are more differences than just the time (number of nodes, lp iterations, etc).
