### ISSUE TITLE
addConsNode currently unusable?

### ISSUE THREAD

**Issue by CharJon** [scipopt/PySCIPOpt#416]
Hi everyone,

so I might be missing something, but it seems to me as if the interface is lacking functionality to make use of `addConsNode`.
To implement some custom branching rules I want to use `makeChild` and `addConsNode`. The later expects a constraint as a `Constraint` object as input (next to a node to add the constraint to). But I can not wrap my head around how to transform my constraint of type `ExprCons` into a constraint. I tried adding it to the model via `addCons`, but this lead to problems, as I don't want the constraint to be part of the model in general, but just stick to one child (and it's children).
I might be misunderstanding something as my SCIP knowledge is fairly limited, but the constraint handlers make use of the `createCons` method, to generate special constraints. Do the branching rules need something similar, or am I doing something wrong?
I appreciate any help and/or comment.

**Comment by fserra** [comment]
does #391 answer your question?

**Comment by CharJon** [comment]
Hi, thanks for your answer. #391 is indeed closely related to my problem.
After reading the information there, I still feel like extending the Interface is the only solution for my case, as `addCons` does not work for me.
What I did for now to solve my problem is also wrapping [SCIPcreateConsLinear](https://www.scipopt.org/doc-7.0.1/html/group__CONSHDLRS.php#gaea3b4db21fe214be5db047e08b46b50e) and using Constraints created this way for `addConsNode`. This seems to work as expected, I'm just not familiar with wrapping and get a `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)` after everything finishes.

If this is the preferred solution and if someone could help me with the SIGSEGV I could create a pull-request to extend the functionality.

**Comment by fserra** [comment]
I think it would make sense to modify `addConsNode` to also accept `ExprCons`, maybe only when the `ExprCons` is linear.

**Comment by CharJon** [comment]
This works as well.

Right now I'm basically doing the same as Model._addLinCons does, just without `PY_SCIP_CALL(SCIPaddCons(self._scip, scip_cons))` before and `PY_SCIP_CALL(SCIPreleaseCons(self._scip, &scip_cons))` after `PyCons = Constraint.create(scip_cons)`.
If I add the constraint creation via `PY_SCIP_CALL(SCIPcreateConsLinear(...))` into `addConsNode`, how do I prevent a SIGSEGV?

**Comment by fserra** [comment]
I don't understand what you are saying. You can open a PR so we can see the code, but my guess is that it should look something like:

```
PY_SCIP_CALL(SCIPcreateConsLinear(...))
PY_SCIP_CALL(SCIPaddConsNode(...))
PyCons = Constraint.create(scip_cons)
PY_SCIP_CALL(SCIPreleaseCons(self._scip, &scip_cons))
...
return PyCons
```

You get a segfault when you do that?
I think it should work without having the increase the ref to cons, because when cons is a Constraint created from a conshdlr within SCIP, then `cons` is basically the consdata of the constraint and one doesn't want to delete the consdata. However, if the cons is an ExprCons it shouldn't be a problem to release the constraint....

**Comment by CharJon** [comment]
Thanks again for your feedback. I created #418 .
Adding PY_SCIP_CALL(SCIPreleaseCons(self._scip, &scip_cons)) to the end of the method solved my SIGSEGV error. Could you give some intuition why the constraint has to be "released"?

**Comment by fserra** [comment]
I wouldn't know why that resolves a segmentation fault. SCIP basically uses reference counting. So when you create a constraint it has reference 1, when you add it to scip it has reference 2. When a constraint reaches reference 0 it gets freed. So if you do **not** call release, it will never get down to 1 and so SCIP will not release it. That is a memory leak but not a segfault.
We call release at that point in time because we do not want the user to remember the constraint and then call release

**Comment by SanielDous** [comment]
@CharJon It would be really nice if you could post a code snippet of your workaround. Thereby, others like me could adapt it easier :)

**Comment by CharJon** [comment]
> @CharJon It would be really nice if you could post a code snippet of your workaround. Thereby, others like me could adapt it easier :)

All code I used is in #418. I did not reply to your comment over there, because I do not know what happened to my code. It is flagged as merged, but I can't find the changes from current master branch and #485 is discontinued?

**Comment by SanielDous** [comment]
Thank you for replying. Unfortunately, I think your code never made it into master since the `addConsLocal` branch was never merged. This feature would be really useful...

**Comment by CGraczyk** [comment]
Hi,
I just saw your issue, tbh I dont remember what happened to that branch - could be that I made a mistake and just closed the MR instead of merging it?
I will try to find an answer for you, #605 is related to this as well correct @SanielDous ?

**Comment by SanielDous** [comment]
Yes, #605 is related. I tried to fix the problem using a constraint handler but it seems make it way more complicated than what I want to achieve.
