### ISSUE TITLE
install fail on mac

### ISSUE THREAD

**Issue by zlweiyang** [scipopt/PySCIPOpt#417]
creating build/temp.macosx-10.15-x86_64-3.8/src/pyscipopt
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/Users/zhuliang/Applications/scip/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c src/pyscipopt/scip.c -o build/temp.macosx-10.15-x86_64-3.8/src/pyscipopt/scip.o
  In file included from src/pyscipopt/scip.c:633:
  In file included from /Users/zhuliang/Applications/scip/include/scip/scip.h:35:
  /Users/zhuliang/Applications/scip/include/scip/def.h:43:10: fatal error: 'scip/config.h' file not found
  #include "scip/config.h"
           ^~~~~~~~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyscipopt
  Running setup.py clean for pyscipopt
Failed to build pyscipopt
Installing collected packages: pyscipopt
    Running setup.py install for pyscipopt ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/k3/lk65ttvn069fzkfmf9221dkh0000gp/T/pip-install-30u13q25/pyscipopt/setup.py'"'"'; __file__='"'"'/private/var/folders/k3/lk65ttvn069fzkfmf9221dkh0000gp/T/pip-install-30u13q25/pyscipopt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/k3/lk65ttvn069fzkfmf9221dkh0000gp/T/pip-record-orl59xj9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/pyscipopt
         cwd: /private/var/folders/k3/lk65ttvn069fzkfmf9221dkh0000gp/T/pip-install-30u13q25/pyscipopt/

**Comment by bijoythomas** [comment]
Hello @mattmilten 

I was able to follow the installation instructions by setting the SCIPOPTDIR env var to a proper installation of the optimization suite and am running into issues when importing `pyscipopt`

The first error I ran into was the missing `libgfortran.5.dylib` as indicated by the following error on import
```
>>> import pyscipopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda2/envs/py37/lib/python3.7/site-packages/pyscipopt/__init__.py", line 10, in <module>
    from pyscipopt.scip      import Model
ImportError: dlopen(/anaconda2/envs/py37/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/gcc/lib/gcc/8/libgfortran.5.dylib 
  Referenced from: /Users/bijoythomas/SCIPOptSuite-7.0.0-Darwin/lib/libscip.7.0.dylib
  Reason: image not found
```

I proceeded to install the `gcc` package through brew and made sure it was referenced  in the `DYLD_LIBRARY_PATH` var like below:
`export DYLD_LIBRARY_PATH=/usr/local/Cellar/gcc/10.2.0/lib/gcc/10:$DYLD_LIBRARY_PATH`

But now, the import is past the fortran lib error but encountering another missing library:
```
>>> import pyscipopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda2/envs/py37/lib/python3.7/site-packages/pyscipopt/__init__.py", line 10, in <module>
    from pyscipopt.scip      import Model
ImportError: dlopen(/anaconda2/envs/py37/lib/python3.7/site-packages/pyscipopt/scip.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/tbb/lib/libtbb.dylib
  Referenced from: /Users/bijoythomas/SCIPOptSuite-7.0.0-Darwin/lib/libscip.7.0.dylib
  Reason: image not found
```

It looks like the missing libraries are an issue with the SCIP library `libscip.7.0.dylib` references and have nothing to do with the Python interface so perhaps this is the wrong place to post the issue, but I was just wondering if anyone here has run into something similar.
