### ISSUE TITLE
How to automatically install pyscipopt through dockerfile

### ISSUE THREAD

**Issue by zlweiyang** [scipopt/PySCIPOpt#422]
How to automatically install pyscipopt through dockerfile, because I want to realize the automatic deployment function of the server. I feel that the installation process of pyscipopt is too complicated.

**Comment by fserra** [comment]
Hi, I don't know if this helps
http://www.pokutta.com/blog/pages/scip/scip-teaching.html

**Comment by mattmilten** [comment]
closed due to inactivity
