### ISSUE TITLE
Import error: undefined symbol: __intel_cpu_feature_indicator

### ISSUE THREAD

**Issue by Wenbo11** [scipopt/PySCIPOpt#429]
Hey,

My system is GNU/linux
The following error raised whatever I installed pyscipot by using pip or building from source.
``import pyscipopt``
``Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/storage/home/hhive1/hsun349/data/anaconda3/envs/mip/lib/python3.8/site-packages/pyscipopt/__init__.py", line 10, in <module>
    from pyscipopt.scip      import Model
ImportError: /storage/home/hhive1/hsun349/data/anaconda3/envs/mip/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-x86_64-linux-gnu.so: undefined symbol: __intel_cpu_feature_indicator``

More information:
I also tried ``conda install -c scipopt -c conda-forge ecole pyscipopt`` mentioned in [ecole](https://github.com/ds4dm/ecole). Surprisingly, this way of installation works. However, I would like to install it by building from source since I may personalize some APIs in cython. 

To figure out the issue, I took a look at the scip.cpython-38-x86_64-linux-gnu.so file generated by ``conda install -c scipopt -c conda-forge ecole pyscipopt`` and building from the source.
I found:
1) They linked to the same dynamic libraries.
2) They have different symbols. See the attached symbol_diff.txt
Any ideas to solve it? Thank you so much!

[symbol_diff.txt](https://github.com/SCIP-Interfaces/PySCIPOpt/files/5214521/symbol_diff.txt)

Best,
Wenbo

**Comment by fserra** [comment]
mmm did you install SCIP and does it work?

**Comment by Wenbo11** [comment]
The SCIP works well.

**Comment by fserra** [comment]
From what you wrote, I have no idea.
Can you write **exactly** what you did to install SCIP and PySCIPOpt and which versions are you using?

**Comment by Wenbo11** [comment]
SCIP version 7.0.1
Soplex version 5.0.1
SCIP and Soplex were both built by CMake

For Soplex
``
cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$SCIPOPTDIR -DBOOST=false``
``make -C ./build -j 4``
``make -C ./build install ``

For SCIP
``
cmake -S . -B build -DSOPLEX_DIR=$SCIPOPTDIR -DCMAKE_INSTALL_PREFIX=$SCIPOPTDIR``
``make -C ./build -j 4``
``make -C ./build install
``

pyscipopt 3.0.3
built from source by
``python setup.py install``

Please let me know if any other information needed. Thank you so much!

**Comment by fserra** [comment]
hi, i don't really know. Maybe if you don't install scip and soplex into the same directory? (you don't really need to install soplex at all)
Or maybe try a new fresh environment...
@mattmilten maybe you have a better idea?

**Comment by mattmilten** [comment]
No, I also don't have a better idea, unfortunately. I haven't seen this error before.
