### ISSUE TITLE
Getting divescores inside solving loop

### ISSUE THREAD

**Issue by vincentfortin** [scipopt/PySCIPOpt#431]
I am looking to get dive scores from multiple diving heuristics at a certain point in the tree and use this information to make a branching decision.
I am unable to find a way to get dive scores inside the solving loop and I am wondering if it is possible to get those scores without executing the dive ?

I am looking to create a composite score from many dive scores using different techniques (averages, ml model, ...).

Thanks

**Comment by fserra** [comment]
Hey Vincent, I have very little experience with this side of SCIP, but I see that in `pub_heur.h` there is a function `SCIPheurGetDivesets()` (defined in `heur.c`) which returns the divesets of a given heuristic.

Then, in `scip_probing.c` there is a function
```c
SCIP_RETCODE SCIPgetDivesetScore(
   SCIP*                 scip,               /**< SCIP data structure */
   SCIP_DIVESET*         diveset,            /**< general diving settings */
   SCIP_DIVETYPE         divetype,           /**< represents different methods for a dive set to explore the next children */
   SCIP_VAR*             divecand,           /**< the candidate for which the branching direction is requested */
   SCIP_Real             divecandsol,        /**< LP solution value of the candidate */
   SCIP_Real             divecandfrac,       /**< fractionality of the candidate */
   SCIP_Real*            candscore,          /**< pointer to store the candidate score */
   SCIP_Bool*            roundup             /**< pointer to store whether preferred direction for diving is upwards */
   )
```

So, in C, I guess you could collect the diving heuristics with `SCIPfindHeur()` and then get the divesets of the heuristic with `SCIPheurGetDivesets()` and finally get the scores with `SCIPgetDivesetScore()`.

Would this be what you want?

I don't know, thought, if this would actually work, or if there is some precondition needed. Also, one would need to add some of this functions to PySCIPOpt, but that shouldn't be too complicated.
