### ISSUE TITLE
Branch-cut-and-price questions

### ISSUE THREAD

**Issue by IngyuLeeGitHub** [scipopt/PySCIPOpt#432]
Hello!

I need to make a branch-cut-and-price model using pySCIPOpt. Thanks to your kindness, I learned how to make the branch-and-price model, but I am not familiar with cut generation. 

I am wondering if there is a good example of branch-cut-and-price. I found that **lotsizing_lazy.py** shows how to add cut constraints, and I would like to ask if it's a good start to implement branch-cut-and-price or if you suggest some other examples. 
If so, can I use the cut generation from this model along with column generation to develop the branch-cut-and-price model?
 
I found that this example shows a bunch of parameters as shown in the attached screenshot. Could you kindly explain about the parameters or give me some sources to study? Thank you!

![Capture](https://user-images.githubusercontent.com/70441233/93727585-b7be1300-fb89-11ea-845f-78b0d482a5f1.PNG)

**Comment by IngyuLeeGitHub** [comment]
It would be helpful if you could answer the following question as well. 
I am trying to make the branch-cut-and price in a way that I said. But, I am having trouble to call for variables in the Conshdlr function, which are added by the pricer.

Regards,

**Comment by fserra** [comment]
you will find descriptions of these parameters in https://scipopt.org/doc/html/CONS.php

The example seems to be more about row generation (adding constraints) than pricing.

There are other issues in which branch cut and price is discussed: https://github.com/SCIP-Interfaces/PySCIPOpt/issues/395 https://github.com/SCIP-Interfaces/PySCIPOpt/issues/394 https://github.com/SCIP-Interfaces/PySCIPOpt/issues/375
 
You can get all the variables in the problem with `model.getVars` but, as far as I know, there is no function to just get the priced vars.

**Comment by IngyuLeeGitHub** [comment]
Thank you for your reply. 

Yes, to make the branch-cut-and-price, I need to implement row generation. 
That's why I am considering "Conshdlr" and ran into the following issue.

![image](https://user-images.githubusercontent.com/70441233/94327509-7e1a4d00-ff79-11ea-9d69-064e59fc7103.png)

It comes from 
![image](https://user-images.githubusercontent.com/70441233/94327520-8ecac300-ff79-11ea-8bb6-b9d075b5e095.png)

Do you know what this error happened and how to fix it? Appreciate your help!

**Comment by fserra** [comment]
I don't know what you mean by parallelly, but you need to make sure that SCIP understands that maybe the constraint that you are might be modified later by adding variables to it (i.e. mark the constraints as modifiable).

Maybe you can share a small example of the wrong behavior?

**Comment by stephenjmaher** [comment]
Combing column and row generation can be quite tricky. You need to take care of a number of different aspects to ensure the correctness of the algorithm.

First, you must ensure that you are handling the omitted constraints in the reduced cost calculations of your pricer. Even though the constraints do not appear in your model, they still may have a non-zero dual value. This will need to be accounted for when you generate variables.

Second, you will need to keep a track of the variables that you add, and the omitted constraints they belong to. When the constraints are generated, all previously generated columns will need to be added to the constraint.

Finally, to ensure that the processing of the LP does not terminate early, you need to provide a high priority for your constraint handler. This will ensure that it is the first one checked for any LP solution.
