### ISSUE TITLE
Cannot import PyScipOPt on windows, ImportError: DLL load failed

### ISSUE THREAD

**Issue by tyjch3n** [scipopt/PySCIPOpt#435]
Hi all, I've I have SCIPOptSuite 7.0.1 and Python 3.6 installed on my windows 10 machine. the scip.exe file is added onto my path variable where if I type scip on command prompt I will be directed to a scip shell. However after running a pip install for pyscipopt I run into the following error:

"ImportError: DLL load failed: The specified procedure could not be found."

Any pointers as to what I may have done wrong? Its not clear to me given that scip is already added onto my path variable. Thanks!

**Comment by fserra** [comment]
I am sorry, I don't really know. There are many resolved issues with installation problems in windows. Did you check them?

**Comment by mattmilten** [comment]
closed due to inactivity
