### ISSUE TITLE
Branch-and-Price Adding multiple columns at once

### ISSUE THREAD

**Issue by IngyuLeeGitHub** [scipopt/PySCIPOpt#437]
Hello!

I want to add a column at a time as my branch-and-price model branches but it seems to add multiple columns on the same node. I printed which column is added, denoted as j. As you can see j 0, 4, 21, 9, ..., 19 are added together in the screenshot. 
I wonder why it happens and how to add one column at a time. Thank you!!

![image](https://user-images.githubusercontent.com/70441233/94508416-f2562a00-01df-11eb-9738-5bba6f933a7c.png)

**Comment by fserra** [comment]
Maybe @stephenjmaher can say more about this.

But why do you say it is adding more than one variable at a time? Maybe it is just adding one per call to your pricer, and your pricer might just be called more than once.

**Comment by IngyuLeeGitHub** [comment]
Yes. I expected that one column is added at a time. But, for some reason, my price seems to be called more than once. 
I wonder if you know why this happens. 

![image](https://user-images.githubusercontent.com/70441233/95088195-a1b76300-06f0-11eb-8a81-6221557d6146.png)

**Comment by stephenjmaher** [comment]
It is not clear what you are trying to achieve here. Could you please explain further what to "add one column at a time" actually means. Do you mean per node, per LP solved or per call to the pricing problem? Also, could you please tell us where/when you are outputting the "j" line? This will explain more about your particular issue.

There a number of loops that are executed to solve the node LP. For our purposes, you have the price-and-cut loop and then you have the pricing loop. In the pricing loop, the pricer is called to generate columns, then the LP is resolved to update the bounds. This continues until a maximum number of pricing rounds are executed or the LP is solved to optimality. You have control over the number of columns added per round of the pricing loop. In `pricerredcost` you can choose to add a single column per call. The `pricerredcost` function is called for a number of times in the pricing loop. Once the pricing loop is completed, the pricing-and-cut loop continues.

The reason for this explanation is that the output of the "j" lines could be after a number of pricing rounds or price-and-cut rounds. As such, you need to be clear about what adding one column at a time actually means.

**Comment by IngyuLeeGitHub** [comment]
Thank you for your kind explanation. I like to add one column at a call to the pricing problem. I put my code if it could be helpful for your understanding, in which I made outputting the "j" in bold. I would be grateful if you could explain how to add a single column per call using pricerredcost. Thank you!


from pyscipopt import Model, Pricer, SCIP_RESULT, SCIP_PARAMSETTING, quicksum, multidict
import time
import itertools as it
import numpy as np
from  more_itertools import unique_everseen

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, mutual_info_classif, f_regression


class CutPricer(Pricer):

    # The reduced cost function for the variable pricer
    def pricerredcost(self):

        dual_sol = []
        for i, c in enumerate(self.model.data['slackCons']):
            dual_sol.append(self.model.getDualsolLinear(c))
        reduced_cost    = 1 - np.abs(np.dot(dual_sol*self.model.data['y'], self.model.data['X']))  
        column_to_check = np.array(list(set(self.model.data['column']) - set(self.model.data['idx_column']))) 

        if len(column_to_check) > 0:       
            neg_rc          = reduced_cost[column_to_check] < -1e-08
            column_to_add   = column_to_check[neg_rc][np.argsort(reduced_cost[column_to_check][neg_rc])][:1]
            if len(column_to_add) > 0:                    
                for j in column_to_add:
                    **print('j:', j)**
                    # print(self.model.getObjVal())
                    # print([self.model.getVal(v) for v in self.model.data['v_var']])
                    self.model.data['idx_column'].append(j)
                    k = self.model.data['group'][j] 
                    g_BM = sum(self.model.data['group'] == self.model.data['group'][j])         
                    ### Slack constraints
                    new_wp = self.model.addVar(vtype = "C", lb = 0, ub = None, name = "wp_" + str(j), obj = 1.0)
                    new_wn = self.model.addVar(vtype = "C", lb = 0, ub = None, name = "wn_" + str(j), obj = 1.0)           
                    new_v = self.model.addVar(vtype = "B", name = "v_" + str(j), obj = 0.0)
                    self.model.data['wp_var'] = np.append(self.model.data['wp_var'], new_wp)
                    self.model.data['wn_var'] = np.append(self.model.data['wn_var'], new_wn)
                    self.model.data['v_var']  = np.append(self.model.data['v_var'], new_v)
                              
                    for i, c in enumerate(self.model.data['slackCons']):
                        self.model.addConsCoeff(c, new_wp, self.model.data['y'][i]*self.model.data['X'][i][j])
                        self.model.addConsCoeff(c, new_wn, -self.model.data['y'][i]*self.model.data['X'][i][j])
                    
                    ### Group constraint
                    if k in self.model.data['idx_group']:
                        idx_k = np.squeeze(np.where(self.model.data['idx_group'] == k))
                        groupCons = self.model.data['groupCons'][idx_k]
                        self.model.addConsCoeff(groupCons, new_v, -1.0)
                        
                    ### Budget constraint
                    else:
                        budgetCons = self.model.data['budgetCons'][0]
                        new_g = self.model.addVar(vtype = "B", name = "g_" + str(k), obj = 0.0)
                        
                        self.model.addConsCoeff(budgetCons, new_g, self.model.data['g_cost'][k]) 
                        self.model.data['groupCons'].append(self.model.addCons(g_BM*new_g - new_v >= 0, modifiable = True, name = 'group_'+str(k)))
                        self.model.data['idx_group'].append(k)
                        self.model.data['g_var'] = np.append(self.model.data['g_var'], new_g)
                        
                    ### Bound constraints
                    self.model.addCons(new_wp + new_wn <= 1000*new_v, name=('w_ub_'+str(j)))
                    self.model.addCons(new_wp + new_wn >= -1000*new_v, name=('w_lb_'+str(j)))              
                             
        return {'result':SCIP_RESULT.SUCCESS}

    # The initialisation function for the variable pricer to retrieve the transformed constraints of the problem
    def pricerinit(self):
        for i, sc in enumerate(self.model.data['slackCons']):
            self.model.data['slackCons'][i] = self.model.getTransformedCons(sc)
            
        for i, gc in enumerate(self.model.data['groupCons']):
            self.model.data['groupCons'][i] = self.model.getTransformedCons(gc)

        for i, bc in enumerate(self.model.data['budgetCons']):
            self.model.data['budgetCons'][i] = self.model.getTransformedCons(bc)

     
        
column = range(X.shape[1])
### Select initial features based on f_score
idx_column = list(SelectKBest(f_regression, k=5).fit(X, y).get_support(indices=True))
idx_group = list(unique_everseen(group[idx_column]))

M, L = X.shape
L_CG = len(idx_column)
L_GR = len(idx_group)

BM = [big_m] * L_CG    
g_BM = [len(g_fea[k]) for k in idx_group]

model = Model("CESVM1_CG")
model.redirectOutput()
model.setPresolve(0)
model.setParam('limits/time', 60)
model.setHeuristics(0)

pricer = CutPricer()
model.includePricer(pricer, "", "", priority = 1, delay = True)

### VARIABLES
### binary
v_var = np.array([model.addVar(vtype='B', lb = 0, ub = 1, name="v_"+str(idx_column[j])) for j in range(L_CG)])
g_var = np.array([model.addVar(vtype='B', lb = 0, ub = 1, name="g_"+str(idx_group[k])) for k in range(L_GR)])
### errors 
e_var = np.array([model.addVar(vtype = "C", lb = 0, ub = None, name="loss_"+str(i)) for i in range(M)])
### Feature weight and bias 
wp_var = np.array([model.addVar(vtype = "C", lb = 0, ub = None, name ="wp_"+str(idx_column[j])) for j in range(L_CG)])
wn_var = np.array([model.addVar(vtype = "C", lb = 0, ub = None, name ="wn_"+str(idx_column[j])) for j in range(L_CG)])
b_var = model.addVar(vtype='C', lb = None, ub = None, name = "b")


### OBJECTIVE VALUE 
model.setObjective(quicksum((wp_var[j] + wn_var[j]) for j in range(L_CG)) + C*quicksum(e_var), "minimize")

slackCons = []
### HINGE CONSTRAINTS
for i in range(M):
    slackCons.append(model.addCons(e_var[i] + y[i]*(b_var + quicksum([X[i][idx_column[j]]*(wp_var[j] - wn_var[j]) for j in range(L_CG)])) >= 1, modifiable = True, name = "slack_" + str(i)))
    
       
### BUDGET CONSTRAINT
budgetCons = []
budgetCons.append(model.addCons((quicksum(g_cost[idx_group]*g_var) <= B), modifiable = True, name=("budget")))

groupCons = []
for k in range(L_GR):
    col_in_group = list(set(idx_column) & set(g_fea[idx_group[k]]))
    groupCons.append(model.addCons(g_BM[k]*g_var[k] - quicksum(v_var[[idx_column.index(j) for j in col_in_group]]) >= 0, modifiable = True, name=("group_"+str(idx_group[k]))))
   
### BOUND CONSTRAINT
for j in range(L_CG):
    model.addCons(wp_var[j]+wn_var[j] - BM[j]*v_var[j] <= 0, name=('w_ub_'+str(idx_column[j])))
    model.addCons(wp_var[j]+wn_var[j] + BM[j]*v_var[j] >= 0, name=('w_lb_'+str(idx_column[j])))       


model.data = {}
model.data['X'] = X
model.data['y'] = y
model.data['g_cost'] = g_cost

model.data['wp_var']     = wp_var
model.data['wn_var']     = wn_var
model.data['e_var']      = e_var
model.data['g_var']      = g_var
model.data['v_var']      = v_var
model.data['b_var']      = b_var

model.data['slackCons'] = slackCons
model.data['budgetCons'] = budgetCons
model.data['groupCons'] = groupCons
model.data['column'] = column 
model.data['group']  = group 
model.data['idx_column'] = idx_column 
model.data['idx_group']  = idx_group 

model.data['priceimplem'] = True
    
    
model.optimize()

**Comment by stephenjmaher** [comment]
The reason that you could be adding more than one column is that the list `column_to_add` could contain more than 1 element. You have a loop, `for j in column_to_add`, which adds all columns in the `column_to_add` list. If you remove the for loop and add only a single column from the `column_to_add` list, then you will add one column per call to `pricerredcost`.

You should look at different strategies for picking columns from the `column_to_add` list. One simple strategy is to add the column with the most negative reduced cost. However, there could be other features of the columns that you may want to prioritise.

**Comment by stephenjmaher** [comment]
I just realised that every time that you process an element of `column_to_add`, you are adding three columns `new_wp`, `new_wn`, `new_v`. So, even if you process a single element from `column_to_add`, you will always add three columns to the restricted master problem.

**Comment by IngyuLeeGitHub** [comment]
Thank you for your prompt reply. It still happens when I add one variable **new_v**. 

class CutPricer(Pricer):

    # The reduced cost function for the variable pricer
    def pricerredcost(self):

        dual_sol = []
        for i, c in enumerate(self.model.data['slackCons']):
            dual_sol.append(self.model.getDualsolLinear(c))
        reduced_cost    = 1 - np.abs(np.dot(dual_sol*self.model.data['y'], self.model.data['X']))  
        column_to_check = np.array(list(set(self.model.data['column']) - set(self.model.data['idx_column']))) 

        if len(column_to_check) > 0:       
            neg_rc          = reduced_cost[column_to_check] < -1e-08
            column_to_add   = column_to_check[neg_rc][np.argsort(reduced_cost[column_to_check][neg_rc])][:1]
            if len(column_to_add) > 0:                    
                for j in column_to_add:
                    print('j:', j)
                    self.model.data['idx_column'].append(j)
                    k = self.model.data['group'][j] 
                    g_BM = sum(self.model.data['group'] == self.model.data['group'][j])            
                    new_v = self.model.addVar(vtype = "B", name = "v_" + str(j), obj = 0.0)

                    ### Group constraint
                    if k in self.model.data['idx_group']:
                        idx_k = np.squeeze(np.where(self.model.data['idx_group'] == k))
                        groupCons = self.model.data['groupCons'][idx_k]
                        self.model.addConsCoeff(groupCons, new_v, -1.0)
                        
                    ### Budget constraint
                    else:
                        budgetCons = self.model.data['budgetCons'][0]
                        
        return {'result':SCIP_RESULT.SUCCESS}

    # The initialisation function for the variable pricer to retrieve the transformed constraints of the problem
    def pricerinit(self):
        for i, sc in enumerate(self.model.data['slackCons']):
            self.model.data['slackCons'][i] = self.model.getTransformedCons(sc)
            
        for i, gc in enumerate(self.model.data['groupCons']):
            self.model.data['groupCons'][i] = self.model.getTransformedCons(gc)

        for i, bc in enumerate(self.model.data['budgetCons']):
            self.model.data['budgetCons'][i] = self.model.getTransformedCons(bc)


This is the result showing multiple js are added at a time. 

![image](https://user-images.githubusercontent.com/70441233/95211519-b102e300-07ba-11eb-945d-4d69af22b18f.png)

**Comment by stephenjmaher** [comment]
Please read https://github.com/SCIP-Interfaces/PySCIPOpt/issues/437#issuecomment-704059625

**Comment by IngyuLeeGitHub** [comment]
I am sorry if I misunderstood you. However, column_to_add always contains one element. To check it, I remove the for loop and got the same result.  

class CutPricer(Pricer):

    # The reduced cost function for the variable pricer
    def pricerredcost(self):

        dual_sol = []
        for i, c in enumerate(self.model.data['slackCons']):
            dual_sol.append(self.model.getDualsolLinear(c))
        reduced_cost    = 1 - np.abs(np.dot(dual_sol*self.model.data['y'], self.model.data['X']))  
        column_to_check = np.array(list(set(self.model.data['column']) - set(self.model.data['idx_column']))) 

        if len(column_to_check) > 0:       
            neg_rc          = reduced_cost[column_to_check] < -1e-08
            column_to_add   = column_to_check[neg_rc][np.argsort(reduced_cost[column_to_check][neg_rc])][:1]
            j = column_to_add[0]
            print('j:', j)
            self.model.data['idx_column'].append(j)
            k = self.model.data['group'][j] 
            g_BM = sum(self.model.data['group'] == self.model.data['group'][j])            
            new_v = self.model.addVar(vtype = "B", name = "v_" + str(j), obj = 0.0)

            ### Group constraint
            if k in self.model.data['idx_group']:
                idx_k = np.squeeze(np.where(self.model.data['idx_group'] == k))
                groupCons = self.model.data['groupCons'][idx_k]
                self.model.addConsCoeff(groupCons, new_v, -1.0)
                
            ### Budget constraint
            else:
                budgetCons = self.model.data['budgetCons'][0]
                        
        return {'result':SCIP_RESULT.SUCCESS}

    # The initialisation function for the variable pricer to retrieve the transformed constraints of the problem
    def pricerinit(self):
        for i, sc in enumerate(self.model.data['slackCons']):
            self.model.data['slackCons'][i] = self.model.getTransformedCons(sc)
            
        for i, gc in enumerate(self.model.data['groupCons']):
            self.model.data['groupCons'][i] = self.model.getTransformedCons(gc)

        for i, bc in enumerate(self.model.data['budgetCons']):
            self.model.data['budgetCons'][i] = self.model.getTransformedCons(bc)

This is the screenshot of the result. 

![image](https://user-images.githubusercontent.com/70441233/95214823-4c498780-07be-11eb-8764-33cde0555cd7.png)

**Comment by stephenjmaher** [comment]
From what I see, `j = column_to_add[0]`. As such, you are not printing the number of columns added, but the value of `column_to_add[0]`. Could you please clarify the issue? I don't see any problem here and you should be adding a single column per iteration.

Have a look at the `vars` column in your output. It is increasing my 1 after each iteration. Presumably, the last 4 `j` outputs are from the 4 additional nodes processed.
