### ISSUE TITLE
Support for SOCP

### ISSUE THREAD

**Issue by gsagnol** [scipopt/PySCIPOpt#44]
Hi, 
currently SOCP constraints such as
x^2 + y^2 <= t^2

are treated as a non-convex quadratic constraint when passed to PySCIPOpt.

Would it be possible to develop an interface to SCIP's c-code of `cons_soc.h` ? Then, I could implement SOCPs' correctly in PICOS!

Thanks, Guillaume.

**Comment by fserra** [comment]
I guess it should be fairly simple to allow for building SOC constraints. However, allowing for building them with nice notation could be more complicated. I'll implement this

**Comment by gsagnol** [comment]
As far as I'm concerned, a low-level notation would be enough, then PICOS will do the interface from nice notation to low-level.

**Comment by fserra** [comment]
@gsagnol apparently i never got around to implement this. Do you still need this?
