### ISSUE TITLE
Can pyscipopt be used to solve polynomial objective functions? e.g. 100(x^2-y)^2 + (y-1)^2

### ISSUE THREAD

**Issue by Hamim-1204007** [scipopt/PySCIPOpt#441]
Is it possible to use pyscipopt to solve non-linear i.e. polynomial objective functions? e.g. 100(x^2-y)^2 + (y-1)^2

**Comment by fserra** [comment]
sure, you just need to model it as a constraint, see https://github.com/SCIP-Interfaces/PySCIPOpt/issues/167#issuecomment-392786274

**Comment by Hamim-1204007** [comment]
> sure, you just need to model it as a constraint, see [#167 (comment)](https://github.com/SCIP-Interfaces/PySCIPOpt/issues/167#issuecomment-392786274)

Thanks for replying. I have tried to follow your instructions but it still gives error. Here is the code that I have used:

`model = Model("Non-linear optimization")

x1 = model.addVar(vtype="C", name="x1")
x2 = model.addVar(vtype="C", name="x2")
objvar = model.addVar(name="objvar", vtype= "C", lb=None, ub=None)

model.addCons(x1 + x2 >= 5)
model.addCons(x2 <= 3)
model.addCons(objvar >= 100*(x1**2-x2)**2 + (x2 - 1)**2)

model.setObjective(objvar, "minimize")

model.optimize()

if model.getStatus() == "optimal":
    print("Optimal value:", model.getObjVal())
    print("Solution:")
    print(" x1 = ", model.getVal(x1))
    print(" x2 = ", model.getVal(x2))
else:
    print("Problem could not be solved to optimality")`

**Comment by fserra** [comment]
which errors does it give? for me it works if you add some bounds to the objective variable and I get some memory errors that I would have to look into, but this is not an error of the algorithm

**Comment by mattmilten** [comment]
closed due to inactivity
