### ISSUE TITLE
Request for SCIPgetNIntVars() and SCIPgetNBinVars() functions

### ISSUE THREAD

**Issue by ozancakiroglu95** [scipopt/PySCIPOpt#445]
Is it possible to add these two SCIP functions existing in C-API (SCIPgetNIntVars() and SCIPgetNBinVars()) as in the following documentation https://www.scipopt.org/doc/html/group__GlobalProblemMethods.php  also into the PySCIPOpt if it is not too complicated? 

Thanks in advance.

**Comment by fserra** [comment]
it is and it shouldn't be complicated. You can do it yourself and open a PR: https://github.com/SCIP-Interfaces/PySCIPOpt#extending-the-interface
Examples: https://github.com/SCIP-Interfaces/PySCIPOpt/pull/388/files
https://github.com/SCIP-Interfaces/PySCIPOpt/pull/410/files
