### ISSUE TITLE
How to abort if a certain time limit has passed and a preset objective value has been reached

### ISSUE THREAD

**Issue by kovacsrekaagnes** [scipopt/PySCIPOpt#448]
Hi, is there a way to create a function in pyscipopt which checks the objective value of my incumbent solution and the elapsed time since solution process has started and if a certain time limit has passed and a certain objective value is reached then abort the solution process? Thanks in advance.

In cplex I would do it by registering the following callback:

```
class ObjLimitCallback(cplex.callbacks.MIPInfoCallback):
    # this callback function aborts if a certain time limit has passed and we have a good enough solution
    # for a MAXIMISATION problem
    def __call__(self):
        if not self.aborted and self.has_incumbent():

            # get the objective of the incumbent solution
            obj = self.get_incumbent_objective_value()

            # get how much time has passed
            timeused = self.get_time() - self.starttime

            # if we spent enough time already and the objective is better than the goal
            if timeused > self.timelimit and obj > self.objgoal:
                print("Good enough solution at", timeused, "sec., obj =", obj, ", quitting.")
                self.aborted = True
                self.abort()
```

**Comment by fserra** [comment]
Hi

Sorry for the late reply. I guess you can implement an event handler that gets called whenever a new incumbent solution is found. There, when you find the good enough solution, you probably can just set the timelimit parameter to your preferred time.
