### ISSUE TITLE
Can we have a shape parameter to support matrix based modeling

### ISSUE THREAD

**Issue by pbpf** [scipopt/PySCIPOpt#452]
now we can create a var by 
> x=model.addVar("x", vtype="INTEGER")

can be do

> y=model.addVar("y", shape=(3,4), vtype="INTEGER")

to  create  a matrix var?

**Comment by mattmilten** [comment]
Hi! I Don't think this would help much in terms of speed/efficiency and is also not the "SCIP" way, that is constraint-based modeling.
If you can provide a working prototype, though, we will check whether this can be integrated.
