### ISSUE TITLE
documentation site down 

### ISSUE THREAD

**Issue by alicemaz** [scipopt/PySCIPOpt#453]
hi, the documentation site listed in the readme http://scip-interfaces.github.io/PySCIPOpt/docs/html returns a 404, not sure if it has moved somewhere else or is inaccessible by mistake presently

**Comment by fserra** [comment]
thanks. 
we just change the name of the organization from scip-interfaces to scipopt, so the correct link is http://scipopt.github.io/PySCIPOpt/docs/html/

**Comment by fserra** [comment]
i updated the readme. thanks!
