### ISSUE TITLE
chained expression

### ISSUE THREAD

**Issue by JPelda** [scipopt/PySCIPOpt#454]
x = pyscipopt.scip.Variable
-----------------------------
The chained expression
model.addCons(-10 <= (x <= 10)) returns a

TypeError: Can't evaluate constraints as booleans.
If you want to add a ranged constraint of the form
   lhs <= expression <= rhs
you have to use parenthesis to break the Python syntax for chained comparisons:
   lhs <= (expression <= rhs)

x = pyscipopt.scip.Expr
-------------------------
The chained expression
model.addCons(-10 <= (x <= 10)) returns a

TypeError: Can't evaluate constraints as booleans.
If you want to add a ranged constraint of the form
   lhs <= expression <= rhs
you have to use parenthesis to break the Python syntax for chained comparisons:
   lhs <= (expression <= rhs)

**Comment by fserra** [comment]
the following
```python
from pyscipopt import Model

model = Model()

x = model.addVar(name="x")

model.addCons(-10 <= (x <= 10))
```
runs without problem for me

**Comment by JPelda** [comment]
Thank you for the fast reply!

The failure occures if the lhs or the rhs is of type numpy.float64, do not know why. If parsed to float or numpy.float in advance, the addCons(lhs <= (x <= rhs)) works fine.

Best regards.

**Comment by fserra** [comment]
interesting.
so this has nothing to do with ranged constraints.

This also fails
```
cons =  model.addCons(np.float64(-10) <= x)
```

but this works
```
cons =  model.addCons(x <= np.float64(-10))
```

so my guess is that when one compares a numpy float64 with `something`, the implementation of the compare in numpy asks is `something` is nonzero or something like that and this produces the error as it calls the `__nonzero__` or `__bool__` callback of the ExprCons class (this is the error that you see: Can't evaluate constraints as booleans)

Instead when one uses `x <= np.float64(-10)` the compare of the expr is used and works correctly.
If this is the case, then there is not much we can do I guess. So maybe just use `model.chgRhs(cons, newrhs)` and `model.chgLhs(cons, newlhs)` to change the sides

**Comment by JPelda** [comment]
Thank you!
