### ISSUE TITLE
Lower and upper bounds for binary variables

### ISSUE THREAD

**Issue by choidami** [scipopt/PySCIPOpt#457]
Hello,

I wasn't sure where to ask this question, so I'm asking here.
If I load a .lp file with binary variables, does the lower and upper bounds for the binary variables automatically get set to 0 and 1 respectively?
I tried it with one lp file, and checked each variable's bounds and it seems like this is the case, but I wanted to be sure.

**Comment by mattmilten** [comment]
Yes, variables declared as binary will have bounds of 0 and 1 automatically. Having to set these manually would be kind of redundant.
