### ISSUE TITLE
Error on using left hand and right hand constraint

### ISSUE THREAD

**Issue by JPelda** [scipopt/PySCIPOpt#459]
Have a problem with the following:

ind_d = np.array([model.addVar('ind' + str(i), lb=0, ub=1, vtype='B') for i in range(6)])
Q = np.array([model.addVar('Q' + str(i), lb=-1000, ub=0) for i in range(6)])

indD = [model.addCons((1 - d) * q.getLbOriginal() <= (q <= d * q.getUbOriginal())) for d, q in zip(ind_d, Q)]

Results in:
  File "src\pyscipopt\expr.pxi", line 276, in pyscipopt.scip.Expr.__richcmp__
  File "src\pyscipopt\expr.pxi", line 64, in pyscipopt.scip._expr_richcmp
NotImplementedError

Doing
[model.addCons(q == 0) for q in Q]
and then
[model.chgRhs(...)]
[model.chgLhs(...)]
gives the error that chgRhs needs a value not an scipy.Expr.

There was are similar error that happend because one var was of type float64, but this is not the case here.
Can anyone help? I would really appreciate it!

**Comment by mattmilten** [comment]
Hi!
If you change up the parantheses in the ranged constraint, you get a more descriptive error message:

```
indD = [model.addCons(((1 - d) * q.getLbOriginal() <= q ) <= d * q.getUbOriginal()) for d, q in zip(ind_d, Q)]

TypeError: Ranged ExprCons is not well defined!
```

So, you should just separate this into two `addCons` calls and you're good:

```
indD_l = [model.addCons((1 - d) * q.getLbOriginal() <= q) for d, q in zip(ind_d, Q)]
indD_r = [model.addCons(q <= d * q.getUbOriginal()) for d, q in zip(ind_d, Q)]
```

Cheers,
Matthias
