### ISSUE TITLE
SCIP make, ERROR

### ISSUE THREAD

**Issue by zyq11223** [scipopt/PySCIPOpt#461]
After unpack the scip-xxxx.tgz,
cd scip-xxx,
then make
at last, I got  info below:
In file included from src/soplex/clufactor_rational.cpp:18:0:
src/soplex/spxdefines.h:46:43: fatal error: boost/multiprecision/number.hpp: No such file or directory

**Comment by mattmilten** [comment]
Please refer to the [SCIP webpage](scipopt.org) for help with installing SCIP. This forum is only dedicated to PySCIPOpt and requires/assumes a working installation of the SCIP Optimization Suite. Please note that installing just SCIP without the other components of the suite is not going to work. 

I recommend to *not compile* SCIP yourself and use the prebuilt installers instead.

**Comment by zyq11223** [comment]
> Please refer to the [SCIP webpage](scipopt.org) for help with installing SCIP. This forum is only dedicated to PySCIPOpt and requires/assumes a working installation of the SCIP Optimization Suite. Please note that installing just SCIP without the other components of the suite is not going to work.
> 
> I recommend to _not compile_ SCIP yourself and use the prebuilt installers instead.

would you mind please tell me where to find the prebuilt installers for linux?

**Comment by mattmilten** [comment]
Here you go: https://scipopt.org/index.php#download
