### ISSUE TITLE
Node Selection:  Segmentation Violation

### ISSUE THREAD

**Issue by ha0ransun** [scipopt/PySCIPOpt#463]
I want to test the FIFO in 1000 instances. It successfully solves 820 instances while fails in instance 821. The FIFO node selection triggers:
> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV).

but the default method will not.
Do you have any idea about this issue? I use SCIP 7.0.1, python 3.8.5. The testing instance can be found at [https://drive.google.com/file/d/1ZZPUc3rdQPAQoZqB4bqDbhSUi2BpNW7Q/view?usp=sharing](url) 
The testing code is:

```python
from pyscipopt import Model
from pyscipopt.scip import Nodesel
from pyscipopt import SCIP_PARAMSETTING

class FiFo(Nodesel):

  def nodeselect(self):
    '''first method called in each iteration in the main solving loop. '''

    leaves, children, siblings = self.model.getOpenNodes()
    nodes = leaves + children + siblings

    return {"selnode" : nodes[0]} if len(nodes) > 0 else {}

  def nodecomp(self, node1, node2):
    '''
    compare two leaves of the current branching tree
    It should return the following values:
      value < 0, if node 1 comes before (is better than) node 2
      value = 0, if both nodes are equally good
      value > 0, if node 1 comes after (is worse than) node 2.
    '''
    return 0

def set_scip(model, seed,
                     presolver=True,
                     separator=True,
                     separator_root=True,
                     propagator=True,
                     restart=True,
                     primal_heuristic=True,
                     conflict=True):

    seed = seed % 2147483648  # SCIP seed range
    # randommization
    model.setBoolParam('randomization/permutevars', True)
    model.setIntParam('randomization/permutationseed', seed)
    model.setIntParam('randomization/randomseedshift', seed)

    if not separator:
        # separation only at root node
        model.setIntParam('separating/maxrounds', 0)
    if not separator_root:
        model.setIntParam('separating/maxroundsroot', 0)
    # no restart
    if not restart:
        model.setIntParam('presolving/maxrestarts', 0)

    # if asked, disable presolving
    if not presolver:
        model.setIntParam('presolving/maxrounds', 0)
        model.setIntParam('presolving/maxrestarts', 0)

    # if asked, disable conflict analysis (more cuts)
    if not conflict:
        model.setBoolParam('conflict/enable', False)

    # if asked, disable primal heuristics
    if not primal_heuristic:
        model.setHeuristics(SCIP_PARAMSETTING.OFF)

    # if asked, disable propagation heuristics
    if not propagator:
        model.disablePropagation(False)


def test_nodesel(method='fifo'):
    m = Model()
    m.hideOutput()
    m.readProblem('instance_821.lp')
    set_scip(m, seed=0, restart=False, separator=False)
    # include node selector
    if method == 'fifo':
        m.includeNodesel(FiFo(), "testnodeselector", "Testing a node selector.", 1073741823, 536870911)
    m.optimize()


if __name__ == "__main__":
    test_nodesel('default')
    print('default success')
    test_nodesel('fifo')
    print('fifo success')
```

**Comment by fserra** [comment]
For me it solves fine. Also, the code looks fine as far as I can see. I recommend that you try again but in [debug mode](https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md#building-with-debug-information), then hopefully an assert will fail before the segmentation fault. This should give us more information.

**Comment by ha0ransun** [comment]
I tried it in debug mode, it says:

> Assertion failed: (*node == NULL || SCIPnodeGetType(*node) == SCIP_NODETYPE_SIBLING || SCIPnodeGetType(*node) == SCIP_NODETYPE_CHILD || SCIPnodeGetType(*node) == SCIP_NODETYPE_LEAF), function SCIPnodeFocus, file /Users/hanransun/PycharmProjects/scip/scip-7.0.1/src/scip/tree.c, line 4338.

**Comment by fserra** [comment]
that is weird. Can you tell me the output of `m.printVersion()`

**Comment by ha0ransun** [comment]
The version information is:

> SCIP version 7.0.1 [precision: 8 byte] [memory: block] [mode: debug] [LP solver: SoPlex 5.0.1] [GitHash: b41d526acf]
Copyright (C) 2002-2020 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)

**Comment by fserra** [comment]
I don't understand what might be going wrong. In your other examples I guess you are also getting an empty `nodes` at the end.
Which version of pyscipopt are you using? I see the following code in `nodesel.pxi`
```python
cdef SCIP_RETCODE PyNodeselSelect (SCIP* scip, SCIP_NODESEL* nodesel, SCIP_NODE** selnode):
  cdef SCIP_NODESELDATA* nodeseldata
  nodeseldata = SCIPnodeselGetData(nodesel)
  PyNodesel = <Nodesel>nodeseldata
  result_dict = PyNodesel.nodeselect()
  selected_node = <Node>(result_dict.get("selnode", None))
  selnode[0] = selected_node.scip_node
  return SCIP_OKAY
```
So when `nodes` is the empty list, you are going to return nothing, so `selected_node` is going to be None. I can only imagine that `selected_node.scip_node` is going to be NULL wwhen `selected_node` is None... but apparently this is not the case.

I guess one could add `if selected_node == None: selnode[0] = NULL`

can you test if that fixes your issue?

**Comment by ha0ransun** [comment]
It fixes my issue.

```python
cdef SCIP_RETCODE PyNodeselSelect (SCIP* scip, SCIP_NODESEL* nodesel, SCIP_NODE** selnode):
  cdef SCIP_NODESELDATA* nodeseldata
  nodeseldata = SCIPnodeselGetData(nodesel)
  PyNodesel = <Nodesel>nodeseldata
  result_dict = PyNodesel.nodeselect()
  selected_node = <Node>(result_dict.get("selnode", None))
  if selected_node == None:
    selnode[0] = NULL
  else:
    selnode[0] = selected_node.scip_node
  return SCIP_OKAY
```

**Comment by Hust1Booze** [comment]
hello, this does solve my problem, thanks 
and when custom nodecomp() function, it does will appear this problem !
