### ISSUE TITLE
import pyscipopt  error on ubuntu 1604

### ISSUE THREAD

**Issue by lidonghui-ai** [scipopt/PySCIPOpt#465]
from pyscipopt.scip      import Model
ImportError: libscip.so.7.0: cannot open shared object file: No such file or directory

when I try 'import pyscipopt', it showed the error above. How can I solve it? The scip version is 4.0.0 and pyscipopt version is 1.2.

**Comment by fserra** [comment]
i don't know why it is looking for libscip 7. Why don't you update to the latest version?

**Comment by mattmilten** [comment]
closed for inactivity and (very) outdated Ubuntu version
