### ISSUE TITLE
how to use addConsIndicator?

### ISSUE THREAD

**Issue by Killajam** [scipopt/PySCIPOpt#466]
I am trying to implement a piecewise function like:
`if x >= 1:
    y = 1
 if x = 0:
    y = 0`
so i found the 'addConsIndicator' but i don't know how to use it.
Here is my code:
`from pyscipopt import Model, quicksum

model = Model("transport optimization")
model.hideOutput(quiet=False)
model.enableReoptimization()

decision_var = [0 for i in range(5)]
indicator = [0 for i in range(5)]

for i in range(5):
    decision_var[i] = model.addVar(vtype='I', name='%s' % i, ub=3)
for i in range(5):
    indicator[i] = model.addVar(vtype='B', name='indicator%s' % i)
    model.addConsCardinality(cons=-decision_var[i] <= -1, binvar=indicator[i])
    # model.addConsIndicator(cons=decision_var[i] <= 0, binvar=0)

obj = quicksum(decision_var)
model.setObjective(obj, sense="minimize")
model.optimize()`

So how should I implement the piecewise function through addConsIndicator, or is there another method?

**Comment by fserra** [comment]
You are calling cons cardinality...
In your commented call to consindicator you are saying `binvar = 0` which doesn't seem to make much sense.
The documentation says:
```
        """Add an indicator constraint for the linear inequality 'cons'.

        The 'binvar' argument models the redundancy of the linear constraint. A solution for which
        'binvar' is 1 must satisfy the constraint.
```
the following modification of your code runs.

```
from pyscipopt import Model, quicksum

model = Model("transport optimization")
model.enableReoptimization()

decision_var = [0 for i in range(5)]
indicator = [0 for i in range(5)]

for i in range(5):
    decision_var[i] = model.addVar(vtype='I', name='%s' % i, ub=3)
for i in range(5):
    indicator[i] = model.addVar(vtype='B', name='indicator%s' % i)
    model.addConsIndicator(cons=decision_var[i] <= 0, binvar=indicator[i])

obj = quicksum(decision_var)
model.setObjective(obj, sense="minimize")
model.optimize()
```

From the documentation I would guess that you need to implement two indicator constraints one to force that `y` is 1 when `x ` is 1 and the other to force it to be 0

You can also try to model with big m constraints.
