### ISSUE TITLE
ModuleNotFoundError: No module named 'pyscipopt', but successful installation in terminal

### ISSUE THREAD

**Issue by mariaeileen** [scipopt/PySCIPOpt#467]
Hi, 

I have successfully installed pyscipopt and it seems as if it is stored within the library for python3.7. I need to use pyscipopt in a script using python 3.8. However, "import pyscipopt" gives a ModuleError for both python 3.7 and python 3.8. 

$ pip install -U pyscipopt
**Requirement already satisfied: pyscipopt in /Users/mariaeileenhubbuck/opt/anaconda3/lib/python3.7/site-packages (3.1.0)**

From shell:
ModuleNotFoundError: No module named 'pyscipopt'

Does anyone know how I can get pyscipopt to work? Seems like it might be an error where its stored, but its strange that it doesnt work for either Python3.8 or Python 3.7. I have downloaded SCIP beforehand and followed the instructions for installing pyscipopt correctly. 
- Maria

**Comment by mattmilten** [comment]
You need to make sure to be in the same environment you installed PySCIPOpt into when trying to use/import the module. You may want to run `pip list` to see which packages are installed in the current env.

Also, you should try running `python -m pip install pyscipopt`. This ensures that you are not using a different pip binary from another environment.

**Comment by mariaeileen** [comment]
Hi, 
I'm running my script in IDLE Python3.8 and this is my sys.path: 
>>> print(sys.path)
['/Users/mariaeileenhubbuck/Documents/Discrete Optimization/facility', '/Users/mariaeileenhubbuck/Documents', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages']

After what I understand, I will need to install pyscipopt within the path for the site packages as one of the paths listed above. However, I can't seem to install with the pip install or python -m pip install pyscipopt as you suggested as I only get **Requirement already satisfied: pyscipopt in /Users/mariaeileenhubbuck/opt/anaconda3/lib/python3.7/site-packages (3.1.0)**. 

Do I need to append the above path to my sys.path for it to work? I have tried to uninstall pyscipopt in order to start the whole process over again but I'm not able to uninstall all parts of pyscipopt, see message from terminal below:
**Would remove**:
    /Users/mariaeileenhubbuck/opt/anaconda3/lib/python3.7/site-packages/PySCIPOpt-3.1.0.dist-info/*
    /Users/mariaeileenhubbuck/opt/anaconda3/lib/python3.7/site-packages/pyscipopt/*
  **Would not remove (might be manually added)**:
    /Users/mariaeileenhubbuck/opt/anaconda3/lib/python3.7/site-packages/pyscipopt/.DS_Store

I believe that this error lies within the paths / environments, but I cannot seem to figure out how to solve it. 
-Maria

**Comment by mariaeileen** [comment]
Additional info: 
PySCIPOpt is listed as when I type pip list.

**Comment by mariaeileen** [comment]
I have tried to add the path to the sitepackages from anaconda into my pythonpath as pyscipopt is currently installed within
/Users/mariaeileenhubbuck/opt/anaconda3/lib/python3.7/site-packages, but without any luck

'>>> import sys
'>>> print(sys.path)
['/Users/mariaeileenhubbuck/Documents/Discrete Optimization/facility', '/Users/mariaeileenhubbuck/Documents', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages']
'>>> sys.path.append (r',/Users/mariaeileenhubbuck/opt/anaconda3/lib/python3.7/site-packages')
'>>> import pyscipopt
Traceback (most recent call last):
  File "<pyshell#27>", line 1, in <module>
    import pyscipopt
ModuleNotFoundError: No module named 'pyscipopt'`

Do you know what else I can try?
-Maria

**Comment by mattmilten** [comment]
Hmm, that sounds like your Python environments are not cleanly separated and there are maybe some globally installed packages. I suggest you delete all traces of PySCIPOpt and start again with a fresh environment. 

Do you really need IDLE? I'd recommend trying to import pyscipopt in a simple Python shell first.

**Comment by rodfloripa** [comment]
I have the same problem. I run pip list and PySCIPOpt is there, but I can't import the library.

**Comment by mattmilten** [comment]
Well, the error message reads:
```
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory
```
So you should try installing libgfortran. Usually, this is encoded as a dependency of SCIP and should be installed when installing SCIP via the provided installer packages. If this is not done for whatever reason, you should install it manually.

**Comment by rodfloripa** [comment]
It worked with the right version of SCIP Suite. I just posted here to help others that may have the same problem.
