### ISSUE TITLE
Could you please provide some learning resources about "branchrule, includeBranchrule"?

### ISSUE THREAD

**Issue by ll906875341** [scipopt/PySCIPOpt#468]
Hello everyone,
First of all, thank you very much for helping us with PySCIPOpt.
I recently learned the usage of pyscipopt, and I learned the simple usage of pyscipopt in "Mathematical Optimization: Solving Problems using SCIP and Python". I now want to learn the introduction and usage of some advanced content of pyscipopt such as "setIntParam, branchrule, includeBranchrule". but I have been searching on the Internet for a long time, and I have not found a suitable learning resource. Excuse me, are there any learning materials about the introduction and usage of advanced content such as "setIntParam, branchrule, includeBranchrule"?
Very grateful for your help.

**Comment by fserra** [comment]
Hi

you need to remember that pyscipopt is just a thin wrapper of scip. So what you are really asking is learning material to learn SCIP. You can probably start by checking the documentation: https://scipopt.org/doc/html/BRANCH.php

`setIntParam` is just to set a parameter of type int. You can find a list of all parameters here https://scipopt.org/doc/html/PARAMETERS.php

**Comment by ll906875341** [comment]
Thank you very much for your help
good luck
