### ISSUE TITLE
Install error with SCIPOptSuite-7.0.2-Darwin and python 3.8

### ISSUE THREAD

**Issue by rlacjfjin** [scipopt/PySCIPOpt#469]
I met with such errors when install pyscipopt:(MacOS) In windows, it's ok......
1. echo $SCIPOPTDIR
/Users/jinzhe/Downloads/SCIPOptSuite-7.0.2-Darwin

2. >>> import pyscipopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jinzhe/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: dlopen(/Users/jinzhe/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so, 2): Library not loaded: libscip.7.0.dylib
  Referenced from: /Users/jinzhe/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so
  Reason: image not found

In $SCIPOPTDIR:
(base) jinzhe@jz SCIPOptSuite-7.0.2-Darwin % ls
bin     include lib

and in lib directory, 
cmake                 libgcg.3.0.dylib      libscip.7.0.2.0.dylib libscip.dylib         libsoplex.a           libzimpl.a
libgcg.3.0.4.0.dylib  libgcg.dylib          libscip.7.0.dylib     libsoplex-pic.a       libzimpl-pic.a

I don't know how to do...

**Comment by mattmilten** [comment]
Hi!

This does not look like you have *installed* SCIP - you seem to have just downloaded the installer package. When SCIP is installed, you should be able to run `scip` in a terminal and the `libscip.dylib` library should be available on your system - probably in /Library or something similar.

Please refer to the SCIP documentation for further information on how to install SCIP: https://scipopt.org

**Comment by rlacjfjin** [comment]
In fact, I have installed scip&nbsp; and can use scip.solve&nbsp; problems.
I also installed with cmake.
both of them are all have such errors.
In terminal,&nbsp; SCIP command can be run.



---Original---

**Comment by rlacjfjin** [comment]
> Hi!
> 
> This does not look like you have _installed_ SCIP - you seem to have just downloaded the installer package. When SCIP is installed, you should be able to run `scip` in a terminal and the `libscip.dylib` library should be available on your system - probably in /Library or something similar.
> 
> Please refer to the SCIP documentation for further information on how to install SCIP: https://scipopt.org



> Hi!
> 
> This does not look like you have _installed_ SCIP - you seem to have just downloaded the installer package. When SCIP is installed, you should be able to run `scip` in a terminal and the `libscip.dylib` library should be available on your system - probably in /Library or something similar.
> 
> Please refer to the SCIP documentation for further information on how to install SCIP: https://scipopt.org

Thanks for your reply.
I have been installed scip.
scip -f egout.mps
SCIP version 7.0.2 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: SoPlex 5.0.2] [GitHash: e9d280a398]
Copyright (C) 2002-2020 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)

External codes:
  SoPlex 5.0.2         Linear Programming Solver developed at Zuse Institute Berlin (soplex.zib.de) [GitHash: e24c304e]
  CppAD 20180000.0     Algorithmic Differentiation of C++ algorithms developed by B. Bell (www.coin-or.org/CppAD)
  ZLIB 1.2.11          General purpose compression library by J. Gailly and M. Adler (zlib.net)
  GMP 6.2.0            GNU Multiple Precision Arithmetic Library developed by T. Granlund (gmplib.org)
  ZIMPL 3.4.0          Zuse Institute Mathematical Programming Language developed by T. Koch (zimpl.zib.de)
  PaPILO 1.0.2         parallel presolve for integer and linear optimization (https://github.com/lgottwald/PaPILO) [GitHash: 62d2842]
  bliss 0.73p          Computing Graph Automorphism Groups by T. Junttila and P. Kaski (http://www.tcs.hut.fi/Software/bliss/)

user parameter file <scip.set> not found - using default parameters

read problem <egout.mps>
============

original problem has 141 variables (55 bin, 0 int, 0 impl, 86 cont) and 98 constraints

solve problem
...
...



and my scip path is:  /Users/jinzhe/Downloads/SCIPOptSuite-7.0.2-Darwin/bin/scip
and the SCIPOPTDIR is :/Users/jinzhe/Downloads/SCIPOptSuite-7.0.2-Darwin

I think everything is ok, but when pip install pyscipopt and import pyscipopt, it's not ok...

**Comment by mattmilten** [comment]
Then, maybe you need to modify your `DYLD_LIBRARY_PATH` so your system can find the library at runtime.

**Comment by rlacjfjin** [comment]
> Then, maybe you need to modify your `DYLD_LIBRARY_PATH` so your system can find the library at runtime.

Thanks,
Now, it's work well.
