### ISSUE TITLE
Add event handler for timer event

### ISSUE THREAD

**Issue by xk-rizo** [scipopt/PySCIPOpt#471]
Hi! I want to define an event handler that is triggered every certain amount of time (say thirty seconds). It will check if a source external to the solver has produced any solutions and add them to the solver.

I know how to write the event handler to check the external source and add the solutions, but I don't know how to link the event handler to a "timer event" (I know there is an event type SCIP_EVENTTYPE_SYNC but don't know if/how to use it). How should it be done?

**Comment by mattmilten** [comment]
Hi!
The SYNC event type is meant for the concurrent solver - I don't think you can use this to implement your idea. I am also not aware of an event type that acts on a timer.
I suggest you hook your custom timer into a type of event that is called pretty frequently, like [SCIP_EVENTTYPE_NODESOLVED](https://scipopt.org/doc/html/type__event_8h.php#aa0a891248bca1f5312b56edd0a10df2c). So, you would just query the time whenever this event is called and only in your defined time intervals, you would check for a new external solution that you could add.

Cheers,
Matthias
