### ISSUE TITLE
Different results in powerShell and pycharm ipython console

### ISSUE THREAD

**Issue by JPelda** [scipopt/PySCIPOpt#472]
Dear developers,

why is the ipython console (pycharm) giving different results than the powershell? I exported the settings from powershell and did model.readparams() in the ipython console, still different results. I also have no additional params setting in the python script given. In the powershell the problem is loaded by scip -f problem.cip, scip.set is given and is also loaded.

ipython:
SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 2.00
Solving Nodes      : 2
Primal Bound       : +0.00000000000000e+00 (1 solutions)
Dual Bound         : +0.00000000000000e+00
Gap                : 0.00 %

powershell:
SCIP Status        : problem is solved [infeasible]
Solving Time (sec) : 2.00
Solving Nodes      : 1
Primal Bound       : +1.00000000000000e+20 (0 solutions)
Dual Bound         : +1.00000000000000e+20
Gap                : 0.00 %

**Comment by mattmilten** [comment]
Hi JPelda, it is impossible to diagnose the issue with such little information available. Please try to come with a small reproducible example so we can try to understand what SCIP might be doing differently in both runs. It would also help to see a full log of both of your runs.

Cheers,
Matthias

**Comment by JPelda** [comment]
Dear Matthias,

Thank you for your fast reply. Appended you will find the files.

I am using Windows 10.
External codes from the statistics
[github_question.zip](https://github.com/scipopt/PySCIPOpt/files/5794760/github_question.zip)
:
  SoPlex 5.0.1         Linear Programming Solver developed at Zuse Institute Berlin (soplex.zib.de) [GitHash: fcd2a2a5]
  CppAD 20180000.0     Algorithmic Differentiation of C++ algorithms developed by B. Bell (www.coin-or.org/CppAD)
  MPIR 3.0.0           Multiple Precision Integers and Rationals Library developed by W. Hart (mpir.org)
  ZIMPL 3.4.0          Zuse Institute Mathematical Programming Language developed by T. Koch (zimpl.zib.de)
  PaPILO 1.0.1         parallel presolve for integer and linear optimization (https://github.com/lgottwald/PaPILO) [GitHash: 0638fc4]
  bliss 0.73p          Computing Graph Automorphism Groups by T. Junttila and P. Kaski (http://www.tcs.hut.fi/Software/bliss/)
  Ipopt 3.12.9         Interior Point Optimizer developed by A. Waechter et.al. (www.coin-or.org/Ipopt)

I think the external codes will also apply to the PyCharm console, as it is using the same path to scip as scip.exe? There is also a Ipopt 3.11 on my computer's path but as I installed a pre-compiled scip (from zuse website) I think this won't matter.

Best regards,
Johannes

**Comment by mattmilten** [comment]
Thanks for the files! I was able to reproduce the behavior and I am just as confused as you are. Saving the constructed model to a CIP file and reading it in again, leads to a different result than solving the original model. Interestingly, the first difference appears already in the number of variables and constraints, so I guess there is something off in the way SCIP handles the data.

@CGraczyk, could you please have a look?

**Comment by leoneifler** [comment]
I think (95% percent sure) that this is a numerical issue. Your `Q_pipes` variables have lower bounds that come from an involved computation. These variables are then used in a quadratic equality constraint. When you write your model to a `.cip` file the variable bounds get printed with `15` decimal digits. I think that this slight rounding causes infeasibility in your problem. You can check if this is the case by writing out the solution you get from running inside `PySCIPOPT` and then reading in this solution in the shell together with the `cip` file. 

Things you could try: If possible the best way is to find a formulation for your model that is numerically more stable. You could also relax feasibility tolerances.
