### ISSUE TITLE
PY_SCIP_CALL

### ISSUE THREAD

**Issue by JPelda** [scipopt/PySCIPOpt#473]
Trying to import the default plugins via 

model.includeDefaultPlugins().

But I get:
model.includeDefaultPlugins()
  File "src\pyscipopt\scip.pyx", line 1027, in pyscipopt.scip.Model.includeDefaultPlugins
  File "src\pyscipopt\scip.pyx", line 248, in pyscipopt.scip.PY_SCIP_CALL
Exception: SCIP: error in input data!

cpython is installed and the scip is in the path-environment as well as SCIPOPTDIR is set as recommended.

I am using pyscipopt 3.0.4 from anaconda.
I like to include some propagators, any help is appreciated.

**Comment by fserra** [comment]
it seems that when you create a model, the default plugins are already there by default. I don't know exactly when the error occurs, but it should fail when one tries to include the same plugin twice.

**Comment by mattmilten** [comment]
@JPelda, please close this issue if there isn't anything else to do here.

**Comment by JPelda** [comment]
Thank you!
