### ISSUE TITLE
Make pyscipopt.scip.Variable hashable

### ISSUE THREAD

**Issue by anagorko** [scipopt/PySCIPOpt#478]
If v is of Variable type I need to use str(v) or v.ptr() if I need to use v as a dictionary key. Couldn't .ptr() be also variable's .hash()?

**Comment by mattmilten** [comment]
Hmm, there might have been a reason for not doing this but I cannot recall it right now. Can you just implement this, please, and submit a Pull Request?

Thanks!

**Comment by fserra** [comment]
I think it was because when one compares variables, constraints are created and for hashing one needs to decide whether the things are equal or not... could that have been the reason?

**Comment by mattmilten** [comment]
Oh yeah, that sounds very reasonable.

**Comment by anagorko** [comment]
Thank you for the explanation.

After adding .__hash__ to the Variable class expression "x == y" evaluates to False (and it should be ExprCons(Expr({Term(x1): 1.0, Term(x2): -1.0}), 0.0, 0.0)).

I'm closing this issue.
