### ISSUE TITLE
lotsizing_lazy.py 

### ISSUE THREAD

**Issue by rlacjfjin** [scipopt/PySCIPOpt#480]
Hi,
In the example lotsizing_lazy.py, how can I sure that the cutting plane is successful to used?
The function addcut in class Conshdlr_sils is not called?

**Comment by mattmilten** [comment]
Are you talking about [this file](https://github.com/scipopt/PySCIPOpt/blob/master/examples/finished/lotsizing_lazy.py)?
`addcut()` is called in the `conscheck()` and `consenfolp()` callbacks that are called from within SCIP. If you don't believe that the code is executed, just add a print statement or use a debugger to step through.
