### ISSUE TITLE
How can I access which constraints are unsatisfied when the optimization result is infeasible?

### ISSUE THREAD

**Issue by fabulynn** [scipopt/PySCIPOpt#486]

**Comment by marios-stam** [comment]
Hello did you find any solution to this?

**Comment by Joao-Dionisio** [comment]
Hello, @marios-stam! I haven't found an easy way to do this, but maybe the page on [Conflict Analysis](https://scipopt.org/doc/html/CONF.php) can help.

**Comment by marios-stam** [comment]
Thank you very much for the guidance. Maybe I should open a new issue either way for people to look at since I do not think that this one is supposed to be closed.

**Comment by Joao-Dionisio** [comment]
I agree, @marios-stam! I'll just post the same answer when you do :)
