### ISSUE TITLE
trysol does not work

### ISSUE THREAD

**Issue by jan-fischer10** [scipopt/PySCIPOpt#487]
Dear all,

I am currently working with the Pyscipopt interface to set up a Branch and Price Solver using the language Python. However, I came to realize that trySol and writeLP are not working for me. I tried these commands on Visual Studio Code and Anaconda Spyder. Simply nothing seems to happen after adding the solution. In Spyder the Input number jumps back to „In [1]“ and saved objects seem to be inaccessable. 

Do you know about this issue? If so, I would be glad to know how to fix this issue. I was trying to use the trySol command to add a starting solution to my model. So I am looking forward to at least get this method working. 

Thanks for your time. 

Best

    solution = master.createSol(None)
    # for each nonzero variable
    for key in dG:
        master.setSolVal(solution, d[key], dG[key])
    for key in wG:
        master.setSolVal(solution, w[key], wG[key])
    for key in zG:
        master.setSolVal(solution, z[key], zG[key])
    
    master.trySol(solution)

**Comment by mattmilten** [comment]
Hi Jan,

please make sure the solution is not a partial solution but contains values for all variables. Also, please check the return value of `trySol()` - it signals whether the new solution was accepted and stored.

Cheers
Matthias

**Comment by jan-fischer10** [comment]
Thanks for your response! 

I tried to do the same as in the test_heur example and I fixed all variables now. It SEEMS to work now but I think it doesn't do what I expected. My idea was to give a **starting solution** and let SCIP start there. The given solution is at most 7 % away from the optimal solution and I cannot believe SCIP has found the optimal solution within such short time. So my impression is that SCIP sets the variables to the values I suggested and checks for feasibility. Since the values are all feasible the result is optimal solution found with gap 0.0 %.

**Is there another way how to suggest a starting solution?** The function addSol gives the same result: optimal solution found.

**Comment by CGraczyk** [comment]
Could you post the output of SCIP when solving this problem after your added solution?
Use model.redirectOutput() if you haven't already.

Also, trySol should not be called in the Problem stage of SCIP, assuming you are adding the initial solution to SCIP, instead use addSol - the documentation here seems unclear.
The same issue is with writeLP (which you mentioned in your email) which is also not accessible in the problem stage, where the LP is not yet constructed (wait for solving stage).

**Comment by jan-fischer10** [comment]
Ok, I tried both, addSol and trySol using the code given in the example file. So I defined the class MyHeur and included my heuristic with the ```timemask = SCIP_HEURTIMING.BEFORENODE```. I am getting the output printed below. 

So you mean I should call trySol and writeLP after the problem has been optimized and addSol for introducing a starting solution. I always used writeLP after solving as far as I know. 

**Output when using trySol:**
```
User-callback calls 1301, time in user-callback 0.04 sec
presolving:
   (1.0s) symmetry computation started: requiring (bin +, int -, cont +), (fixed: bin -, int +, cont -)
   (316.0s) symmetry computation finished: 517 generators found (max: 517, log10 of symmetry group size: inf)
   (316.0s) no symmetry on binary variables present.
presolving (0 rounds: 0 fast, 0 medium, 0 exhaustive):
 0 deleted vars, 0 deleted constraints, 0 added constraints, 0 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 0 cliques
presolved problem has 123600 variables (118800 bin, 0 int, 0 impl, 4800 cont) and 49300 constraints
  49300 constraints of type <linear>
transformed objective value is always integral (scale: 1)
Presolving Time: 315.00

solution value 1 violates bounds of <t_z_2.15.16>[-0,0] by 1
 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
  320s|     1 |     0 |  2981 |     - |   567M |   0 | 123k|  33k|  33k|   0 |  0 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  338s|     1 |     0 |  9286 |     - |   588M |   0 | 123k|  33k|  34k| 500 |  1 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  339s|     1 |     0 |  9966 |     - |   591M |   0 | 123k|  33k|  34k| 974 |  2 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  339s|     1 |     0 | 10724 |     - |   597M |   0 | 123k|  33k|  35k|1249 |  3 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  340s|     1 |     0 | 11075 |     - |   600M |   0 | 123k|  33k|  35k|1379 |  4 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  342s|     1 |     0 | 11214 |     - |   605M |   0 | 123k|  33k|  35k|1416 |  5 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  343s|     1 |     0 | 11543 |     - |   609M |   0 | 123k|  33k|  35k|1583 |  6 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  343s|     1 |     0 | 11714 |     - |   612M |   0 | 123k|  33k|  35k|1630 |  7 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  344s|     1 |     0 | 11924 |     - |   616M |   0 | 123k|  33k|  35k|1667 |  8 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  346s|     1 |     0 | 12306 |     - |   620M |   0 | 123k|  33k|  35k|1713 |  9 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  347s|     1 |     0 | 12578 |     - |   623M |   0 | 123k|  33k|  35k|1753 | 10 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  348s|     1 |     0 | 13760 |     - |   628M |   0 | 123k|  33k|  35k|1919 | 11 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  349s|     1 |     0 | 14530 |     - |   631M |   0 | 123k|  33k|  35k|2055 | 12 |   5 |   0 | 0.000000e+00 |      --      |    Inf | unknown
  427s|     1 |     0 | 17049 |     - |   656M |   0 | 123k|  33k|  35k|2055 | 12 |  11 |  36 | 0.000000e+00 |      --      |    Inf | unknown
  427s|     1 |     0 | 17196 |     - |   660M |   0 | 123k|  33k|  35k|2068 | 13 |  11 |  36 | 0.000000e+00 |      --      |    Inf | unknown
 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
  427s|     1 |     0 | 17215 |     - |   660M |   0 | 123k|  33k|  35k|2071 | 14 |  11 |  36 | 0.000000e+00 |      --      |    Inf | unknown
  432s|     1 |     2 | 17305 |     - |   660M |   0 | 123k|  33k|  35k|2071 | 14 |  11 |  55 | 0.000000e+00 |      --      |    Inf | unknown
solution value 1 violates bounds of <t_z_2.15.16>[-0,0] by 1
solution value 1 violates bounds of <t_z_2.15.16>[-0,0] by 1
solution value 1 violates bounds of <t_z_2.15.16>[-0,0] by 1
solution value 1 violates bounds of <t_z_2.15.16>[-0,0] by 1
solution value 1 violates bounds of <t_z_2.15.16>[-0,0] by 1
solution value 1 violates bounds of <t_z_2.15.16>[-0,0] by 1
solution value 1 violates bounds of <t_z_2.15.16>[-0,0] by 1
solution value 1 violates bounds of <t_z_2.15.16>[-0,0] by 1
solution value 1 violates bounds of <t_z_2.15.16>[-0,0] by 1
solution value 1 violates bounds of <t_z_2.15.16>[-0,0] by 1
L 445s|    11 |     0 | 18969 | 575.3 |    alns|  10 | 123k|  33k|  33k|2131 |  2 |  11 |  55 | 0.000000e+00 | 0.000000e+00 |   0.00%| 100.00%

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 445.00
Solving Nodes      : 11
Primal Bound       : +0.00000000000000e+00 (1 solutions)
Dual Bound         : +0.00000000000000e+00
Gap                : 0.00 %
```

**and the output for addSol** (here SCIP probably doesnt try to work around the inconsistency with the one variable bound):
```
User-callback calls 1706, time in user-callback 0.04 sec
presolving:
   (1.0s) symmetry computation started: requiring (bin +, int -, cont +), (fixed: bin -, int +, cont -)
   (309.0s) symmetry computation finished: 517 generators found (max: 517, log10 of symmetry group size: inf)
   (309.0s) no symmetry on binary variables present.
presolving (0 rounds: 0 fast, 0 medium, 0 exhaustive):
 0 deleted vars, 0 deleted constraints, 0 added constraints, 0 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 0 cliques
presolved problem has 123600 variables (118800 bin, 0 int, 0 impl, 4800 cont) and 49300 constraints
  49300 constraints of type <linear>
transformed objective value is always integral (scale: 1)
Presolving Time: 308.00

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
Y 310s|     1 |     0 |     0 |     - |  PyHeur|   0 | 123k|  33k|   0 |   0 |  0 |   0 |   0 | 0.000000e+00 | 0.000000e+00 |   0.00%| unknown

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 310.00
Solving Nodes      : 1
Primal Bound       : +0.00000000000000e+00 (1 solutions)
Dual Bound         : +0.00000000000000e+00
Gap                : 0.00 %
```

**Comment by jan-fischer10** [comment]
So the problem is still there. As I said, it seems like SCIP simply assumes my given solution and prints "problem is solved". This does not look to me like a starting solution. Has someone ever implemented a starting solution with PYSCIPOPT and can share his experience? Or is someone seeing the mistake in following the example file to trysol for a starting solution to my MIP?

**Comment by CGraczyk** [comment]
> Thanks for your response!
> 
> I tried to do the same as in the test_heur example and I fixed all variables now. It SEEMS to work now but I think it doesn't do what I expected. My idea was to give a **starting solution** and let SCIP start there. The given solution is at most 7 % away from the optimal solution and I cannot believe SCIP has found the optimal solution within such short time. So my impression is that SCIP sets the variables to the values I suggested and checks for feasibility. Since the values are all feasible the result is optimal solution found with gap 0.0 %.
> 
> **Is there another way how to suggest a starting solution?** The function addSol gives the same result: optimal solution found.

So it is difficult to tell you anything practical here really - have you checked if your added solution is actually optimal? have you solved the instance without any starting solution and SCIP returned a different solution? have you checked if the solution SCIP has given after adding the starting solution is different from what you have added? 

In the case of trySol there have been 11 nodes explored as you can see in the output - so your claim of "scip simply returning problem solved because the input values are feasible" does not make sense - is this output different if you don't add/try anything?
In the second case of addSol there is the case that SCIP seems to just check the solution for optimality and stop.
If your solution is already a global optimum there is of course nothing left to do.

Is there actually a concrete problem here that is happening? because without having your complete program the question stands if this is a SCIP / PySCIP / general coding problem or simply a result of the optimization problem you are attempting to solve.
Which of course I could not tell you.

Have you tried a minimal example to test your heuristic and solutions etc. to test your hypothesis of SCIP not solving the problem - and showcasing the issue you are facing here?
