### ISSUE TITLE
NotImplementedError of quicksum occurs when building Model

### ISSUE THREAD

**Issue by HS-ielab** [scipopt/PySCIPOpt#489]
when I set the objective using `quicksum` like this: 
`model.setObjective(quicksum(alpha*(case.loc[items[i]]-a[i])*price.loc[items[i]]/2 for i in range(I) for s in range(S)))`
NotImplementedError occurs.

It's intesting that before setting objective function, quicksum is used in adding cons, it works.

The detail info:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/yanghuasheng/Documents/dev/pythonProject/logitstics_opt.py", line 38, in <module>
    model.setObjective(quicksum(alpha*(case.loc[items[i]]-a[i])*price.loc[items[i]]/2 for i in range(I) for s in range(S)))
  File "src/pyscipopt/expr.pxi", line 363, in pyscipopt.scip.quicksum
  File "src/pyscipopt/expr.pxi", line 205, in pyscipopt.scip.Expr.__iadd__
NotImplementedError

**Comment by fserra** [comment]
interesting. This is not a problem of quick sum but of the expression that you are building. As the error says, apparently the `iadd` is not implemented in `Expr`. I don't know exactly how quicksum is adding things but it must be doing something like `bla += bli` and this seems to be not supported by `Expr`.... If this is the case, the fix should be to implement the `__iadd__` method for expressions... but I am surprised that we haven't seen this before, so maybe I am mistaken. @CGraczyk can you have a look please?

**Comment by HS-ielab** [comment]
> interesting. This is not a problem of quick sum but of the expression that you are building. As the error says, apparently the `iadd` is not implemented in `Expr`. I don't know exactly how quicksum is adding things but it must be doing something like `bla += bli` and this seems to be not supported by `Expr`.... If this is the case, the fix should be to implement the `__iadd__` method for expressions... but I am surprised that we haven't seen this before, so maybe I am mistaken. @CGraczyk can you have a look please?

Thank you @fserra  and @CGraczyk .

Here are more information.
1. In my test code, adding cons and objective are OK and the model could be well solved.
`model.addCons(quicksum(d[(i, s)]*lam[i] for i in range(I) for s in range(S)) <= M)`
`model.setObjective(quicksum(alpha*(P[i]-a[i])*c[i]/2 - o*d[(i, s)]*Y*lam[i] for i in range(I) for s in range(S)))`

2. But when I try to replace parameter datas (d, P, and c above) from realistic case by pandas DataFrame, the error occurs. and it only occurs when setting objective function but good when adding cons.
`model.addCons(quicksum(demand.loc[(stores[s], items[i])].values[0]*lam[i] for i in range(I) for s in range(S) if (stores[s], items[i]) in demand.index) <= M)`
`model.setObjective(quicksum(alpha*(case.loc[items[i]]-a[i])*price.loc[items[i]]/2 for i in range(I) for s in range(S))
                   - quicksum(o*demand.loc[(stores[s], items[i])]*Y*lam[i] for i in range(I) for s in range(S) if (stores[s], items[i]) in demand.index))`

**Comment by HS-ielab** [comment]
I have fixed the problem.
pandas dataFrame.loc returns a series. So it couldn't be added into the expr directly. 
model.setObjective(quicksum(alpha*(case.loc[items[i]]`.values[0]`-a[i])*price.loc[items[i]]`.values[0]`/2 for i in range(I) for s in range(S))
                   - quicksum(o*demand.loc[(stores[s], items[i])]`.values[0]`*Y*lam[i] for i in range(I) for s in range(S) if (stores[s], items[i]) in demand.index))
Sorry for my negligence
