### ISSUE TITLE
How to Extending the interface?

### ISSUE THREAD

**Issue by Fengyuan-Shi** [scipopt/PySCIPOpt#492]
I have read the Extending the interface section of the ReadMe. Now I add a function at `scip.pyx`
`
    def printInfo(self):
        print('customized function')
`
and reference the`printInfo()` by 
`
        m = scip.Model()
        m.printInfo()
`
a error information is reported as: 
> AttributeError: 'pyscipopt.scip.Model' object has no attribute 'printInfo'

Could anyone help me?

**Comment by CGraczyk** [comment]
Hm this does seem weird, maybe the python import is not recognizing the changes in scip.pyx correctly?

**Comment by Fengyuan-Shi** [comment]
> Hm this does seem weird, maybe the python import is not recognizing the changes in scip.pyx correctly?
> Have you tried recompiling pyscipopt after adding your new function?

Absolutely weir, I have tried two way, first is to add that function in the source code `scip.pyx` and run `python setup.py install`, second is install pyscipopt without that function then add it into `scip.pyx` which function `getDualboundRoot` is referenced at. Neither of them worked. -_-!

**Comment by mattmilten** [comment]
Hi @Fengyuan-Shi, you need to make sure that the pyscipopt module that you import in your code is really the one that contains your new changes. Usually, you can just override the currently installed version by running `python setup.py install` or `pip install .` from within your current environment. Another alternative is to set up a new virtual environment and then run the install command without getting PySCIPOpt from PyPI first - this should guarantee that you are using your custom version.

I hope that helps.
