### ISSUE TITLE
Segfault when using Null solution

### ISSUE THREAD

**Issue by AntoinePrv** [scipopt/PySCIPOpt#493]
## Problem
The following code crashes with `[1]    4536 segmentation fault (core dumped)  python3 crash.py`.
```python
import pyscipopt

model = pyscipopt.Model()

x = model.addVar("x")
y = model.addVar("y", vtype="INTEGER")
model.setObjective(x + y)
model.addCons(2*x - y*y >= 0)

sol = model.getBestSol()

# Any of this lines would segfault
print(sol)
model.getSolObjVal(sol)
```
If `print(sol)` is remove, the code runs fine.

## Diagnostic
For print, Gdb suggest segfaults is coming from `SCIPgetSolVal` in [Solution.__repr__](https://github.com/scipopt/PySCIPOpt/blob/4ccafc20bfc510bd07ca307fb780914eb3ebc4c8/src/pyscipopt/scip.pyx#L568).
Indeed, one can create a Solution with `SCIP_SOL == NULL`, but it is not checked in `__repr__` before passing it to `SCIPgetSolVal`.

For `getSolObjVal`, `NULL` is also [not checked](https://github.com/scipopt/PySCIPOpt/blob/4ccafc20bfc510bd07ca307fb780914eb3ebc4c8/src/pyscipopt/scip.pyx#L4143)

## Suggested fix
Either (easy fix): 

```cython
def __repr__(self):
    if self.sol == NULL:
        return "No valid solution"  # Or anything else
   ...
```
```cython
def getSolObjVal(self, Solution sol, original=True):
    if sol == None:
        sol = Solution.create(self._scip, NULL)
    if sol.sol == NULL:
        return None  # Or anything else
   ...
```

Or forbid creating `NULL` `Solution` altogether (always replace with `None`).

## Context
 - Linux
 - Python 3.9.4
 - PySCIPOpt 3.1.2 from conda-forge

**Comment by mattmilten** [comment]
Good catch! I implemented a fix that just returns `None` instead of a Solution when there is no valid `SCIP_SOL*`.

**Comment by AntoinePrv** [comment]
Thanks!

**Comment by mattmilten** [comment]
This is not a valid fix.
A Solution with NULL pointer is used to get the current LP solution from a node. So it's a perfectly fine value for the Solution object.

**Comment by CGraczyk** [comment]
What is the status here?

**Comment by mattmilten** [comment]
This can be closed. The code will raise a warning now when used incorrectly, aka in the wrong state.
