### ISSUE TITLE
How to install the old version?

### ISSUE THREAD

**Issue by huaguifan** [scipopt/PySCIPOpt#500]
I noticed that the function `pyscipopt.scip.Model.getState` in the old version (2.1.5) is now gone.
How can I install this old version? Could anyone help me?

**Comment by XiangyuYang-Opt** [comment]
Hi, I had the same problem, i.e., Model.getState() is unavailable. I would like to know how you solved this problem.

**Comment by mattmilten** [comment]
related issue: #554
