### ISSUE TITLE
scip.h missing - conda install not installing headers

### ISSUE THREAD

**Issue by mdavis-xyz** [scipopt/PySCIPOpt#501]
Hi,

I'm having trouble installing this.

It is not clear from the README whether I am supposed to install SCIP myself first before installing this python library.

Note that @mattmilten 's answer to #54 says:

> Please follow the installation instructions precisely

The instructions say:

> Conda will install SCIP automatically, hence everything can be installed in a single command

Therefore I'm assuming that Conda *should* apt/yum/whatever install the relevant C headers. That's the behavior I'm expecting. i.e. I'm expecting that I don't need to apt/yum install any header files.

# Steps to reproduce

Dockerfile (most of this is just to [install miniconda](https://linuxhandbook.com/dockerize-python-apps/)):

```

FROM python:3.8-slim as conda
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y --no-install-recommends \
    git \
    wget \
    g++ \
    gcc \
    ca-certificates
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN mkdir /root/.conda
RUN bash Miniconda3-latest-Linux-x86_64.sh -b
RUN echo "Running $(conda --version)"
RUN conda init bash 
RUN . /root/.bashrc  #not required?
RUN conda update conda
RUN conda create -n python-app
RUN conda activate python-app
RUN conda install python=3.8 pip

RUN conda install --channel conda-forge pyscipopt
```

Then `docker build .`

# Expected behavior

The build suceeds. pyscipopt is installed with only `conda install pyscipopt`

# actual behavior

```
#11 2.418     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-install-ceqdh537/pyscipopt_896c994a7b164a608642904f2cad78bc/src -I/var/lang/include/python3.8 -c src/pyscipopt/scip.c -o build/temp.linux-x86_64-3.8/src/pyscipopt/scip.o
#11 2.418     src/pyscipopt/scip.c:635:10: fatal error: scip/scip.h: No such file or directory
#11 2.418      #include "scip/scip.h"
#11 2.418               ^~~~~~~~~~~~~
#11 2.418     compilation terminated.
#11 2.418     error: command 'gcc' failed with exit status 1
```

Note that this *does* work if I use a different docker base image such as `continuumio/miniconda3`, instead of installing conda myself inside a python image.

**Comment by chiennifer** [comment]
I get a similar error when trying to conda install pyscipopt

    In file included from src/pyscipopt/scip.c:635:
    In file included from /usr/local/include/scip/scip.h:35:
    /usr/local/include/scip/def.h:43:10: fatal error: 'scip/config.h' file not found
    #include "scip/config.h"
             ^~~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------

**Comment by mattmilten** [comment]
@chiennifer, your issue is not related to this problem. You are using the Makefile system to build and install the SCIP Optimization Suite - this will not work because we need a shared library. Please use CMake to build SCIP.

**Comment by mdavis-xyz** [comment]
Note that the link in `[install.md](https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md) pointing to instructions on CMake is broken.

**Comment by mattmilten** [comment]
Thanks for the heads-up! The links are now fixed.
