### ISSUE TITLE
why does pyscipopt not giving feasible/notfeasible output

### ISSUE THREAD

**Issue by akshatamath** [scipopt/PySCIPOpt#502]
I am doing cost optimization problem, when i add objective function which include cost in it, for some inputs it does'nt give optimal solution, solver keeps on solving that, if i remove cost from objective it optimizes, but our objective is maximize cost.

**Comment by mattmilten** [comment]
This is a very unspecific question. I'd recommend writing out the LP file of your model to verify whether it actually corresponds to the mathematical model you intend to solve.
