### ISSUE TITLE
How to switch the solver to Soplex

### ISSUE THREAD

**Issue by littlebaba** [scipopt/PySCIPOpt#504]
How to switch the solver to Soplex? I can't find useful information, I hope to give some help.

**Comment by mattmilten** [comment]
There is no direct Python interface to SoPlex. It's SCIP's default LP solver, so you will in fact use SoPlex when using PySCIPOpt. Alternatively, you could try using the LP interface of PySCIPOpt. But this is less user-friendly.

https://scipopt.github.io/PySCIPOpt/docs/html/lp_8pxi_source.html#l00003
