### ISSUE TITLE
Convenience functions to add multiple constraints

### ISSUE THREAD

**Issue by steffanschlein** [scipopt/PySCIPOpt#507]
It would be useful to have a function in the `Model` class that allows adding multiple constraints at once using a generator. A possible function could be called `addConss()`. This would allow replacing code like
```python
for i in range(1, n_locations + 1):
    model.addCons(quicksum(x[i, j] for j in range(1, n_locations + 1)) == 1)
```
by
```python
model.addConss([quicksum(x[i, j] for j in range(n_locations)) == 1 for i in range(n_locations)])
```

The new function would use the default parameters of `addCons()` and return a list of added constraints. It would be easy to maintain because it is only a thin wrapper around the existing `addCons()`.

For example, Gurobi features a similar function [addConstrs()](https://www.gurobi.com/documentation/9.1/refman/py_model_addconstrs.html).

If this would fit the design principles of PySCIPOpt, I could create a pull request with my propased extension.

**Comment by mattmilten** [comment]
Sure! That would be a neat feature! The same should then also be applied to `addVar()` if possible.

**Comment by steffanschlein** [comment]
Alright, then I will prepare a patch for it. I will also try to implement `addConss()` such that one can specify the other named parameters of `addCons()`. 

A similiar feature might be more complicated, for example Gurobi implements [sparse indecies](https://www.gurobi.com/documentation/9.1/refman/py_model_addvars.html#pythonmethod:Model.addVars). A separate issue would probably be useful. However, I currently do not have a use-case for adding multiple varibles.
