### ISSUE TITLE
Doxygen didn't document Model.__init__

### ISSUE THREAD

**Issue by dpaleka** [scipopt/PySCIPOpt#512]
For some reason, [the documentation for Model.\_\_init\_\_](https://github.com/scipopt/PySCIPOpt/blob/b904c6315a6b0ba496e24859cc3586c310264003/src/pyscipopt/scip.pyx#L942) is not in Doxygen docs, or at least not in [the place](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html) one would expect it to be.

**Comment by mattmilten** [comment]
Good catch! Most likely, we need to change this line in `docs/doxy`:

```
EXTRACT_ALL  = NO
```

**Comment by CGraczyk** [comment]
I have tried this but the documentation is still not complete.

**Comment by Joao-Dionisio** [comment]
@fschloesser , is this issue still unresolved? I don't think there's anything wrong with the documentation for Model.__init__ as it is now.

**Comment by Joao-Dionisio** [comment]
It's exactly where I would expect it, @fschloesser , I was just making sure that the issue was already solved and so it could be closed :)
