### ISSUE TITLE
best solution is not feasible in original problem

### ISSUE THREAD

**Issue by xtjjyygy** [scipopt/PySCIPOpt#521]
Hello,
I have such a problem and need your help，I found an answer：https://stackoverflow.com/questions/22452332/obtain-best-feasible-solution-with-scip，But I didn't understand how to solve this problem in practice，in especial “but using a lower tolerance like 1e-10 in combination with set emphasis feasibility”

Thank you

**Comment by CGraczyk** [comment]
Hi, thanks for your interest in using PySCIPOpt.
You can have a look at the [documentation](https://scipopt.github.io/PySCIPOpt/docs/html/) to figure out which functions may help with your problem, like setting parameters.

Please provide more info, like a minimal code example and how your own implementation has failed to produce the desired results when using the existing PySCIPOpt functions.

**Comment by xtjjyygy** [comment]
Thank you for your reply. At present, this problem has been solved. This problem is caused by my inaccurate constraint definition. Thank you again
