### ISSUE TITLE
Min/Max operator implementation

### ISSUE THREAD

**Issue by dhzyingz** [scipopt/PySCIPOpt#524]
I want to obtain the Min or Max of a list of decision variables but donno how to do that.

I find a relevant closed [issue ](https://github.com/scipopt/PySCIPOpt/issues/198) but it was for only two variables.

**Comment by CGraczyk** [comment]
Hi, thanks for your interest in using PySCIPOpt.
You can have a look at the [documentation](https://scipopt.github.io/PySCIPOpt/docs/html/) to figure out how the model.getVars() function works as well as which other functions may help with your problem.

Please provide more info, like a code example and how your own implementation has failed to produce the desired result

**Comment by fserra** [comment]
I don't think this is possible. Sometimes one is lucky and can relax a constraint of the form `x = max(y_i)` into `x >= max(y_i)` which can then me linearized to `x >= y_i` for each i.

In general, though, max and min are nonconvex and so no linear representation exists. A formulation using binary variables can be found here https://docs.mosek.com/modeling-cookbook/mio.html#maximum

**Comment by dhzyingz** [comment]
> I don't think this is possible. Sometimes one is lucky and can relax a constraint of the form `x = max(y_i)` into `x >= max(y_i)` which can then be linearized to `x >= y_i` for each i.
> 
> In general, though, max and min are nonconvex and so no linear representation exists. A formulation using binary variables can be found here https://docs.mosek.com/modeling-cookbook/mio.html#maximum

You are right, the reformulation sometimes can achieve my goal.
The link is very useful, thx~

**Comment by CGraczyk** [comment]
I'll assume this closes the Issue for now?
