### ISSUE TITLE
Add CITATION.cff file

### ISSUE THREAD

**Issue by mattmilten** [scipopt/PySCIPOpt#525]
This is a new way of crediting authors and should make it easier to cite a software package.
More info here:
- https://twitter.com/natfriedman/status/1420122675813441540
- https://citation-file-format.github.io/

This also requires updating the current version in the .cff file, so it should better be integrated into some version bump script to craft a release (see [here](https://github.com/citation-file-format/citation-file-format/issues/247))

This would also be a good opportunity to update the list of authors.

What do you think?

**Comment by fserra** [comment]
sounds good!

**Comment by CGraczyk** [comment]
agreed, i don't know how much time i will have to look into this in the next couple weeks though

**Comment by matbesancon** [comment]
alternatively, CITATION.bib is also supported:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files
