### ISSUE TITLE
pip install pyscipopt "fatal error: scip/config.h: No such file or directory"

### ISSUE THREAD

**Issue by wangzhanwei666** [scipopt/PySCIPOpt#526]
already install scipopt-7.0.3, but when install pyscipopt, will output "fatal error: scip/config.h: No such file or directory",I can't find 'config.h' in the install path and source path both. 
Any one meets this problem???

**Comment by wangzhanwei666** [comment]
Don't use "make, make install"
Use "cmake .., make , make install' can solve the problem

**Comment by CGraczyk** [comment]
I assume the issue is thus solved.
