### ISSUE TITLE
How can I get the variable to be branched without executing the branching rule (such as relpscost)?

### ISSUE THREAD

**Issue by linjc16** [scipopt/PySCIPOpt#527]
Hello, I have come across a problem. I want to collect the branching variables using several branching rules (strong branch, relpscost, etc.) for the same node. What should I do? Thanks.

**Comment by CGraczyk** [comment]
Hi,
Are you specifically interested in relpscost? If so, these scores are currently not possible to extract (see [here](https://github.com/ds4dm/ml4co-competition/discussions/54#discussioncomment-1169306)).

Have a look at fork/copy [this](http://listserv.zib.de/pipermail/scip/2012-November/001114.html), to give you an idea how to approach this. Maybe look into the [probing methods](https://www.scipopt.org/doc/html/group__PublicProbingMethods.php) of scip/pyscipopt to manually implement this. 

If you need additional function wrappers in pyscipopt you can implement them yourself following the contribution guidelines and we can work together on these additions in a pull request/branch.
