### ISSUE TITLE
Remove Variable objects from variable data

### ISSUE THREAD

**Issue by schlein** [scipopt/PySCIPOpt#532]
The Python `Variable` objects created by [`Model.addVar()`](https://github.com/scipopt/PySCIPOpt/blob/0485fdb17851749a80ca6254d1e9cc01e44c2c95/src/pyscipopt/scip.pyx#L1415) are stored as user data in the SCIP data structure:
```python
SCIPvarSetData(scip_var, <SCIP_VARDATA*>pyVar)
```
In addition, in the same function the `Model` class implements a mechanism that maps `SCIP_VAR` pointers to the corresponding Python `Variable` objects:
```python
self._modelvars[pyVar.ptr()] = pyVar
```
Currently, the latter mechanism is used for retrieving variables in `Model.getVars()`. The former mechanism is only used in the Benders plugin in [`getPyVar()`](https://github.com/scipopt/PySCIPOpt/blob/0485fdb17851749a80ca6254d1e9cc01e44c2c95/src/pyscipopt/benders.pxi#L67). Having two mechanisms for mapping between Python and C variables seems reduant.

It should be possible to refactor the Benders plugin to access the Python variables through the `Model` reference that is stored in the plugin's wrapper class. There is a comment in the plugin that seems to hint that a refactoring of how variables are passed could be worthwhile. This would free the user data storage for other use-cases.

**Background and motivation:** In my project of extending PySCIPOpt for use with GCG, the occupied variable user data causes a problem. GCG stores information in the variable's data field and expects the content to be a GCG struct.

What are your thoughts on this change? I could provide a PR that refactors the Benders plugin.

**Comment by fserra** [comment]
sounds good to me. @stephenjmaher, what do you think?

**Comment by stephenjmaher** [comment]
That all sounds reasonable to me. Please put together a PR and we can have a look. Your suggestions seems like a good change.

**Comment by Joao-Dionisio** [comment]
Hello @schlein! I am very late to the party, can you tell me what is the status of the PR? Can this issue be closed?

**Comment by Joao-Dionisio** [comment]
No worries! I'll be closing the issue then, to clear the issue page. If someone finds this and can pick it up, please do, and feel free to reopen the issue!
