### ISSUE TITLE
Cannot call Column function in examples/unfinished/cutstock.py

### ISSUE THREAD

**Issue by jp18813100494** [scipopt/PySCIPOpt#533]
![微信图片_20210924105432](https://user-images.githubusercontent.com/26135273/134611154-70249ba7-fca3-427b-b383-828aec00f793.png)
Follow this demo, but I missed the error "NameError: name 'Column' is not defined".
I wanna know how to use this function.  I am in a hurry. May someone can help me?
![微信图片_20210924105816](https://user-images.githubusercontent.com/26135273/134611466-d36742e8-546e-4052-aee8-62ebf1d2c04c.png)

**Comment by fserra** [comment]
that example is in the `unfinished` directory which means that it is not ready to be used. You should look for examples either in `examples/finished` or `tests`
