### ISSUE TITLE
Same code, different outputs in MAC and Windows

### ISSUE THREAD

**Issue by andemart** [scipopt/PySCIPOpt#534]
Hi all, 

I am planning to use PySCIPOpt for my modelling and optimization, however I jsut came across an issue when solving a simple MILNP in my Mac.

It will not get solved, stopping at the iteration 129 with a segmentation error.

L 0.1s|     1 |     0 |   129 |     - |    alns|   0 |  10 |   9 |  42 |  11 | 10 |   0 |   0 | 1.400000e+01 | 2.962742e+01 | 111.62%| unknown
zsh: segmentation fault  /Users/anaconda3/envs/pyopt/bin/python 

However, the same exercise is easily solved in my Windows computer, could you please help me to solve or at least understand what is going on? Same versions of Python 3.9.7 and SCIP (the latest).

I'll cope the code here below:

> from pyscipopt import Model
> 
> 
> model = Model('Testing MILNP')
> 
> 
> x1 = model.addVar (vtype="C", name='x1')
> x2 = model.addVar (vtype="C", name='x2')
> x3 = model.addVar (vtype="I", name='x3')
> x4 = model.addVar (vtype="I", name='x4')
> 
> z = model.addVar ('z')
> model.setObjective (z, sense = 'minimize')
> 
> model.addCons (z == x1 * x4 * (x1+x2+x3) + x3)
> model.addCons (x1*x2*x3*x4 >= 25)
> model.addCons (x1**2 + x2**2 + x3**2 + x4**2 == 40)
> model.addCons (1 <= (x1 <= 5))
> model.addCons (1 <= (x2 <= 5))
> model.addCons (1 <= (x3 <= 5))
> model.addCons (1 <= (x4 <= 5))
> 
> 
> 
> model.optimize()
> sol = model.getBestSol()
> 
> print('x1=', sol[x1])
> print('x2=', sol[x2])
> print('x3=', sol[x3])
> print('x4=', sol[x4])

P.S. I installed Pyscipopt through conda-forge:

conda install --channel conda-forge pyscipopt

**Comment by andemart** [comment]
P.S. I installed Pyscipopt through conda-forge:

conda install --channel conda-forge pyscipopt

**Comment by fschloesser** [comment]
Hey @andemart ,
For reproducibility, can you please print the scip header on both of your setups, just to double check. 
We will look into your problem and come back to you.

**Comment by mattmilten** [comment]
Closed due to inactivity.
