### ISSUE TITLE
How to write quicksum with 3 variables

### ISSUE THREAD

**Issue by alirezanoori1986** [scipopt/PySCIPOpt#541]
I don't know much about mathematics and especially optimization problems. I've been asked to write a python script for the following optimization problem. I'm following several tutorials to do it but still have some issues. For example, I don't know how to write a quicksum with 3 variables. Could you please kindly help me with this?

Here's the problem:

https://imgur.com/a/vUez7yZ

**Comment by mattmilten** [comment]
Hi! You can just chain together several fol loops in python. Quicksum works just like Python's built-in sum. What have you tried so far? Do you get a specific error message?

**Comment by alirezanoori1986** [comment]
Honestly, since I didn't know how it works, I haven't tried anything. Is there some example that I can follow? I usually read the documentation and run a couple of examples then try to implement it on my own.

**Comment by mattmilten** [comment]
Well, there are several examples in the examples directory: https://github.com/scipopt/PySCIPOpt/tree/master/examples%2Ffinished
I suggest to start there for getting an idea of how to formulate your model.

**Comment by alirezanoori1986** [comment]
Thanks again. The examples are great but unless I'm missing them, they don't give the formula that they are converting from. I'm looking for something like this: https://scipbook.readthedocs.io/en/latest/intro.html
Could you please help me convert maybe at least one of the summations?

**Comment by fserra** [comment]
Do you mean a quick sum of a variable with 3 indices?

The example https://scipbook.readthedocs.io/en/latest/intro.html#multi-product-transportation-problem shows how to do it:
```
model.addConstr(quicksum(x[i,j,k] for (i,j2,k) in x if j2 == j) <= M[j], "Capacity[%s]" % j)
```
For SCIP it would be
```
model.addCons(quicksum(...
```

**Comment by alirezanoori1986** [comment]
Awesome. Thank you. I will read the example. Could I ask here if I get stuck? Thanks.

**Comment by fserra** [comment]
It feels to me that your question is not really pyscipopt specific, but rather how to model something, so I guess that this is not the right place to ask these questions... But well, you can probably ask but it might take a while to get an answer. I guess you'll get better/faster help from places like stackexchange or so
