### ISSUE TITLE
Not finding LAPACK

### ISSUE THREAD

**Issue by JPelda** [scipopt/PySCIPOpt#544]
Quadratic constraint handler does not have LAPACK for eigenvalue computation. Will assume that matrices (with size > 2x2) are indefinite.

Installed scip from the zuse-website (SCIPOptSuite-7.0.3-win64-VS15.exe). Scip is in my systempath and via gitBash it works nicely without any LAPACK issue. But within pyscipopt it throws the error of the "Quadratic constraint..." this leads to not solving my problem.

Can anybody help? I tried python 3.8.12 and 3.9 without success. Can it be that the scip version distributed by anaconda is not linked to ipopt and pyscipopt is only looking for that version of scip? How can I change this?

Thank you for helping!

**Comment by JPelda** [comment]
Changed the responsible line 
```
import os
if hasattr(os, 'add_dll_directory'):
    if os.getenv('SCIPOPTDIR'):
        os.add_dll_directory(os.path.join(os.getenv('SCIPOPTDIR').strip('"'), 'bin'))
```

into 
```
if hasattr(os, 'add_dll_directory'):
    if os.getenv('SCIPOPTDIR'):
        os.environ['PATH'] = os.path.join(os.getenv('SCIPOPTDIR').strip('"'), 'bin') + \
                             os.pathsep + os.environ['PATH']
```

Which ensures that the preinstalled scip version is listed before the one that is coming with anaconda install pyscipopt.

**Comment by fschloesser** [comment]
Yes, the scip of the conda package and the one from the scip websites are different, this might very well be. Especially if your solution works, we know that this is what was happening.
I figure you solved the problem yourself, can this issue be closed then?

**Comment by JPelda** [comment]
I think it is worth while to change the first lines in the next release of pyscipopt to make sure an existing scip installation is used for sure.
Thanks!

**Comment by fschloesser** [comment]
I am unsure if this is what is intended or not, but maybe @CGraczyk @fserra @mattmilten @matbesancon have an opinion about that

**Comment by mattmilten** [comment]
Hmm, I am not sure whether we should modify the PATH here. This is mostly a conda issue with the conda installation of SCIP superseding other SCIP installations. I am not sure whether there are any other unintended side-effects.
@JPelda could you please try running a few tests on Windows to verify that this change is indeed working as intended? Then, please submit a pull request with your changes.

**Comment by JPelda** [comment]
I checked out both solutions. With 
`os.add_dll_directory`
it gives 
`Quadratic constraint handler does not have LAPACK for eigenvalue computation. Will assume that matrices (with size > 2x2) are indefinite.`
and leads to a really long runtime (does it ever find a solution?). After a bit of research this error seems to mean something like ipopt is not linked to scip. I think that the anaconda scip does not come with ipopt (why? It should be faster with an ipopt linked).

Using:
`os.environ['PATH'] = os.path.join(os.getenv('SCIPOPTDIR').strip('"'), 'bin') + \
                             os.pathsep + os.environ['PATH']`
Runs like a charm. I unfortunately do not know how to receive the version of SCIP that is taken by PYSCIPOPT. However, as the SCIP.exe that is used by my bash-shell (if I optimize my problems there by reading in the .lp file with scip.exe open) gives solutions in a short time I guess that PYSCIPOPT is using this now, too.

In my opinion the first `os.add_dll_directory` adds the path to SCIP to a list of dll_directories and windwos still takes the first occurence which is from the anaconda scip installation. Whereas `os.environ['PATH'] = ...` sets the pre-installed SCIP version before the anaconda scip  in the list of dlls.

**Comment by mattmilten** [comment]
I don't think we should update the installer's logic here. It might very well be that a conda user explicitly wants to use the bundled SCIPOpt when installing PySCIPOpt.

I guess the best way forward is to just use the PyPI package via `pip install` if you are using an existing SCIPOpt installation.
