### ISSUE TITLE
addVar / delVar / addVar

### ISSUE THREAD

**Issue by anagorko** [scipopt/PySCIPOpt#546]
The following code:

```
model = pyscipopt.Model()
x = model.addVar('x')
model.delVar(x)
y = model.addVar('y')
```
fails with failed assertion in line 1464 in scip.pyx. The line is

```
         assert not pyVar.ptr() in self._modelvars
```

I don't see delVar removing old pointer from self._modelvars, may this be the issue?

**Comment by CGraczyk** [comment]
Hi, thanks for reporting this bug, you are correct that the model kept the stored pointer from the addVar call after deleting the variable. Should be fixed.
