### ISSUE TITLE
getting suboptimal values for a binary integer programming problem

### ISSUE THREAD

**Issue by davidireland3** [scipopt/PySCIPOpt#548]
I have formulated a budgeted variant of max cut as a MIP based on the answer to [this question](https://or.stackexchange.com/a/7274/7471). I was initially using the Python MIP package, but it quickly was unable to solve my problem as the graph sized increased, so I decided to try PySCIPOpt. However, when comparing the solution to one provided by the Python MIP package it has provided a suboptimal answer (I can verify by working out the cut value). I am assuming that I am formulating something wrong in my MIP model but I am unable to tell what. Below is the code I use for the problem: 

```
def max_cut_heuristic(graph, budget):
    N = graph.number_of_nodes()
    model = Model("Max Cut")
    model.setMaximize()
    nodes = [model.addVar(f"{i}", vtype="B") for i in range(N)]  # add a binary decision variable for every node
    edges = {}
    for i, j in graph.edges():
        edges[(i, j)] = model.addVar(f"{(i, j)}", vtype="B")  # add a binary decision variable for every edge
    model.setObjective(quicksum(nodes[i] + nodes[j] - 2 * edges[(i, j)] for i, j in list(graph.edges()))). # define the objective
    for i, j in graph.edges():
        model.addCons(nodes[i] + nodes[j] - 1 <= edges[(i, j)])  # add the linear constraint
    model.addCons(quicksum(nodes[i] for i in range(N)) == budget)  # add the budget constraint
    model.optimize()
    sol = model.getBestSol()
    sol = [i for i in range(N) if sol[nodes[i]] == 1]
    return sol
```

is there something obvious that I am doing wrong here?

e: graph is a `networkx` graph object.

**Comment by Joao-Dionisio** [comment]
Can you please provide a working script with the instances that are suboptimal? 

But looking at the model and the answer to the question, I think you want to maximize the problem, not minimize, right? By default, SCIP tries to minimize the objective function. I suspect something like this is necessary:

```
model.setObjective(quicksum(nodes[i] + nodes[j] - 2 * edges[(i, j)] for i, j in list(graph.edges())), "maximize")
```

At a first glance, that seems to be what is wrong. Please let me know if it works out :)

**Comment by Joao-Dionisio** [comment]
I am closing the issue to clear the Issue page, but please re-open it if this didn't solve your problem!
