### ISSUE TITLE
Can't find "nlpi/pub_expr.h"

### ISSUE THREAD

**Issue by rgreen13** [scipopt/PySCIPOpt#552]
(Also posted at https://github.com/scipopt/PySCIPOpt/issues/552)

Using Debian 11.1 with the SCIPOpt .deb package for version 8.0.0 (which installs and runs with no issue) alongside Python 3.9. I'm running into the following error when installing PySCIPOpt:
```
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/tmp/pip-install-xcm34ryv/pyscipopt_7be7d20bdcc447dcafdaaadb2d1f13a9/src -I/usr/include/python3.9 -c src/pyscipopt/scip.c -o build/temp.linux-x86_64-3.9/src/pyscipopt/scip.o
  src/pyscipopt/scip.c:716:10: fatal error: nlpi/pub_expr.h: No such file or directory
    716 | #include "nlpi/pub_expr.h"
        |          ^~~~~~~~~~~~~~~~~
  compilation terminated.
```
I've searched through source files and there is no `nlpi` directory in the `scip` include directory, but there is a `pub_expr.h` in the main `scip` include directory (`/usr/include/scip`). I have a feeling that the error is related to line 1,457 in `scip.pxd` in the PyScipOpt source code, but am not 100% sure. It seems that it may also be related to a difference between ScipOpt versions 7.0.3 and 8.0.0 and the `nlpi` directory.

**Comment by fschloesser** [comment]
This is probably due to a mismatch between versions of pyscipopt and scip. I expect you used pyscipopt master? Can you try to use the scip-8 branch (that one is still under development though).

**Comment by CGraczyk** [comment]
Hi, did you try installing PySCIPOpt from master perhaps? If you have a look at [this](https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md) the current master is still version 3.x for scip7, have a look at the branch scip-8 for the current WIP for the new release.

**Comment by rgreen13** [comment]
Thank you for the answers! I did not try the scip-8 branch yet (I will), but I've currently done some porting to line up the correct versions of software and all is working!
