### ISSUE TITLE
Regarding scip.Model.getState()

### ISSUE THREAD

**Issue by XiangyuYang-Opt** [scipopt/PySCIPOpt#554]
Dear SCIPers,

What are the alternatives for the function scip.Model.getState()? It seems that .getState() is an old-fashioned usage, and it is not available to see on [Model Class Reference](https://imada.sdu.dk/~marco/DM871/PySCIPOpt/classpyscipopt_1_1scip_1_1Model.html#a3c75554e97728ed380fa47a529b3c617) anymore. Could anyone help with this?

**Comment by mattmilten** [comment]
What is `getState` supposed to do? There is only `getStage()` and `getStatus()` and both are still there...?
