### ISSUE TITLE
How to get current upper/dual bound every fixed seconds?

### ISSUE THREAD

**Issue by Zishanna** [scipopt/PySCIPOpt#555]
Hi,
is there any way to get/print current upper bound and dual bound every fixed seconds, such as 5s, 10s and so on, during a MILP solution process? Thanks in advance.

**Comment by mattmilten** [comment]
Hi @Zishanna,

You might want to check out what we did for [TreeD](https://github.com/mattmilten/TreeD), especially the implementation of the LP event handler that collects data while SCIP solves the instance: https://github.com/mattmilten/TreeD/blob/da23f111379f7e8713bd7aa21750ddbdee1dff87/src/treed/treed.py#L12

Maybe you want to check for other events as well, like BESTSOLFOUND (https://github.com/scipopt/PySCIPOpt/blob/c554bebcf0ced0e23cf46ed02326b89928599242/src/pyscipopt/scip.pxd#L224).

I hope that helps to get you started.

Cheers,
Matthias

**Comment by Zishanna** [comment]
Thank you very much for the quick reply. It inspired me a lot. I will try it in my code.
