### ISSUE TITLE
Somes pages are missed in the online documentation

### ISSUE THREAD

**Issue by JingwangLi** [scipopt/PySCIPOpt#560]
In the section "Building and solving a model", the two links in "There are several **examples** and **tutorials**" are 404, which are
"https://scipopt.github.io/PySCIPOpt/docs/html/examples/finished" and "https://scipopt.github.io/PySCIPOpt/docs/html/examples/tutorial" respectively.

**Comment by JingwangLi** [comment]
I did find some codes in [this page](https://scipopt.github.io/PySCIPOpt/docs/html/dir_d28a4824dc47e487b107a5db32ef43c4.html),  but didn't find accurate definitions of the optimizations problems that the codes correspond to.

**Comment by fschloesser** [comment]
It looks like this has been resolved, the mentioned links on the website work fine.
