### ISSUE TITLE
wrong answer on small 0-1 program

### ISSUE THREAD

**Issue by keithbriggs** [scipopt/PySCIPOpt#563]
The code below gets an optimal objective of -10, at the solution vector of all zeros (which is impossible, as there is no constant term).  The right answer is -10, at x=[0 0 1 0 0 0].   This looks like a bug to me.

```
def foo():
  model=Model()
  x=[model.addVar(f'x_{i}') for i in range(6)]
  for i in range(6): model.addCons(x[i]<=1)
  for i,j,k in [(0,1,3),(0,2,4),(1,2,5)]:
    model.addCons(x[k]<=x[i])
    model.addCons(x[k]<=x[j])
    model.addCons(x[i]+x[j]-x[k]<=1)
  obj=-5*x[0]+9*x[1]-10*x[2]-13*x[3]+17*x[4]-3*x[5]
  model.setObjective(obj)
  model.optimize()
  sol=model.getBestSol()
  val=model.getSolVal(sol,obj)
  sta=model.getStatus()
  x_opt=np.array([int(sol[xi]) for xi in x],dtype=np.int)
  print('foo')
  print(f'  obj={model.getObjective()}')
  print(f'  status={sta}')
  print(f'  objective={int(val)}')
  print(' ',*(xi for xi in x_opt))
```

Output:

> feasible solution found by trivial heuristic after 0.0 seconds, objective value 0.000000e+00
> presolving:
> (round 1, fast)       0 del vars, 6 del conss, 0 add conss, 6 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 0 clqs
>    Deactivated symmetry handling methods, since SCIP was built without symmetry detector (SYM=none).
> presolving (2 rounds: 2 fast, 1 medium, 1 exhaustive):
>  0 deleted vars, 6 deleted constraints, 0 added constraints, 6 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
>  0 implications, 0 cliques
> presolved problem has 6 variables (0 bin, 0 int, 0 impl, 6 cont) and 9 constraints
>       9 constraints of type <linear>
> Presolving Time: 0.00
> transformed 1/1 original solutions to the transformed problem space
> 
>  time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
> t 0.0s|     1 |     0 |     0 |     - | trivial|   0 |   6 |   9 |   0 |   0 |  0 |   0 |   0 |-3.100000e+01 |-5.000000e+00 | 520.00%| unknown
> * 0.0s|     1 |     0 |     5 |     - |    LP  |   0 |   6 |   9 |   9 |   0 |  0 |   0 |   0 |-1.100000e+01 |-1.100000e+01 |   0.00%| unknown
>   0.0s|     1 |     0 |     5 |     - |   600k |   0 |   6 |   9 |   9 |   0 |  0 |   0 |   0 |-1.100000e+01 |-1.100000e+01 |   0.00%| unknown
> 
> SCIP Status        : problem is solved [optimal solution found]
> Solving Time (sec) : 0.00
> Solving Nodes      : 1
> Primal Bound       : -1.10000000000000e+01 (4 solutions)
> Dual Bound         : -1.10000000000000e+01
> Gap                : 0.00 %
> foo
>   obj=Expr({Term(x_0): -5.0, Term(x_1): 9.0, Term(x_2): -10.0, Term(x_3): -13.0, Term(x_4): 17.0, Term(x_5): -3.0})
>   status=optimal
>   objective=-11
>   0 0 0 0 0 0

**Comment by fserra** [comment]
if you do model.printBestSol(True)
you will see that the solution is:
```
objective value:                                  -11
x_0                                               0.5 	(obj:-5)
x_1                                               0.5 	(obj:9)
x_2                                               0.5 	(obj:-10)
x_3                                               0.5 	(obj:-13)
x_4                                                 0 	(obj:17)
x_5                                               0.5 	(obj:-3)
```
I guess you see only 0, because of
```
  x_opt=np.array([int(sol[xi]) for xi in x],dtype=np.int)
```

**Comment by keithbriggs** [comment]
Thanks - I assumed it was doing integer programming by default.   If I use `vtype='I',` it works.

One other thing - I tried `model.setObjIntegral()`, which is in the online docs, but it gives:
`
AttributeError: 'pyscipopt.scip.Model' object has no attribute 'setObjIntegral'`

**Comment by fserra** [comment]
that is strange. I tested it and it works. 

The method was added in August 2020 according to git. Which version of pyscipopt are you using? Can you paste the code where the error happens? Could you also paste the result of model.printVersion() please?

**Comment by keithbriggs** [comment]
I if just do:

```
  model=Model()
  model.setObjIntegral()
```

then I get the error.  The `model.printVersion()` command gives: 

```
SCIP version 7.0.1 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: SoPlex 5.0.1] [GitHash: b41d526acf]
Copyright (C) 2002-2020 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)
```
`pyscipopt.__version__ `gives 3.0.1. 

Also, I tried a pip upgrade but it crashes.   You don't seem to give pip install instructions in the README.md.   Is a pip install supposed to include everything, or does SCIP have to to be separately installed?

```
kbriggs> pip install pyscipopt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyscipopt in /usr/local/lib/python3.6/dist-packages (3.0.1)

kbriggs> pip install --upgrade pyscipopt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyscipopt in /usr/local/lib/python3.6/dist-packages (3.0.1)
Collecting pyscipopt
  Using cached PySCIPOpt-4.0.0.tar.gz (633 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: wheel in /usr/local/lib/python3.6/dist-packages (from pyscipopt) (0.36.2)
Building wheels for collected packages: pyscipopt
  Building wheel for pyscipopt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oorjiqu5/pyscipopt_7e8dad27ec6c45928324c9efd0f88cc0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oorjiqu5/pyscipopt_7e8dad27ec6c45928324c9efd0f88cc0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-o1m2p0bn
       cwd: /tmp/pip-install-oorjiqu5/pyscipopt_7e8dad27ec6c45928324c9efd0f88cc0/
```
(lots more errors.)

**Comment by fserra** [comment]
I am not sure what the current status is. Maybe @CGraczyk can help you with the upgrade.

**Comment by fserra** [comment]
Ah I see that he is already taking care of #564. I guess we can close this issue then.
