### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by keithbriggs** [scipopt/PySCIPOpt#564]
I upgraded my scip to 8.0.0.  It installed without errors and all checks passed.

I then did `python3 -m pip install --upgrade pyscipopt`, and it reported a successful install of 4.0.0.   But now I get:

```
kbriggs> python3
Python 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyscipopt import Model
Segmentation fault (core dumped)
```

This is all on Ubuntu 18.   The previous version worked - now I can't do anything!

**Comment by CGraczyk** [comment]
have you tried a fresh install for pyscipopt following the [Install.MD](https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md) ?

**Comment by keithbriggs** [comment]
Yes, I have been trying that.   I get lots of errors like this.   I seems to be finding the wrong header files.  It says "Using include path </home/kbriggs/Downloads/scipoptsuite-8.0.0/include>", but actually that doesn't exist.  So it uses /usr/local/include/ which is probably an old version.   How do I get it to find the right headers?

```
kbriggs@Dell:~/Downloads/PySCIPOpt-master> export SCIPOPTDIR=/home/kbriggs/Downloads/scipoptsuite-8.0.0/
kbriggs@Dell:~/Downloads/PySCIPOpt-master> python3 setup.py build
Using include path </home/kbriggs/Downloads/scipoptsuite-8.0.0/include>.
Using SCIP library <scip> at </home/kbriggs/Downloads/scipoptsuite-8.0.0/lib>.
running build
running build_py
running build_ext
building 'pyscipopt.scip' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/kbriggs/Downloads/scipoptsuite-8.0.0/include -I/usr/include/python3.6m -c src/pyscipopt/scip.c -o build/temp.linux-x86_64-3.6/src/pyscipopt/scip.o
In file included from /usr/local/include/nlpi/pub_expr.h:31:0,
                 from src/pyscipopt/scip.c:645:
/usr/local/include/nlpi/type_expr.h:85:4: error: redeclaration of enumerator ‘SCIP_EXPRCURV_UNKNOWN’
    SCIP_EXPRCURV_UNKNOWN    = 0,             /**< unknown curvature (or indefinite) */
    ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/scip/scip.h:57:0,
                 from src/pyscipopt/scip.c:633:

```

**Comment by keithbriggs** [comment]
By deleting /usr/local/include/nlpi/, I get this:

```
kbriggs@Dell:~/Downloads/PySCIPOpt-master> export SCIPOPTDIR=/home/kbriggs/Downloads/scipoptsuite-8.0.0/
kbriggs@Dell:~/Downloads/PySCIPOpt-master> python3 setup.py build
Using include path </home/kbriggs/Downloads/scipoptsuite-8.0.0/include>.
Using SCIP library <scip> at </home/kbriggs/Downloads/scipoptsuite-8.0.0/lib>.
running build
running build_py
running build_ext
building 'pyscipopt.scip' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/kbriggs/Downloads/scipoptsuite-8.0.0/include -I/usr/include/python3.6m -c src/pyscipopt/scip.c -o build/temp.linux-x86_64-3.6/src/pyscipopt/scip.o
src/pyscipopt/scip.c:645:10: fatal error: nlpi/pub_expr.h: No such file or directory
 #include "nlpi/pub_expr.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by CGraczyk** [comment]
Can you try to get rid of the whole global install first ? The compiler uses the global path by default it seems.

**Comment by keithbriggs** [comment]
What is included in the whole global install? I probably did a "make install" with the previous version, and there is no "make uninstall".

Another thing, INSTALL.md says:
```

`SCIPOPTDIR` needs to have a subdirectory `lib` that contains the
library, e.g. `libscip.so` (for Linux) and a subdirectory `include` that
contains the corresponding header files:

    SCIPOPTDIR
      > lib
        > libscip.so ...
      > include
        > scip
        > lpi
        > nlpi
        > ...
```

but with scipoptsuite-8.0.0 and a cmake build, you don't get that structure.   The only include and lib folders are like this:

```
kbriggs@Dell:~/Downloads/scipoptsuite-8.0.0> find . -name include
./scip/lib/include
./scip/src/amplmp/include
./scip/tests/include
kbriggs@Dell:~/Downloads/scipoptsuite-8.0.0> find . -name lib
./build/scip/src/CMakeFiles/Export/lib
./build/soplex/src/CMakeFiles/Export/lib
./build/lib
./scip/obj/shared/O.linux.x86_64.gnu.opt/lib
./scip/obj/static/O.linux.x86_64.gnu.opt/lib
./scip/lib
./soplex/obj/O.linux.x86_64.gnu.opt/lib
./soplex/lib
./ug/lib
./lib
./zimpl/lib
```

**Comment by keithbriggs** [comment]
Also, `src/pyscipopt/scip.c` has:

`#include "nlpi/pub_expr.h"`

but this file does not exist in the scipoptsuite-8.0.0 distribution.  It is actually in 

`scip/src/scip/pub_expr.h`

**Comment by keithbriggs** [comment]
Sorry - I think I was accidentally not using the latest pyscipopt version.  I wiped everything and did this:

1. built cmake build of scipoptsuite-8.0.0.   Built with no problems, did "make install".
2. In PySCIPOpt-master, I did "python3 setup.py install".  No problems reported, all header files and libs now found and successful install reported.
3. But then I still get:

```
kbriggs@Dell:~/python> python3 
Python 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyscipopt import Model
Segmentation fault (core dumped)
```

**Comment by CGraczyk** [comment]
So i guess the install works at least - are you sure you are using the correct python environment? are you using a virtual env as recommended in the install.md?

**Comment by keithbriggs** [comment]
No, I've never been able to understand venvs.   The problems I have been reporting were all under Ubuntu 18.   I went to a new Ubuntu 20 machine, which had no old versions of scip or pyscipopt installed, and this worked:

1. build scip-8.0.0 with cmake, but don't do "make install".
2. `unzip pyscipopt-master.zip; cd pyscipopt-master; python3 setup.py build; pip install .`

This actually works (I can now `import pyscipopt`), but why?   How does the `setup.py build` know where to find the header files, when I never set the SCIPOPTDIR env variable?

**Comment by CGraczyk** [comment]
I think you should just setup the venv as described in the install.md under building everything from source, it should reduce the possible errors you are encountering.

**Comment by keithbriggs** [comment]
Thanks, I'll try venv a bit later, but meanwhile I'm happy with the procedure I mentioned.
