### ISSUE TITLE
Conda install command fails in base environment

### ISSUE THREAD

**Issue by RicardoEuler** [scipopt/PySCIPOpt#567]
I've encountered an issue with the conda install command.
When using  `conda install --channel conda-forge pyscipopt`
in the `base` environment of a fresh anaconda installation (4.11.0) the solving environment stage takes forever.
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ failed
CondaError: KeyboardInterrupt
```
The above output was cancelled after ~20min but I've had it previously running for hours without success.
Installing in a new environment resolves the issue and produces a working installation of `pyscipopt`. I'm currently on Ubuntu 20.04 LTS but I was able to reproduce the issue on a Win10 system, too. Installing other packages (`matplotlib`,`gurobi`) in `base` works fine.

**Comment by mattmilten** [comment]
Hmm, to me it's pretty unclear why another clean env would work when the `base` env does not. Still, it is considered best practice to use dedicated environments anyway and just ignore the `base` env.

IMO, this looks like an Anaconda issue. I don't know whether anyone else is going to investigate further - please feel free to close this issue yourself if you can live with your workaround.
