### ISSUE TITLE
cannot open shared object file

### ISSUE THREAD

**Issue by keithbriggs** [scipopt/PySCIPOpt#571]
Two issues: first, the docs say that SCIPOPTDIR must point to a directory with this structure:

```
SCIPOPTDIR
  > lib
    > libscip.so ...
  > include
    > scip
    > lpi
    > nlpi
    > ...
```

However, scip-8.0.0 has nothing like this.   The only folders called `include` are:
```

scipoptsuite-8.0.0/scip/src/amplmp/include
scipoptsuite-8.0.0/scip/tests/include
```

So how is this supposed to work?  Second, despite this, when I set 

`export SCIPOPTDIR=/home/kbriggs/Downloads/scipoptsuite-8.0.0/scip/`

everything builds and installs correctly, but I still cannot import:

```
kbriggs@Z230-work:~/Downloads/PySCIPOpt-master> python3 setup.py build
...

kbriggs@Z230-work:~/Downloads/PySCIPOpt-master> python3 -m pip install  .
Processing /home/kbriggs/Downloads/PySCIPOpt-master
Collecting wheel (from PySCIPOpt==4.1.0)
  Using cached https://files.pythonhosted.org/packages/27/d6/003e593296a85fd6ed616ed962795b2f87709c3eee2bca4f6d0fe55c6d00/wheel-0.37.1-py2.py3-none-any.whl
Building wheels for collected packages: PySCIPOpt
  Running setup.py bdist_wheel for PySCIPOpt ... done
  Stored in directory: /home/kbriggs/.cache/pip/wheels/72/bc/7f/dc5033c1d6634cf37e8df4fc89f95919a978a3040b0e48fcac
Successfully built PySCIPOpt
Installing collected packages: wheel, PySCIPOpt
Successfully installed PySCIPOpt-4.1.0 wheel-0.37.1

kbriggs@Z230-work:~/Downloads/PySCIPOpt-master> python3
Python 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyscipopt import Model,scip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kbriggs/.local/lib/python3.6/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: libscip.so.8.0: cannot open shared object file: No such file or directory
```

What's going on here?

**Comment by mattmilten** [comment]
Hi Keith,

As the [INSTALL.md](https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md) file specifies:

> PySCIPOpt requires a working installation of the SCIP Optimization Suite. Please, make sure that your SCIP installation works!

Apparently, you just downloaded the source tarball of the SCIPOptSuite without compiling and installing it. This installation step will create the mentioned directory structure with the `lib` and `include` directories.

This is also the reason why your PySCIPOpt installation fails with an error message about a missing `libscip.so` - this library is not there because you did not compile and install SCIP (and the SCIPOptSuite).

The `SCIPOPTDIR` environment variable then has to point to this installation directory so the PySCIPOpt installer can find the necessary libs and header files.

It is strongly recommended to use the pre-built installer packages for the SCIPOptSuite but if you want to compile the code yourself, please use the CMake build system.

I hope that makes sense and answers your questions.

Cheers,
Matthias

**Comment by keithbriggs** [comment]
Mathias: thanks, but I did compile and install it. I was repeating the procedure which worked perfectly for me last week on another machine. Both machines are Ubuntu 20 and should be identical. That's why I can't figure it out.

**Comment by mattmilten** [comment]
If you install the SCIPOptSuite (*not* PYSCIPOpt), there will be no `scip` subdirectory like in your `SCIPOPTDIR` definition - so you obviously did not install it. That's also why the env variable is called `SCIPOPTDIR` and not `SCIPDIR` or something like that.

If all else fails, just use the conda installer - this includes everything in one package.

**Comment by keithbriggs** [comment]
I tried conda, but it messes around with my shell in a way I don't like.

Since my SCIP is installed, this should work:

`export SCIPOPTDIR=/usr/local/`

It does contain the required directories as at the top of this issue page.  However, I got:

```
kbriggs@Z230-work:~/Downloads/PySCIPOpt-master> python3 setup.py build
SCIPOPTDIR=/usr/local/ does not contain a src/scip directory.
```

This shows that the logic in setup.py is faulty.  I had a /usr/local/src/ directory, but it was empty.  After deleting it, everything at last runs without error:
```

kbriggs@Z230-work:~/Downloads/PySCIPOpt-master> python3 setup.py build
Using include path /usr/local/include.
Using SCIP library scip at /usr/local/lib.

running build
running build_py
running build_ext
kbriggs@Z230-work:~/Downloads/PySCIPOpt-master> pip install .
Processing /home/kbriggs/Downloads/PySCIPOpt-master
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (from PySCIPOpt==4.1.0) (0.34.2)
Building wheels for collected packages: PySCIPOpt
  Building wheel for PySCIPOpt (setup.py) ... done
  Created wheel for PySCIPOpt: filename=PySCIPOpt-4.1.0-cp38-cp38-linux_x86_64.whl size=4717020 sha256=56228dc42c3241b3dc7e4002f9e5b84dd3998a4e195c9231b3cf2864a838eccb
  Stored in directory: /home/kbriggs/.cache/pip/wheels/f7/21/ec/dcc0a979e7f23fdaf440480a2b70a68eae8b49145521bc918f
Successfully built PySCIPOpt
Installing collected packages: PySCIPOpt
  Attempting uninstall: PySCIPOpt
    Found existing installation: PySCIPOpt 4.1.0
    Uninstalling PySCIPOpt-4.1.0:
      Successfully uninstalled PySCIPOpt-4.1.0
Successfully installed PySCIPOpt-4.1.0
```

**Comment by mattmilten** [comment]
Indeed, `setup.py` tried to guess the installation method and this failed in your case because of the `src` directory in `/usr/local`. My suggested pull request is going to fix this by requiring the user to specify a non-standard SCIP installation.

**Comment by keithbriggs** [comment]
Yes, I'm not sure why setup.py looks for src/, because I think it only uses include/ and lib/.    I think the checking could easily be made much smarter.   Why doesn't it explicitly check that the header files and libraries are in the specified path?

**Comment by mattmilten** [comment]
This issue should be solved now by reordering the path detection logic.
