### ISSUE TITLE
Georgia Tech ISyE Senior Design Group - Installation problems using conda and pip install

### ISSUE THREAD

**Issue by anthonyyu123** [scipopt/PySCIPOpt#572]
[PySCIPOpt_Installation_Issues.docx](https://github.com/scipopt/PySCIPOpt/files/8219000/PySCIPOpt_Installation_Issues.docx)
Included above is a doc detailing our errors with trying to install PySCIPOpt on a Mac using Conda install with screenshots of the initial code and the errors given.

**Comment by mattmilten** [comment]
Wow. Please don't submit error reports via MS Word documents. You can just as easily copy and paste the error messages directly into the issue description.

I am closing this issue. Please just open a new one, describing the error in the issue description - thanks!
