### ISSUE TITLE
GaTech Senior Design Error with Conda install 

### ISSUE THREAD

**Issue by anthonyyu123** [scipopt/PySCIPOpt#574]
Apologies about the previous error. We have moved on from trying to install PySCIPOpt to use dockers instead, we just wanted to let you know of the error just in case. 

Here are the error when trying to use conda install on a Mac: 
**(base) lawn-128-61-24-75:~ josephlee$ conda install -c conda-forge pyscipopt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | failed with initial frozen solve. Retrying with flexible solve.**

We tried with slightly different code:
**(base) lawn-128-61-24-75:~ josephlee$ conda install --channel conda-forge pyscipopt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ failed with repodata from current_repodata.json, will retry with next repodata source.**

**Comment by mattmilten** [comment]
No worries! It's just very unusual to do it this way and requires everyone to open another file.

Are you using the M1 chip?
Can you try whether the solution from #567 also works in your case? (Just create a new conda env and install the package there instead of in the `base` env)

**Comment by mattmilten** [comment]
@anthonyyu123 did the suggested workaround resolve your issue?

**Comment by Joao-Dionisio** [comment]
Can we close this issue, @mattmilten ? It has been inactive for a while, and I'm fairly certain your suggestion fixes the problem.

**Comment by mattmilten** [comment]
Sure! I don't expect any updates here.
