### ISSUE TITLE
Cryptic error message

### ISSUE THREAD

**Issue by keithbriggs** [scipopt/PySCIPOpt#576]
scip.pyx has:

` raise Warning(f"{method} cannot only be called in stage SOLVING without a valid solution (current stage: {SCIPgetStage(self.scip)})")`

I don't understand the grammar here - it makes no sense.  Is one of these the intended meaning:

` raise Warning(f"{method} cannot be called in stage SOLVING except with a valid solution (current stage: {SCIPgetStage(self.scip)})")`

or:

` raise Warning(f"{method} can only be called in stage SOLVING without a valid solution (current stage: {SCIPgetStage(self.scip)})")`

?   Or maybe something else?

**Comment by fserra** [comment]
it should be `can only be called with a valid solution`

**Comment by mattmilten** [comment]
Thanks for bringing this up, @keithbriggs!

**Comment by keithbriggs** [comment]
Thanks for the fix - it now makes sense. However, my original problem remains - when using this as a solver from cvxpy, I get this message repeatedly even though the solution is correct. So is the message being triggered by the right condition? I will post a minimal example next week.
