### ISSUE TITLE
Installing PySCIPOpt

### ISSUE THREAD

**Issue by Ishaanjolly** [scipopt/PySCIPOpt#577]
Hi, apologise for the bother on the installation process. I understand that there has have already been a huge amount of issues that have been resolved. 

On downloading scip-8.0.0 from the official website, and following the commands listed here: https://github.com/scipopt/scip/blob/master/INSTALL.md. I get a weird error: 

``
-- Build shared libraries: ON
-- Build type: Release
-- Finding ZLIB
-- Finding ZLIB - found
-- Finding Readline
-- Finding Readline - found
-- Finding GMP
-- Finding GMP - found
-- Finding PAPILO
CMake Error at CMakeLists.txt:298 (find_package):
  Could not find a package configuration file provided by "PAPILO" with any
  of the following names:

    PAPILOConfig.cmake
    papilo-config.cmake

  Add the installation prefix of "PAPILO" to CMAKE_PREFIX_PATH or set
  "PAPILO_DIR" to a directory containing one of the above files.  If "PAPILO"
  provides a separate development package or SDK, be sure it has been
  installed.
-- Configuring incomplete, errors occurred!

```

I was wondering if you could please help me resolve this?

**Comment by mattmilten** [comment]
Hi @Ishaanjolly, could you please close this request and open a new one in the SCIP project https://github.com/scipopt/scip/issues?

**Comment by Ishaanjolly** [comment]
Indeed, will do it just now. Thanks, Matthias.
