### ISSUE TITLE
Wrapping getVanillafullstrongData() in pyscipopt

### ISSUE THREAD

**Issue by kothariharshit** [scipopt/PySCIPOpt#578]
I tried to wrap [getVanillafullstrongData()](https://www.scipopt.org/doc/html/branch__vanillafullstrong_8c.php#a2548062bc0760f6f06259400768ca735) in python, but I think I made some mistake. Can you please add this functionality or guide me on how to wrap this function. Thanks!

**Comment by CGraczyk** [comment]
This is not a public function in scip (missing the SCIP_EXPORT preamble) and is only available internally and cannot be accessed through the interface.

**Comment by fserra** [comment]
the scip I have says:

```
/** recovers candidate variables and their scores from last vanilla full strong branching call */
SCIP_EXPORT
SCIP_RETCODE SCIPgetVanillafullstrongData(
   SCIP*                 scip,               /**< SCIP data structure */
   SCIP_VAR***           cands,              /**< pointer to store candidate variables; or NULL */
   SCIP_Real**           candscores,         /**< pointer to store candidate scores; or NULL */
   int*                  ncands,             /**< pointer to store number of candidates; or NULL */
   int*                  npriocands,         /**< pointer to store number of priority candidates; or NULL */
   int*                  bestcand            /**< pointer to store best branching candidate; or NULL */
   );
```

**Comment by CGraczyk** [comment]
You are right, i just followed the linked function of his comment and it links to the non public one!

@kothariharshit so the usual process for wrapping is that you need to add the functioncall into the .pxd file and then implement the python version calling this function in the .pxy file - can you show me what you have tried to add this function to your pyscipopt?

**Comment by kothariharshit** [comment]
Thank you for your reply.
I added this to scip.pxd - 
`cdef extern from "scip/branch_vanillafullstrong.h":
    SCIP_RETCODE SCIPincludeBranchruleVanillafullstrong(SCIP* scip)
    SCIP_RETCODE SCIPgetVanillafullstrongData(SCIP* scip,
                                              SCIP_VAR*** cands,
                                              SCIP_Real** candscores,
                                              int* ncands,
                                              int* npriocands,
                                              int* bestcand)
`
And added this to scip.pyx - 
`    def getVanillafullstrongData(self):
        cdef SCIP_VAR** cands
        cdef SCIP_Real* candscores
        cdef int        ncands
        cdef int        npriocands
        cdef int        bestcand

        return SCIPgetVanillafullstrongData(self._scip, &cands, &candscores, &ncands, &npriocands, &bestcand)`

Does this look correct?

**Comment by kothariharshit** [comment]
Thank you for your reply.
I added this to scip.pxd - 
```cdef extern from "scip/branch_vanillafullstrong.h":
    SCIP_RETCODE SCIPincludeBranchruleVanillafullstrong(SCIP* scip)
    SCIP_RETCODE SCIPgetVanillafullstrongData(SCIP* scip,
                                              SCIP_VAR*** cands,
                                              SCIP_Real** candscores,
                                              int* ncands,
                                              int* npriocands,
                                              int* bestcand)
```
And added this to scip.pyx - 
``` 
def getVanillafullstrongData(self):
        cdef SCIP_VAR** cands
        cdef SCIP_Real* candscores
        cdef int        ncands
        cdef int        npriocands
        cdef int        bestcand

        return SCIPgetVanillafullstrongData(self._scip, &cands, &candscores, &ncands, &npriocands, &bestcand)
```
Does this look correct?

**Comment by CGraczyk** [comment]
Well what does your compiler say? can you post the error when recompiling pyscipopt? have a look at [README](https://github.com/scipopt/PySCIPOpt/blob/master/README.md) section "extending the interface" and [contribution guidelines](https://github.com/scipopt/PySCIPOpt/blob/master/CONTRIBUTING.md).

The issue you quote in your edit concludes with a working wrapper for this function. So if it does not you need to provide the compiler error you have encountered.

**Comment by fserra** [comment]
just like with the issue you mentioned you should probably open a pull request and see what the CI says about this.

Just from a quick look, I would say the `scip_result` variable is not needed... there is no `scip_result` argument to the function.

also you should probably initialize `candscores` to NULL

**Comment by kothariharshit** [comment]
Thank you for your reply.
I figured out that the issue was not in the wrapper code, but in my understanding of the function definition. I forgot to call strong branching and hence the candidates were None. Thank you for the help!
On a sidenote, is it possible to get pseudo costs once the branch and bound process is over?
