### ISSUE TITLE
.getObj() vs. .getLPSol()

### ISSUE THREAD

**Issue by rgreen13** [scipopt/PySCIPOpt#582]
I want to get the value of a variable directly from the variable object. It is not 100% clear to me what the difference is between the methods .getObj() and .getLPSol(). Could some clarity be provided?

**Comment by mattmilten** [comment]
The objective value of a variable corresponds to the current integer feasible solution. The LP solution value on the other hand, refers to just the current value of the linear relaxation of the original problem.

In case, you are just solving an LP in the first place, there should not be a difference in those values. Typically, though, PySCIPOpt is used to solve mixed-integer or even nonlinear mixed-integer programming problems (MIPs, MILPs, MINLPs).
