### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by josephslee30** [scipopt/PySCIPOpt#584]
I have downloaded the SCIP Optimization Suite, "SCIPOptSuite-8.0.0-Darwin-Ipopt-gcc7.sh", after running "brew install gcc@7 tbb" in terminal. I then went to https://imada.sdu.dk/~marco/Misc/PySCIPOpt/md_INSTALL.html and followed the instructions listed. I specified the install location using the environment variable SCIPOPTDIR using: 
"export SCIPOPTDIR=/Users/josephlee/Desktop/Spring_2022/HoneywellData/SCIPOptSuite-8.0.0-Darwin" 
in terminal. I then used "pip install pyscipopt" in terminal and was returned:
"Collecting pyscipopt
  Using cached PySCIPOpt-4.2.0.tar.gz (661 kB)
Requirement already satisfied: wheel in /Users/josephlee/opt/anaconda3/lib/python3.8/site-packages (from pyscipopt) (0.34.2)
Building wheels for collected packages: pyscipopt
  Building wheel for pyscipopt (setup.py) ... done
  Created wheel for pyscipopt: filename=PySCIPOpt-4.2.0-cp38-cp38-macosx_10_9_x86_64.whl size=846541 sha256=308c77cf3a600be207a15aeddb377a3b1517ee8e254d9f3b21a2e01dcabf9a48
  Stored in directory: /Users/josephlee/Library/Caches/pip/wheels/d5/35/de/dbf309cec0b3e19be218a04e8dba00eb2cad813082638f17ec
Successfully built pyscipopt
Installing collected packages: pyscipopt
Successfully installed pyscipopt-4.2.0"
However, when I tried importing pyscipopt in python using: "from pyscipopt import Model, quicksum",
it returned the following error.
"Traceback (most recent call last):
  File "Demo_LP_Code.py", line 4, in <module>
    from pyscipopt import Model, quicksum
  File "/Users/josephlee/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: dlopen(/Users/josephlee/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so, 2): Library not loaded: libscip.8.0.dylib
  Referenced from: /Users/josephlee/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so
  Reason: image not found"
I also tried importing it using: "from pyscipopt.scip import Model, quicksum",
and it returned the same error.
"Traceback (most recent call last):
  File "Demo_LP_Code.py", line 4, in <module>
    from pyscipopt.scip import Model, quicksum
  File "/Users/josephlee/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: dlopen(/Users/josephlee/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so, 2): Library not loaded: libscip.8.0.dylib
  Referenced from: /Users/josephlee/opt/anaconda3/lib/python3.8/site-packages/pyscipopt/scip.cpython-38-darwin.so
  Reason: image not found"

Is there something I did wrong that might've caused this error?

**Comment by mattmilten** [comment]
Can you please check whether this fixes your issue: https://github.com/scipopt/PySCIPOpt/issues/469#issuecomment-753323508

**Comment by CGraczyk** [comment]
Since there has been no follow-up i assume this was resolved by the user.
