### ISSUE TITLE
Solution of Benders Master Problem is "None" When trying to implement a customized benders cut

### ISSUE THREAD

**Issue by KAI10** [scipopt/PySCIPOpt#586]
I am trying to implement a customized benders cut following  `test_customizedbenders.py`. The issue i am facing right now is, at the very first execution of `benderssolvesubconvex` function, I am getting  `None` as the solution of the master problem (specifically [here](https://github.com/scipopt/PySCIPOpt/blob/master/tests/test_customizedbenders.py#L55), the `solution` variable is found to be `None`). However, I know that my master problem is feasible as I have tried solving it separately and I do get feasible solutions.

When is the solution of the master problem returned as `None` and how should it be handled within a customized benders cut?

Thanks in advance!

**Comment by Joao-Dionisio** [comment]
Hello, @KAI10! Sorry for the very large delay in an answer. Is this still an issue you're having? If so, can you please provide your code so that I can try to figure out what's wrong?

**Comment by Joao-Dionisio** [comment]
I'm sorry for taking so long to look at this @KAI10. I will close the issue to clear out the issues page, but if you are still having problems, feel free to reopen it, or open a new issue!
