### ISSUE TITLE
Installation from PyPi Failed

### ISSUE THREAD

**Issue by saulspatz** [scipopt/PySCIPOpt#596]
On xubuntu 20.04 with python 3.10, I did

export SCIPOPTDIR=~/Projects/SCIOptSuite/
python -m pip install pyscipopt

and got the error

src/pyscipopt/scip.c:31:10: fatal error: Python.h: No such file or directory
         31 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

Please advise.

**Comment by CGraczyk** [comment]
Hi, have you installed in a clean virtual environment? - where did you get the error?
