### ISSUE TITLE
Solving terminates on missing incumbent

### ISSUE THREAD

**Issue by stefanvanberkum** [scipopt/PySCIPOpt#600]
Hi all,

I just noticed that during solving, calling ```getCutLPSolCutoffDistance(cut, model.getBestSol())``` causes the solving to exit silently (i.e., terminate without any warning or error), if no incumbent exists (```model.getNSols() = 0```). In this case, no solution is returned, and no error is thrown as well. I think throwing an error would be a good feature to avoid any confusion, so I figured I'd let you know! I am running PySCIPOpt 4.2.0 (installed via Conda as recommended) with Python 3.9.

**Comment by Joao-Dionisio** [comment]
This issue is older, but I think it makes sense to redirect it to Issue #610 about generic PySCIPOpt error handling.

Thank you very much for the heads-up!
