### ISSUE TITLE
how to add a variable with serveral possible values?

### ISSUE THREAD

**Issue by xiaolongwang2015** [scipopt/PySCIPOpt#601]
Hi all,

how can I add a variable with serveral possible values? like x equals to one of (1,50,112,193)? 

Thank you!

**Comment by fserra** [comment]
I don't think you can specify such a domain when defining a variable and need to enforce it through constraints. maybe something like `x = y1 + 50 y2 + 112 y3 + 193y4` where each `y` is binary and also the constraint `y1 + y2 +y3 +y4 =1`

**Comment by xiaolongwang2015** [comment]
@fserra Thank you so much!
