### ISSUE TITLE
Question: Implement Constraint Handler properly

### ISSUE THREAD

**Issue by SanielDous** [scipopt/PySCIPOpt#605]
I am trying to implement a Branch-and-Price algorithm. Pricing new variables already works fine but I have some issues when it comes to branching. I already came up with a branching rule that adds new constraints to the child nodes and thereby ensures integrality without branching on the variables. My problem is now to actually add these constraints in the implementation:

This is probably the 1000th time this question is asked and there are some useful hints [here](https://github.com/scipopt/PySCIPOpt/issues/395) and [here](https://github.com/scipopt/PySCIPOpt/blob/use-probdata-to-store-model/tests/test_coloring.py) but I still don't understand how to properly implement a branching rule that adds constraints to the child nodes like:

    quicksum(var[i] for i in X) <= C

for one child node and

    quicksum(var[i] for i in X) >= C + 1

for the other child node. (So, really simple constraints)
[This](https://github.com/scipopt/PySCIPOpt/pull/418) PR tried to make life easier by allowing to use this for example:

    self.model.addConsNode(child1, quicksum(var[i] for i in X) >= C + 1)

I don't know if these changes already found its way into master but I still get the following error:

    TypeError: Argument 'cons' has incorrect type (expected pyscipopt.scip.Constraint, got pyscipopt.scip.ExprCons)

So, I understood I have to use a Constraint Handler to add the new constraints. I tried to understand the examples from [this](https://github.com/scipopt/PySCIPOpt/issues/395) issue but I don't get it where the constraints are actually added. In other words where to put the Expression from above. The function `self.model.createCons(self, name, ...)` does not get such an expression. How does the node's model know the new row?

Probably the solution is completely obvious and I just don't see it. Nevertheless, I would appreciate your tips and hints.

**Comment by Joao-Dionisio** [comment]
Hello, @SanielDous! Sorry for leaving you hanging for so long, your problem seemed out of my league, but now I think I may help a bit.

Are you still having problems? What's the status of this?

**Comment by SanielDous** [comment]
Hi, thank you for your response but I'm not working on the corresponding project anymore.

**Comment by Joao-Dionisio** [comment]
I am very sorry for not helping when it was needed. I'm closing the issue then, but if you or anyone else is having similar problems, feel free to reopen the issue.
