### ISSUE TITLE
Model instance creation causes "SCIP: unspecified error!" for SCIP 8.0.1 built with -DTPI=tny cmake option

### ISSUE THREAD

**Issue by vvvol** [scipopt/PySCIPOpt#608]
Our team successfully used PySCIPOpt 4.2.0 with **SCIP 8.0.0** (Linux Ubuntu 20.04, Python 3.8.10).

But when we had built **SCIP 8.0.1** and then recompiled PySCIPOpt for this new version all our scripts begin crash on model creation !?
For example the operator
**m = pyscipopt.scip.Model()** 
causes the following message
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
src/pyscipopt/scip.pyx in pyscipopt.scip.PY_SCIP_CALL()
Exception: SCIP: method cannot be called at this time in solution process!
Exception ignored in: 'pyscipopt.scip.Model.__dealloc__'
Traceback (most recent call last):
  File "src/pyscipopt/scip.pyx", line 252, in pyscipopt.scip.PY_SCIP_CALL
Exception: SCIP: method cannot be called at this time in solution process!
---------------------------------------------------------------------------
```
Why __dealloc__ is called ?!

**Comment by vvvol** [comment]
**It seems that the reason is in our build scripts (which we use to make SCIP et al from sources).**
After installing SCIPOptSuite applications from "legal" DEB-package  [SCIPOptSuite-8.0.1-Linux-ubuntu.deb](https://scipopt.org/download.php?fname=SCIPOptSuite-8.0.1-Linux-ubuntu.deb) PySCIPOpt 4.2.0 seems work properly.

**Comment by vvvol** [comment]
We found that the problem might be caused by setting **-DTPI=tny** in **cmake** options (in SCIP build script).
To keep multi-threading feature of **scip** application (see **concurrentopt** command) we had put **-DTPI=omp** and the problem seems was resolved.
Nevertheless it would be right if developers will issue official recommendation/workaround/patch...

**Comment by ambros-gleixner** [comment]
Do you know if the interactive shell on the command line works for the binary built with -DTPI=tny ?

**Comment by vvvol** [comment]
It (SCIP console app built with **DTPI=tny**) works at all my systems (Ubuntu 20.04, Debian 11). 
But fscip (FiberSCIP) does not:`
_[syncstore.c:72] ERROR: Error <0> in function call
[scip_general.c:245] ERROR: Error <0> in function call
[scip_general.c:289] ERROR: Error <0> in function call
[syncstore.c:88] ERROR: Error <0> in function call
[scip_general.c:331] ERROR: Error <0> in function call
[scipParaInitiator.cpp:391] ERROR: Error <0> in function call
19830 Segmentation fault_

If **DTPI=omp**, then both scip and fscip work as usual ...

**Comment by ambros-gleixner** [comment]
Thanks, we will have to look what could cause the incompatibility here.

**Comment by Joao-Dionisio** [comment]
I'm out of the loop, sorry. Is this issue still relevant @vvvol, or was it fixed in the meantime?

**Comment by Joao-Dionisio** [comment]
Closing this issue to clear the issue page, but feel free to reopen it if you think it's still necessary.
