### ISSUE TITLE
Wrong answer?

### ISSUE THREAD

**Issue by PauCantosColl** [scipopt/PySCIPOpt#609]
The example program asks to minimize x+y subject to 2x-y^2>=0 and y integer. When I ran it on my computer I got the answer:

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 0.00
Solving Nodes      : 0
Primal Bound       : +0.00000000000000e+00 (2 solutions)
Dual Bound         : +0.00000000000000e+00
Gap                : 0.00 %
x: 0.0
y: -0.0

Isn't this wrong? Clearly, the minimum is -1/2 at (x, y)=(1/2, -1). Is this only a problem with my computer?

**Comment by mattmilten** [comment]
In (Integer) Linear Programming, variables are nonnegative if not declared otherwise, so the result is perfectly fine.

**Comment by PauCantosColl** [comment]
Oh, good to know. I don't find it obvious as there's not a lot of documentation...

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
