### ISSUE TITLE
Branch and price, pricerredcost is not checked after branching

### ISSUE THREAD

**Issue by zzy-opt** [scipopt/PySCIPOpt#611]
![scip](https://user-images.githubusercontent.com/20296031/188326568-acd1a8cd-271d-4504-bd9a-f2414e8b1a25.png)
I am using branch and price and dantzig-wolfe decomposition to solve my problem.
As shown in the log, it successfully solves the dantzig-wolfe reformulation to optimality and dual bound is updated.
However after branching, pricerredcost is not called anymore, since the printing the log "try to find new cols" is the first line of pricerredcost.

The major difference of my implementation to the standard way is that I use constraint handler to do the branching job. I have continuous convexity variables in my restricted master problem and I branch by using some external information. If I use BranchingRule, since all my variables are continous, branching methods are never called.

Could someone give me some quick insight about this, I doubt I missed some parameter setting somewhere but found nothing after looking around the source code. Or could it be a scip bug because I use constraint handler to do the branching job?

**Comment by zzy-opt** [comment]
I implemented the test case with pricer and constraint handler as branching tool. It works perfectly fine. I will keep digging into my own code to figure out what is going on wrong.

**Comment by CGraczyk** [comment]
Hi, 
if you like you can try to open a merge request with your functionality to discuss and or develop it to be included in the general pyscipopt API, this also makes it easier to give concrete feedback as well as figuring out any issues (or lack thereof) from the given code. 

Glad you found a solution!
