### ISSUE TITLE
scipopt mutil objective

### ISSUE THREAD

**Issue by xtjjyygy** [scipopt/PySCIPOpt#614]
I wonder if the SCIP solver can support multi-objective optimization with different priorities like GUROBI or if is there any alternative method in scip. If there is a certain method, could you provide some examples that can be used in python. Thank you so much.

**Comment by CGraczyk** [comment]
Hi,
Thank you for your question, please have a look at https://www.scipopt.org/doc/html/ 
for SCIPOpt specific questions or contact the SCIP team directly https://www.scipopt.org/index.php#contact.

If you find the desired functionality in SCIP, you can see in `src/scip.pyx` if the relevant functions have been wrapped. If not you can start a new merge request to provide a wrapper for said function (if publicly available) and we will support you with the implementation of said wrapper if possible.

**Comment by Joao-Dionisio** [comment]
Hey @xtjjyygy , I've been looking, and I don't think PySCIPOpt directly supports multiobjective optimization. Nevertheless, I think PolySCIP might be what you want: https://polyscip.zib.de/ , but I am not familiar with it. Let me know if it helps!
