### ISSUE TITLE
SCIP installation with TPI tny

### ISSUE THREAD

**Issue by berryvermin** [scipopt/PySCIPOpt#616]
On my Ubuntu 18.04 I'm trying to enable solveConcurrent in PySCIPOpt by installing SCIP via cmake with argument TPI=tny. When I run the cmake command (cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DSOPLEX_DIR=/usr/local -DZIMPL=off -DIPOPT=off -DPAPILO=off -DTPI=tny) I don't see TPI=tny in the terminal output, is it supposed to be there?. 
![SCIP cmake setup](https://user-images.githubusercontent.com/74764006/193243921-78349469-208f-43ab-a636-006d853ea8a0.JPG)
When I then make and install this (and PySCIPOpt afterwards), solveConcurrent cannot be called.

If I change PAPILO to "on", I get this message when making:
```
/usr/local/include/papilo/presolvers/SimpleSubstitution.hpp:36:13: fatal error: papilo/misc/extended_euclidean.hpp: No such file or directory
    #include "papilo/misc/extended_euclidean.hpp"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated
```

What is going wrong here? I'm quite new to all this, hope someone can help!

**Comment by Joao-Dionisio** [comment]
Hey @berryvermin , sorry for taking so long to reply. I am probably even newer to this than you, so I don't think I will be able to help much. I think when you are trying to compile SCIP yourself, some of the things you have to have built previously. Maybe Papilo is one of those things. Have you checked its [repository](https://github.com/scipopt/papilo/)?

Sorry if this suggestion is useless. As I said, I also don't understand much about this.

**Comment by vvvol** [comment]
Dear @berryvermin,
 I can recommend you to build SCIP with **TPI=omp** (do not forget to install OpenMP package).
This hint enable us to use concurrentopt mode and PySCIPOpt normally at Ubuntu 20.04...

**Comment by berryvermin** [comment]
I created a new virtual environment to investigate whether this had something to do with previous installation attempts and that fixed the problem. Did a complete fresh install of SoPlex and SCIP and now the concurrentopt does works from the SCIP interactive window!
