### ISSUE TITLE
Is there a parameter to tell SCIP to focus on improving the primal or improving the bound?

### ISSUE THREAD

**Issue by Joao-Dionisio** [scipopt/PySCIPOpt#619]
Akin to the [MIPFocus](https://www.gurobi.com/documentation/9.5/refman/mipfocus.html) from Gurobi. In my model, I can heuristically get a good solution, and want to focus more on improving the dual bound. I tried looking at the parameter list, but it's quite dense, and I couldn't find anything.

PS: I don't know where I should put these types of irrelevant issues, as I don't want to put unproductive things in the gitlab...

**Comment by fserra** [comment]
Maybe:
```
from pyscipopt import Model, SCIP_PARAMEMPHASIS

scip = Model()
scip.setEmphasis(SCIP_PARAMEMPHASIS.OPTIMALITY)
```

**Comment by Joao-Dionisio** [comment]
Yeah, that seems to be it @fserra , thanks!
