### ISSUE TITLE
Why function SCIPfindEventhdlr() is declared twice in scip.pxd

### ISSUE THREAD

**Issue by vvvol** [scipopt/PySCIPOpt#620]
What is the reason that the function SCIPfindEventhdlr() is declard twice in scip.pxd.
There are two identical lines in the file scip.pxd (#L578, #L873):
`SCIP_EVENTHDLR* SCIPfindEventhdlr(SCIP* scip, const char* name)
`
both in the "section" 
`cdef extern from "scip/scip.h":`

**Comment by Joao-Dionisio** [comment]
Good eye, @vvvol! I'm not that familiar with C/Cython, but it does seem to be unnecessary. Would you mind creating a pull request with the fix?
