### ISSUE TITLE
Why do we need to disable heuristics when using dual values?

### ISSUE THREAD

**Issue by pambus** [scipopt/PySCIPOpt#631]
Hi all,
I hope you are doing great. Thank you very much for helping us with PySCIPOpt.

I am using SCIP to implement a branch and price algorithm (with binary variables). I have a question regarding something on the pyscipopt's README.  

In the "Dual values" section (https://github.com/scipopt/PySCIPOpt#dual-values), it says:

> While PySCIPOpt supports access to the dual values of a solution, there are some limitations involved:
> -**Heuristics should also be disabled to avoid that the problem is solved before the LP solver is called.** 

I do not fully understand why heuristics should be disabled when using dual values. Is it possible that you could give me a little bit more of information about this?

Thank you very much!

**Comment by Joao-Dionisio** [comment]
Hey @pambus, thank you very much for your kind words!

SCIP does not do all the heavy lifting when it comes to the solving process. It calls an LP solver when it wants to solve an LP problem, it can call an outside solver for the presolving stage, etc. etc. My guess is that having the problem be solved via a SCIP heuristic stops the solving process without the need to call the LP solver. The issue with that (I think) is that SCIP does not have a way to get the dual values itself, relying instead on the chosen LP solver.

Again, I am not sure if I am right, so maybe it will be better to wait for a more experienced user to answer. Nevertheless, let me know if it makes sense, and don't be afraid to ask additional questions!

**Comment by pambus** [comment]
Hi Joao!, 
Thank you for your quick response. If what you are saying is correct, then, if I actually get the dual values in every iteration of my branch and price, it would mean that everything is ok. Right?

I had another hypothesis. In every iteration of the B&P, we solve a linearized master, and that gives us dual values. If we add a primal heuristic maybe this is going to make us obtain a solution that is feasible for the LP of the reduced master problem (i.e. with the current columns), which is not necessarily feasible for the complete master problem. Does this make sense?

Best,

**Comment by Joao-Dionisio** [comment]
> If what you are saying is correct, then, if I actually get the dual values in every iteration of my branch and price, it would mean that everything is ok. Right?

Yeah, I think that can happen! The disabling of the heuristics is more of a precaution, I believe, against the easy subproblems that would be solvable with only the heuristic. If at every node your subproblem is hard enough that it requires the LP solver, then everything should be fine.

> (...) obtain a solution that is feasible for the LP of the reduced master problem (i.e. with the current columns), which is not necessarily feasible for the complete master problem. Does this make sense?

I am also trying to learn stuff about B&P, so I might be totally wrong. But it seems to me that if a solution is feasible for the RMP, then it is feasible for the complete MP, right? The solution space of the latter contains the solution space of the former. Maybe I misunderstood what you said, as I am yet not super familiar with B&P. Sorry if that's the case!

Cheers,
João

**Comment by Joao-Dionisio** [comment]
I am closing the issue to clear the Issues page, but feel free to reopen it if you still have questions!
