### ISSUE TITLE
Proper Error Message for Unsupported Comparison

### ISSUE THREAD

**Issue by dasmy** [scipopt/PySCIPOpt#634]
Trying to add the constraint
```
model.addCons(abs(x - pos[0]) + abs(y - pos[1]) > range)
```
I received a pretty cryptic error message of the following form:
```
Traceback (most recent call last):
  File "/Users/m290886/Projects/Advent_of_Code/2022/15b.py", line 68, in <module>
    model.addCons(abs(x - pos[0]) + abs(y - pos[1]) > range)
  File "src/pyscipopt/expr.pxi", line 550, in pyscipopt.scip.GenExpr.__richcmp__
  File "src/pyscipopt/expr.pxi", line 80, in pyscipopt.scip._expr_richcmp
NotImplementedError
```
After being a bit clueless, I inspected the respective source code at https://github.com/scipopt/PySCIPOpt/blob/master/src/pyscipopt/expr.pxi#L57 to find out that I can only use `<=`, `>=`, `==`. My constraint could be easily reformulated, but it would be helpful as guidance for users, to emit some helpful text in this case, e.g.
```
raise NotImplementedError("Please reformulate your constraint using '<=', '>=', or '=='. Simple '<' or '>' are not supported.") 
```

**Comment by dasmy** [comment]
Hi @Joao-Dionisio ,
sorry - I overlooked your answer in my message stream and thus also needed a while to pick this up again. Just created a PR for this. Please let me know there in case anything is missing or should be improved.

**Comment by Joao-Dionisio** [comment]
Hello @dasmy! No need to apologize :) 

I don't have permissions to accept push requests, but everything seems good, someone should accept it shortly. Thank you for your contribution!
