### ISSUE TITLE
The death of the kernel when calling the function node.getNParentBranchings() 

### ISSUE THREAD

**Issue by OksanichenkoFedor** [scipopt/PySCIPOpt#639]
When solving a MaxCut task in JupyterLab using pyScipOpt and getting information about the current node (node.getNParentBranchings()) at a certain step, the kernel dies without a ScipError. JupyterLab returns AsyncIOLoopKernelRestarter error. Could you help with solving this problem?

**Comment by Joao-Dionisio** [comment]
Hello! I don't know if I'll be able to help, but can you please post your code and the SCIPError you received?

**Comment by Joao-Dionisio** [comment]
I am closing the issue to clear the Issues page, but feel free to reopen it if you are still having trouble!
