### ISSUE TITLE
SCIP Segmentation Fault when deleting constraints

### ISSUE THREAD

**Issue by LorenzoBonasera** [scipopt/PySCIPOpt#640]
Hi all, 
I have to add an 'AND' constraint to my model and then remove it:

`addedCons = model.addConsAnd(vars, andVar, name="andConstr")`
`model.optimize()`
`model.freeTransform()`
`model.delCons(addedCons)`

However, the last command causes a segmentation fault error. Any ideas or suggestions?

**Comment by LorenzoBonasera** [comment]
It also happens if I skip optimization:

`addedCons = model.addConsAnd(vars, andVar, name="andConstr")`
`model.delCons(addedCons)`

**Comment by Joao-Dionisio** [comment]
Hello, @LorenzoBonasera ! Unfortunately, some methods in PySCIPOpt are causing segmentation faults, like addConsOr (see issue #637), but also, but freeTransform is also associated with some issues. 

At the moment I am unable to fix the code, but if you share what you want to do, maybe I can help with the modeling as I did with #637.

**Comment by LorenzoBonasera** [comment]
Hello!
I made some debugging and I've found that, at least in my case, the methods freeTransform and addConsAnd are the ones causing segfault issues.

I tried to read ex-novo the problem from MPS file, without adding constraints and avoiding freeTransform, but I still get the segfault error!

My goal is to "reset" my optimization model after solving it.

**Comment by LorenzoBonasera** [comment]
> Do you mean that you solve a model `m`, read from an MPS again, change the model a bit, and then reoptimize it? What about creating a new model from scratch? Would that work?

Yes. I tried creating a new model from scratch, but I still got segfault. I did something like this:
`model.optimize()`
`del model`
`model = pyscipopt.Model("new")`
`model.readProblem(file)`

> I don't know if it's applicable to your case, but there is also the method [freeReoptSolve](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#a703f8cde4f377ac5c7411afb2df2d941)

freeReoptSolve() doesn't work after optimize(), since the STAGE does not permit it. Only freeTransform() can do the work.

**Comment by Joao-Dionisio** [comment]
What about doing this:

```
model.optimize()
model2 = pyscipopt.Model("new")
model2.readProblem(file)
```

Does it still crash the code? If so, the problem might be elsewhere. Maybe there is an issue with readProblem or with the file itself, I don't know.

**Comment by Joao-Dionisio** [comment]
I am closing the issue to clear the Issues page, but feel free to reopen it if you still have problems!
