### ISSUE TITLE
Branching on general disjunctions

### ISSUE THREAD

**Issue by prachishah6795** [scipopt/PySCIPOpt#641]
Is it possible to provide a general disjunction for branching in SCIP? To be precise, I want to solve a MIP by branching on disjunctions involving multiple variables which can be expressed as, $$\pi x \le \pi_0 \vee \pi x \ge \pi_0 + 1,$$ where $(\pi, \pi_0) \in \mathbb{Z}^n \times \mathbb{Z}$

**Comment by Joao-Dionisio** [comment]
Hello! :) 

I believe what you are asking is possible. Have you looked at [branching rules](https://scipopt.org/doc/html/BRANCH.php)? They can be a bit complicated to use at first, but here is an [example](https://github.com/scipopt/PySCIPOpt/blob/master/tests/test_branch_probing_lp.py) on PySCIPOpt.

As for general disjunctions, PySCIPOpt does have [addConsOr()](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#abce862b4e66d284b4647497c46233da3), but it is possible that it leads to a segmentation fault. Fortunately, disjunctions like the one you present should be easy to model with additional binary variables.

**Comment by Joao-Dionisio** [comment]
I am closing the issue to clear the Issues page, but feel free to reopen it if you still have problems!
