### ISSUE TITLE
Python API for FiberSCIP

### ISSUE THREAD

**Issue by vvvol** [scipopt/PySCIPOpt#643]
Can you recommend some open project regarding Python API for FiberSCIP (fscip) - parallel implementation of SCIP (for multi-core systems)?
May be we can expect that PySCIPOpt will be extended to FiberSCIP as well?

**Comment by Joao-Dionisio** [comment]
Hello, @vvvol ! Thank you for your questions. Unfortunately, I don't know how to answer them. Maybe Yuji Shinano, who is more involved with FiberSCIP, will know more about your first question. 

Hey @CGraczyk , what do you think about the second question?

**Comment by Joao-Dionisio** [comment]
Hello, @vvvol. I haven't been able to find what you are looking for. I've only found [this](https://stackoverflow.com/questions/53206938/using-parascip-ug-in-pyscipopt) question on StackExchange, with the following suggestion from Gregor:

> You should probably suggest to use Pyscipopt to write out the model in mps-format, and then read and solve it with FiberSCIP.

Maybe it can help out in your case. 

As for the second question, I don't think anyone from SCIP's side will pick it up in the near future. But if you think that the addition is within your possibilities, then we would be extremely grateful for a PR.

**Comment by Joao-Dionisio** [comment]
Hey, @vvvol. Unless I'm mistaken, the ```solveConcurrent``` method would solve your problem. To do it, you would need to compile SCIP with the correct options. Unfortunately, it appears that there are some problems with this method - see Issue #671. Nevertheless, the two issues seem to be linked, so I'll be closing this one. If you think that's not the case, feel free to reopen!
