### ISSUE TITLE
Mac OS install error

### ISSUE THREAD

**Issue by Deep-sea-boy** [scipopt/PySCIPOpt#645]
Apple M1 Pro
Mac OS 13.1
pycharm/python3.9/virtualenv

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/37582640/218070213-9be188b4-5043-4b52-bf93-852094320f25.png">

<img width="414" alt="image" src="https://user-images.githubusercontent.com/37582640/218070079-4f9ff839-b91f-4fd2-badc-8c15c9c8b1bc.png">

1、Copy pyscipopt and PySCIPOpt-4.2.0.dist-info to my local python venv site-packages.

2、I have installed SCIPOptSuite :

<img width="243" alt="image" src="https://user-images.githubusercontent.com/37582640/218072183-dfb60e0a-7265-4df2-b12c-586a2777f41a.png">
<img width="705" alt="image" src="https://user-images.githubusercontent.com/37582640/218073300-4c1ea890-d1f8-454a-a9cc-138807f9df09.png">

3、Try to  import pyscipopt

Here is error msg：
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/37582640/218072239-607fe07f-3442-468a-a4b2-602332aec5f9.png">

Is it because of the lack of rpath?
What do I need to do？

**Comment by Joao-Dionisio** [comment]
Hello, @Deep-sea-boy ! I don't know if I'll be able to help, but here are a few suggestions. First, I think that SCIP needs to be accessible from inside the virtual environment. Second, maybe installing PySCIPOpt requires having already installed SCIP, instead of doing the installation afterward? And finally, if this does not matter in your objectives, I find that [installing SCIP with Anaconda](https://github.com/scipopt/PySCIPOpt#installation) is the easiest way to do it (with the attention of creating a new virtual environment). 

Please let me know if any of this helps!

**Comment by Deep-sea-boy** [comment]
`(myProject) zenghaisheng@cenghaishengdeMacBook-Pro tailassignalg % conda install --channel conda-forge pyscipopt
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/zenghaisheng/miniconda3/envs/myProject

  added / updated specs:
    - pyscipopt


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ampl-mp-3.1.0              |    hbec66e7_1006         968 KB  conda-forge
    bzip2-1.0.8                |       h3422bc3_4         148 KB  conda-forge
    ca-certificates-2022.12.7  |       h4653dfc_0         142 KB  conda-forge
    certifi-2022.12.7          |     pyhd8ed1ab_0         147 KB  conda-forge
    cppad-20230000.0           |       hb7217d7_0         423 KB  conda-forge
    gmp-6.2.1                  |       h9f76cd9_0         557 KB  conda-forge
    ipopt-3.14.11              |       h843a782_0         732 KB  conda-forge
    libblas-3.9.0              |16_osxarm64_openblas          13 KB  conda-forge
    libedit-3.1.20191231       |       hc8eb9b7_2          94 KB  conda-forge
    libiconv-1.17              |       he4db4b2_0         1.3 MB  conda-forge
    liblapack-3.9.0            |16_osxarm64_openblas          13 KB  conda-forge
    libsqlite-3.40.0           |       h76d750c_0         804 KB  conda-forge
    libzlib-1.2.13             |       h03a7124_4          50 KB  conda-forge
    metis-5.1.0                |    h9f76cd9_1006         4.1 MB  conda-forge
    mumps-include-5.2.1        |      hce30654_11          24 KB  conda-forge
    mumps-seq-5.2.1            |      h0066fe1_11         3.0 MB  conda-forge
    openssl-3.0.8              |       h03a7124_0         2.0 MB  conda-forge
    pyscipopt-4.2.0            |   py39h23fbdae_3         602 KB  conda-forge
    python-3.9.16              |hea58f1e_0_cpython        10.6 MB  conda-forge
    python_abi-3.9             |           3_cp39           6 KB  conda-forge
    scip-8.0.3                 |       h4bea629_1         6.5 MB  conda-forge
    scotch-6.0.9               |       h7537618_2         1.3 MB  conda-forge
    tbb-2021.7.0               |       hffc8910_1         116 KB  conda-forge
    unixodbc-2.3.10            |       hb39ff51_0         262 KB  conda-forge
    zlib-1.2.13                |       h03a7124_4          79 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        33.9 MB

The following NEW packages will be INSTALLED:

  ampl-mp            conda-forge/osx-arm64::ampl-mp-3.1.0-hbec66e7_1006 
  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h3422bc3_4 
  cppad              conda-forge/osx-arm64::cppad-20230000.0-hb7217d7_0 
  gmp                conda-forge/osx-arm64::gmp-6.2.1-h9f76cd9_0 
  ipopt              conda-forge/osx-arm64::ipopt-3.14.11-h843a782_0 
  libblas            conda-forge/osx-arm64::libblas-3.9.0-16_osxarm64_openblas 
  libedit            conda-forge/osx-arm64::libedit-3.1.20191231-hc8eb9b7_2 
  libiconv           conda-forge/osx-arm64::libiconv-1.17-he4db4b2_0 
  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-16_osxarm64_openblas 
  libsqlite          conda-forge/osx-arm64::libsqlite-3.40.0-h76d750c_0 
  libzlib            conda-forge/osx-arm64::libzlib-1.2.13-h03a7124_4 
  metis              conda-forge/osx-arm64::metis-5.1.0-h9f76cd9_1006 
  mumps-include      conda-forge/osx-arm64::mumps-include-5.2.1-hce30654_11 
  mumps-seq          conda-forge/osx-arm64::mumps-seq-5.2.1-h0066fe1_11 
  pyscipopt          conda-forge/osx-arm64::pyscipopt-4.2.0-py39h23fbdae_3 
  python_abi         conda-forge/osx-arm64::python_abi-3.9-3_cp39 
  scip               conda-forge/osx-arm64::scip-8.0.3-h4bea629_1 
  scotch             conda-forge/osx-arm64::scotch-6.0.9-h7537618_2 
  tbb                conda-forge/osx-arm64::tbb-2021.7.0-hffc8910_1 
  unixodbc           conda-forge/osx-arm64::unixodbc-2.3.10-hb39ff51_0 

The following packages will be UPDATED:

  openssl              pkgs/main::openssl-1.1.1s-h1a28f6b_0 --> conda-forge::openssl-3.0.8-h03a7124_0 
  zlib                    pkgs/main::zlib-1.2.13-h5a0b063_0 --> conda-forge::zlib-1.2.13-h03a7124_4 

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2023.01.10~ --> conda-forge::ca-certificates-2022.12.7-h4653dfc_0 
  certifi            pkgs/main/osx-arm64::certifi-2022.12.~ --> conda-forge/noarch::certifi-2022.12.7-pyhd8ed1ab_0 
  python                pkgs/main::python-3.9.16-hc0d8a6c_0 --> conda-forge::python-3.9.16-hea58f1e_0_cpython 


Proceed ([y]/n)? y


Downloading and Extracting Packages
                                                                                                                                                                       
Preparing transaction: done                                                                                                                                            
Verifying transaction: done                                                                                                                                            
Executing transaction: done
`
  
`                                                                                                                                         
(myProject) zenghaisheng@cenghaishengdeMacBook-Pro tailassignalg % python
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) 
[Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyscipopt import Model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zenghaisheng/miniconda3/envs/myProject/lib/python3.9/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: dlopen(/Users/zenghaisheng/miniconda3/envs/myProject/lib/python3.9/site-packages/pyscipopt/scip.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/liblapack.3.dylib
  Referenced from: <F1EE2CFD-F116-3025-AB03-E9416DB72B78> /Users/zenghaisheng/miniconda3/envs/myProject/lib/libdmumps_seq-5.2.1.dylib
  Reason: tried: '/Users/zenghaisheng/miniconda3/envs/myProject/lib/liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/lib/liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/lib/liblapack.3.dylib' (no such file), './liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/lib/python3.9/site-packages/pyscipopt/../../../liblapack.3.dylib' (no such file), './liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/lib/python3.9/site-packages/pyscipopt/../../../liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/bin/../lib/liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/bin/../lib/liblapack.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/lib/liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/lib/liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/lib/liblapack.3.dylib' (no such file), './liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/lib/python3.9/site-packages/pyscipopt/../../../liblapack.3.dylib' (no such file), './liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/lib/python3.9/site-packages/pyscipopt/../../../liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/bin/../lib/liblapack.3.dylib' (no such file), '/Users/zenghaisheng/miniconda3/envs/myProject/bin/../lib/liblapack.3.dylib' (no such file), '/usr/local/lib/liblapack.3.dylib' (no such file), '/usr/lib/liblapack.3.dylib' (no such file, not in dyld cache)
`

**Comment by Deep-sea-boy** [comment]
I've installed SCIP and used conda to download pyscipopt。
As you see, it was failed.

**Comment by Deep-sea-boy** [comment]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/37582640/218177735-ad4f4e8f-9e12-4f5c-9c18-aad5dc2ddb47.png">

The file is exists.

Why does is say "Reason: tried: '/Users/zenghaisheng/miniconda3/envs/myProject/lib/liblapack.3.dylib' (no such file), "

**Comment by Joao-Dionisio** [comment]
That does seem to be everything. Do you have multiple Pythons in the myProject env? Maybe when you call "python" on the command line, it calls the wrong one... I don't think I can help more, I am sorry.

@mattmilten , do you know what could be causing this?

**Comment by mattmilten** [comment]
Why did you copy anything to your python site-packages? This is usually not a good idea and should be left to the package managers. There should also not be two different pyscipopt directories.
Can you run 'scip' in the command line? If the SCIPOptSuite was installed correctly, this should work. This also requires the SCIP lib to be accessible at runtime.

**Comment by mattmilten** [comment]
It could be that there is some issue with the lapack lib and your macOS... I am not an expert concerning macOS and my best bet is to start with a fresh env and reinstall everything using conda.

**Comment by Deep-sea-boy** [comment]
> 

Yes，as you see ,second time I start with a fresh env and reinstall everything using conda, not use pip anymore.
And I run 'scip' , I'm pretty sure I have SCIPOptSuite installed.

Maybe is Mac OS problem...

**Comment by Deep-sea-boy** [comment]
Thank you.   I decided to build a new conda  env  and run 'conda install --channel conda-forge pyscipopt'  and then it works.
It is possible that some libraries(not pyscipopt)  were installed without -c conda-forge before, causing problems.

**Comment by brucefeng10** [comment]
> Thank you. I decided to build a new conda env and run 'conda install --channel conda-forge pyscipopt' and then it works. It is possible that some libraries(not pyscipopt) were installed without -c conda-forge before, causing problems.

i've encountered all the same as you!!!
