### ISSUE TITLE
dyld[44326]: Library not loaded: '@rpath/libtbb.12.dylib'

### ISSUE THREAD

**Issue by brucefeng10** [scipopt/PySCIPOpt#653]
Hello~
I installed SCIP Optimization Suite on my Mac according to the standard steps:
![image](https://user-images.githubusercontent.com/22636115/221085151-191b8ee5-968a-469d-8aad-e394ecab6c24.png)
and everything goes well except some warnnings during compiling.
But after that I try to check if SCIP is installed successfully, I typed `scip` in the command, the result is not OK, which shows:
![image](https://user-images.githubusercontent.com/22636115/221086984-ca09fde0-a033-462c-9156-1502f81b237f.png)
I try to run my model in python using PyScipOpt, similar error occurred: `'libscip.8.0.dylib' (no such file)`.

Did I miss any steps? Anybody meets similar errors?

**Comment by brucefeng10** [comment]
`brew install tbb` solved this!

**Comment by Joao-Dionisio** [comment]
Hello, @brucefeng10 ! I am glad to know that you solved your issue. Is everything alright now? Can the issue be closed?
