### ISSUE TITLE
AttributeError: module 'pyscipopt' has no attribute 'Cutsel'

### ISSUE THREAD

**Issue by zslztms** [scipopt/PySCIPOpt#656]
How do I use the module "pyscipopt.Cutsel"? What need I do? I use the pyscipopt 4.2.0 and scip 8.0.3.
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18508\15449140.py in <module>
      1 import pyscipopt
----> 2 print(pyscipopt.Cutsel)

AttributeError: module 'pyscipopt' has no attribute 'Cutsel'`

**Comment by Joao-Dionisio** [comment]
Hello, @zslztms! Can you please tell me what you are trying to do? I don't know if you are able to access cutsel directly... Either way, you can find its documentation here: [https://scipopt.github.io/PySCIPOpt/docs/html/namespacepyscipopt_1_1cutsel.html](https://scipopt.github.io/PySCIPOpt/docs/html/namespacepyscipopt_1_1cutsel.html)

**Comment by zslztms** [comment]
I run the test script for "https://github.com/MIRALab-USTC/L2O-HEM-Torch" and the code uses the class 'pyscipopt.Cutsel'. But when I run it, it shows module 'pyscipopt' has no attribute 'Cutsel'. So, I want to know how do I import the class 'pyscipopt.Cutsel'.

**Comment by Joao-Dionisio** [comment]
I am also having the same problem... Perhaps the authors modified their own PySCIPOpt somehow? It appears that that is what they are doing with ```environments.py```. On the github page they mention:

> After the environment and dataset are ready, execute the following code to begin training and periodically test the training model performance

So perhaps the ability to access cutsel in that manner is only a result of their code. Sorry for not being able to help, maybe the authors will be able to provide a better insight.
