### ISSUE TITLE
Install PySCIPOpt by using pip on Windows 10 64bit / Python 3.11.2 / SCIP 8.0.3

### ISSUE THREAD

**Issue by toby-ks** [scipopt/PySCIPOpt#657]
I have followed the [instructions](http://scip-interfaces.github.io/PySCIPOpt/docs/html/md_INSTALL.html).
1. Downloaded SCIPOptSuite-8.0.3-win64-VS15.exe, and installed to C:\Program Files\SCIPOptSuite 8.0.3
2. Set SCIPOPTDIR=C:\Program Files\SCIPOptSuite 8.0.3
3. Added C:\Program Files\SCIPOptSuite 8.0.3\bin to my environment variables PATH
4. Run cmd to verify scip [Successful]

I got compile error msg and could not install PySCIPOpt.
Am I doing something wrong?

      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\Multidict.py -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\__init__.py -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\scip.pyx -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\scip.pxd -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\benders.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\benderscut.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\branchrule.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\conshdlr.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\cutsel.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\event.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\expr.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\heuristic.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\lp.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\nodesel.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\presol.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\pricer.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\propagator.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\reader.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\relax.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      copying src\pyscipopt\sepa.pxi -> build\lib.win-amd64-cpython-311\pyscipopt
      running build_ext
      building 'pyscipopt.scip' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\src
      creating build\temp.win-amd64-cpython-311\Release\src\pyscipopt
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Program Files\SCIPOptSuite 8.0.3\include" -IC:\Users\Administrator\AppData\Local\Programs\Python\Python311\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /Tcsrc\pyscipopt\scip.c /Fobuild\temp.win-amd64-cpython-311\Release\src\pyscipopt\scip.obj
      scip.c
      src\pyscipopt\scip.c(100989): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src\pyscipopt\scip.c(103872): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src\pyscipopt\scip.c(104080): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src\pyscipopt\scip.c(107482): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src\pyscipopt\scip.c(108068): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src\pyscipopt\scip.c(108666): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src\pyscipopt\scip.c(123474): warning C4244: 'function': conversion from 'long' to 'char', possible loss of data
      src\pyscipopt\scip.c(133561): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
      src\pyscipopt\scip.c(133625): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
      src\pyscipopt\scip.c(133689): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
      src\pyscipopt\scip.c(138636): warning C4244: 'function': conversion from 'long' to 'char', possible loss of data
      src\pyscipopt\scip.c(139250): warning C4244: 'function': conversion from 'long' to 'char', possible loss of data
      src\pyscipopt\scip.c(176759): error C2037: left of 'f_lineno' specifies undefined struct/union '_frame'
      src\pyscipopt\scip.c(180913): error C2037: left of 'f_back' specifies undefined struct/union '_frame'
      src\pyscipopt\scip.c(180950): error C2037: left of 'f_back' specifies undefined struct/union '_frame'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2`

**Comment by mattmilten** [comment]
Can you try with Python 3.10 instead? There might be an issue with Cython.

**Comment by toby-ks** [comment]
Thank you for your help.
I confirmed to install with Python 3.10.10
