### ISSUE TITLE
How to get intermediate variables of strong branching process

### ISSUE THREAD

**Issue by ll906875341** [scipopt/PySCIPOpt#662]
Hi,

Is it possible to get the intermediate variables in the calculation process of vanilla strong branching? The getVanillafullstrongData function can only get candidate scores. How can I get the optimal objective function values of the LPs of the child nodes of each candidate variable in the calculation process?

Thank you!
Zero

**Comment by ll906875341** [comment]
I implemented the getDowngainUpgainData() function code according to the runVanillaStrongBranching() function, and no problems were found during the testing. 
`
    def getDowngainUpgainData(self):

        # get current LP objective bound of the local sub problem and global cutoff bound
        cdef SCIP* scip = self._scip
        cdef SCIP_Real lpobjval = SCIPgetLPObjval(scip)

        cdef SCIP_COL** cols = SCIPgetLPCols(scip)
        cdef int ncols = SCIPgetNLPCols(scip)

        cdef np.ndarray[np.float32_t, ndim=2] lp_datas
        lp_datas = np.empty(shape=(ncols, 2), dtype=np.float32)

        # initialize strong branching without propagation
        PY_SCIP_CALL( SCIPstartStrongbranch(scip, False) )

        # compute downgain/upgain scores
        cdef SCIP_VAR* var
        cdef SCIP_Real val
        cdef SCIP_Bool integral
        cdef SCIP_Real down, up
        cdef SCIP_Real downgain, upgain
        cdef SCIP_Bool downvalid, upvalid
        cdef SCIP_Bool downinf, upinf
        cdef SCIP_Bool downconflict, upconflict
        cdef SCIP_Bool lperror
        cdef SCIP_Bool idempotent
        idempotent = True

        for i in range(ncols):
            col_i = SCIPcolGetLPPos(cols[i])
            var = SCIPcolGetVar(cols[i])
            val = SCIPvarGetLPSol(var)
            integral = SCIPisFeasIntegral(scip, val)
            up = -SCIPinfinity(scip)
            down = -SCIPinfinity(scip)

            if integral:
                PY_SCIP_CALL(SCIPgetVarStrongbranchInt(scip, var, 2147483647, idempotent,
                        &down, &up, &downvalid, &upvalid, &downinf, &upinf, &downconflict, &upconflict, &lperror))
            else:
                PY_SCIP_CALL(SCIPgetVarStrongbranchFrac(scip, var, 2147483647, idempotent,
                        &down, &up, &downvalid, &upvalid, &downinf, &upinf, &downconflict, &upconflict, &lperror))
                
            down = max(down, lpobjval)
            up = max(up, lpobjval)
            downgain = down - lpobjval
            upgain = up - lpobjval
            lp_datas[col_i][0] = downgain
            lp_datas[col_i][1] = upgain

        return lp_datas
`
Thank you very much for your open source code, and wish you a happy life.

**Comment by Joao-Dionisio** [comment]
Hello, @ll906875341! Sorry for not saying anything, but I had no idea how to solve your issue, and was waiting for someone else to pick it up.

Nevertheless, it's great that you managed to solve it. Even greater, is that you implemented a new method! Would you mind creating a Push Request with your code, so that it can be added to PySCIPOpt, if everything is okay?

**Comment by ll906875341** [comment]
Thank you very much for your reply! I am honored to contribute to the development of PySCIPOpt. The code has just been completed, but it has not been formatted yet. Additionally, I will implement other methods in my research process. I will create a new Push Request to submit the code when it's done. Thank you again for your support, and have a great day!

**Comment by Joao-Dionisio** [comment]
Hello, @ll906875341! Are there any updates on this?
