### ISSUE TITLE
Model Non Linear Objective function

### ISSUE THREAD

**Issue by andreafresa** [scipopt/PySCIPOpt#663]
Hi, I have the following objective function

$$ \max_{n_{ij}(t)} &&\sum_{i \in I} \sum_{j \in J_i}Q_ib({n_{ij}(t)}) + \sum_{i \in I}V_iw_{ij}\sum_{j\in J_i}\min({b(n_{ij}(t)) , Q_i- \sum_{k <j}b(n_{ik}(t))})a_{ij} $$

Where n_ij is a matrix of the decision variables. My function is not linear, because of min, thus it is a Non-Linear Integer Programming problem (NILP).
I converted min(a,b) = (a + b)/2 + abs(a-b)/2

I implemented my function in the following way:

```
def new_npilp(queue , service_rate , accuracy , V, numcores):
    model = scipop.Model("npilp")
    x = {}
    for i in range(len(service_rate)):
            x[i]=model.addVar("x"+str(i), vtype="I", lb=0, ub=numcores)    
    nonlinexp = {}
    term1 = {}
    term2 = {}
    model = scipop.Model("npilp")
    model.addCons(scipop.quicksum(x[i] for i in range(len(service_rate))) <= numcores)
    for i in range(len(service_rate)):
        term1[i] = accuracy[i]*service_rate[i][1]*x[i]
        term2[i] = accuracy[i]*queue-scipop.quicksum(service_rate[k][1]*x[k] for k in range(len(service_rate)))
        nonlinexp[i] = (term1[i]+term2[i]/2) + abs(term1[i]-term2[i])/2
        print(type(nonlinexp[i]))
    fun = scipop.quicksum(queue*service_rate[i][1]*x[i] + nonlinexp[i] for i in range(len(service_rate)))
    model.setObjective(fun, "maximize")
    model.optimize()
    
```

However I get the following error:

> AssertionError: given coefficients are neither Expr or number but SumExpr

Could someone help me here? How can I solve this using PySCIPOpt? If not, why?

**Comment by Joao-Dionisio** [comment]
Hello, @andreafresa! Can you also paste the data for your problem so that I can try to run it?

In the meantime, I think you can do what I believe is called an epigraph reformulation. If your nonlinear objective is max f(x), you can instead do max z and add the constraint z >= f(x).

**Comment by andreafresa** [comment]
Thank @Joao-Dionisio , I tried your formulation and also this one:


```
def new_npilp(queue , service_rate , accuracy , V, numcores):
    model = scipop.Model("npilp")
    x = {}
    for i in range(len(service_rate)):
            x[i]=model.addVar("x"+str(i), vtype="I", lb=0, ub=numcores)    
    nonlinexp = {}
    term1 = {}
    term2 = {}
    model.addCons(scipop.quicksum(x[i] for i in range(len(service_rate))) <= numcores)
    for i in range(len(service_rate)):
        nonlinexp[i] = (accuracy[i]*service_rate[i][1]*x[i])/2  + (accuracy[i]*queue-scipop.quicksum(service_rate[k][1]*x[k] for k in range(len(service_rate))))/2        
        print(type(nonlinexp[i]))
    fun = scipop.quicksum(queue*service_rate[i][1]*x[i] + nonlinexp[i] for i in range(len(service_rate)))
    model.setObjective(fun, "maximize")
    model.optimize()
    print("Optimal value:", model.getObjVal())
    print("x:", [model.getVal(x[i]) for i in range(len(service_rate))])
```

The problem in my formulation was that I was summing 2 Expr in nonlinexp, which becomes a sumExpr (not a smart implementation from PySCIPOpt in my opinion).
However, the decision variable are the same, but the objective values are slightly different: your solution reaches a bigger objective value, which is surprising to me. I will look more in detail into it and I will let you know! Thanks for your help.

**Comment by Joao-Dionisio** [comment]
No problem, @andreafresa! 

Looking at your code, I think you forgot some things, for example, the ```abs(term1[i]-term2[i])/2``` part, but when putting it all together, maybe it works as well :)

I am closing the issue now, to clear the issue page, but do let me know if you manage to do it!
