### ISSUE TITLE
(Feature Request) Add SCIP_PARAMEMPHASIS.NUMERICS to setEmphasis options

### ISSUE THREAD

**Issue by erdos4d** [scipopt/PySCIPOpt#665]
It appears that the class [PY_SCIP_PARAMEMPHASIS](https://github.com/scipopt/PySCIPOpt/blob/46f8eb87f9f95af0f0b5187cc10ce2a4de3a0ef0/src/pyscipopt/scip.pyx#L82) is missing 2 options from the available ones [here](https://scipopt.org/doc/html/type__paramset_8h.php#a2e51a867a8ea3ea16f15e7cc935c3f32). One is the NUMERICS option which sounds very useful. Can these options, especially the numerics one, be implemented? Many thanks, this is a nice library and is very helpful.

**Comment by Joao-Dionisio** [comment]
Hello, @erdos4d! Yeah, it seems that you are absolutely right, and that these things, while useful, are not implemented. Unfortunately, I cannot do it at the moment. If you don't mind waiting (possibly a long time), then eventually I think I'll manage. Of course, it goes without saying that if you have the possibility to contribute, we would be extremely grateful :)

**Comment by erdos4d** [comment]
@Joao-Dionisio I would be happy to make a pull request, but I am completely ignorant of how to implement these things beyond pasting the obvious lines in the PY_SCIP_PARAMEMPHASIS class. Is this all that is necessary, or is there something more? Thanks.

**Comment by mattmilten** [comment]
Hi @erdos4d! Yes, adding those lines is indeed all that is necessary to enable these options. This must have been forgotten when updating the interface to the latest version of SCIP.

**Comment by Joao-Dionisio** [comment]
Fixed in #667. Thank you, @erdos4d! I will be closing the issue, but feel free to reopen it if you think the discussion should continue!
