### ISSUE TITLE
version 8.03

### ISSUE THREAD

**Issue by jhconnolly** [scipopt/PySCIPOpt#668]
In the instillation instructions it says that generally only the major releases are compatible, but I noticed that the most recent workflows have version SCIP 8.03 set for the environment.  I'm in the process of setting up PySCIPOpt and was wondering if I can use version 8.03 instead of 8.00?

**Comment by jhconnolly** [comment]
thanks for the quick response

**Comment by mattmilten** [comment]
In general, you should always try to use the latest bugfix version of the current major release. So 8.0.3 is preferred to 8.0.0. There are no API changes within one major release, so PySCIPOpt works fine with all subversions. 8.0.3, though, contains some bug fixes and performance improvements you typically don't want to miss.
