### ISSUE TITLE
How to get memory usage statistics

### ISSUE THREAD

**Issue by erdos4d** [scipopt/PySCIPOpt#669]
Is it possible to get memory usage statistics, either in real time, or in summary after solving? I notice that the output does have a memory usage column, but I don't see any way to access this data. Thanks.

**Comment by Joao-Dionisio** [comment]
@erdos4d, that should be possible, and ```redirectOutput``` does seem to be the correct method for achieving your purposes. However, I've never used it, and I'm not figuring out how to work with it, sorry. I'll let you know if I manage to do it.

**Comment by Joao-Dionisio** [comment]
Nice to hear you found a solution, @erdos4d! Can this issue be closed, then?

**Comment by Joao-Dionisio** [comment]
I'm closing this issue to clear the issue page, but feel free to reopen it if you think it's still relevant! :)

**Comment by fserra** [comment]
another solution would be to extend the interface to export
```c
/** returns the total number of bytes in block and buffer memory
 *
 *  @return the total number of bytes in block and buffer memory.
 */
SCIP_EXPORT
SCIP_Longint SCIPgetMemTotal(
   SCIP*                 scip                /**< SCIP data structure */
   );
```
defined in `scip_mem.h`. That is the method that SCIP calls whenever it prints the memory
