### ISSUE TITLE
How to display log and statistics on Google-Colab

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#670]
Dear support team,

I am trying to get the log file and also the model statistics through the optimization process, and also after the solve terminates. It seems PySCIPOpt cannot show these!!! (the problem is solved without showing any error). As a template, I have tried something like this:

```
model = Model("Example")
variable_name= model.addVar()
model.setObjective(expression, "minimize")
model.addCons(LHS <= RHS)
model.optimize() 
model.printStatistics()
```

I am wondering if, how can I get this information?

Regards
Abbas

**Comment by mattmilten** [comment]
Hi Abbas,

Can you please try calling the method model.redirectOutput()? SCIP will print it's output the terminal that you cannot see in Colab.

I hope that helps.

Cheers,
Matthias

**Comment by abb-omidi** [comment]
Dear Dr. Miltenberger, (@mattmilten):

Many thanks for your hint. It works well.

Regards
Abbas
