### ISSUE TITLE
Trouble with concurrentopt

### ISSUE THREAD

**Issue by hfvuong** [scipopt/PySCIPOpt#671]
Hello, I'm having trouble running with the concurrentopt function.  I managed to rebuild scip with the TPI=tny.  The concurrent opt works while running scip via it's command line interface.  However when I attempt to use it in my python code I get a segfault. I brought this up to the scip mailing list, but they referred me here since it seems more like a pyscipopt issue. 

One thing that I noticed is the the SCIPTOPTDIR environment variable is ignored.  It's looking for my custom built scip in /home/username/scip and I don't know where that was set up.

I also tried to build with TPI=omp.  It also works on command line, but in pyscipopt it tells me:
 UserWarning: SCIP was compiled without task processing interface. Parallel solve not possible - using optimize() instead of solveConcurrent()
  model.solveConcurrent()

Any help is appreciated.

**Comment by mattmilten** [comment]
How (and where) did you install SCIP? Pointing PySCIPOpt to this directory (via SCIPOPTDIR) is crucial. You can also check whether some LD_LIBRARY_PATH setting in your environment is taking precedence over SCIPOPTDIR during runtime. In that case, you should clean up your environment variables.

**Comment by hfvuong** [comment]
Hi @mattmilten, apologies for the data dump, but I wanted to include as much detail as possible

I installed SCIP by downloading the tarball and using cmake to build and later install it.  I have a /scip folder in my own home directory.  I know that pyscipopt is looking for it there because if I remove it, my script comes back with this error:
(conda_scip) -bash-4.2$ python scip_runner.py test
Traceback (most recent call last):
  File "scip_runner.py", line 2, in <module>
    from pyscipopt import Model
  File "/home/hv28186/.conda/envs/conda_scip/lib/python3.8/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: libscip.so.8.0: cannot open shared object file: No such file or directory

Also using ldd on the scip.cpython-38-x86_64-linux-gnu.so I found in my virtual env's site-packages, I see that it refers to the version I installed:
(conda_scip) -bash-4.2$ ls
benderscut.pxi  conshdlr.pxi  expr.pxi       lp.pxi        presol.pxi      __pycache__  scip.cpython-38-x86_64-linux-gnu.so  sepa.pxi
benders.pxi     cutsel.pxi    heuristic.pxi  Multidict.py  pricer.pxi      reader.pxi   scip.pxd
branchrule.pxi  event.pxi     __init__.py    nodesel.pxi   propagator.pxi  relax.pxi    scip.pyx
(conda_scip) -bash-4.2$ ldd scip.cpython-38-x86_64-linux-gnu.so 
        linux-vdso.so.1 =>  (0x00007fff136f9000)
        **libscip.so.8.0 => /home/hv28186/scip/lib/libscip.so.8.0 (0x00007f3bd1605000)** <----here is the reference
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3bd13e9000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f3bd101b000)
        libz.so.1 => /home/hv28186/.conda/envs/conda_38/lib/libz.so.1 (0x00007f3bd0ffd000)
        libreadline.so.6 => /lib64/libreadline.so.6 (0x00007f3bd0db7000)
        libquadmath.so.0 => /home/hv28186/.conda/envs/conda_38/lib/libquadmath.so.0 (0x00007f3bd0d7d000)
        libstdc++.so.6 => /home/hv28186/.conda/envs/conda_38/lib/libstdc++.so.6 (0x00007f3bd0b69000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f3bd0867000)
        libgcc_s.so.1 => /home/hv28186/.conda/envs/conda_38/lib/libgcc_s.so.1 (0x00007f3bd084e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3bd25f2000)
        libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007f3bd0624000)

Also it seems like the SCIPOPTDIR only applies on windows?  Instead it is looking at my LD_LIBRARY_PATH to find scip.

Could there be some kind of incompatibility with cython and the version of scip I built?  
(conda_scip) bash-4.2$ ./scip --version
SCIP version 8.0.3 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: Soplex 6.0.3] [GitHash: 62fab8a2e3]
Copyright (C) 2002-2022 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)

External libraries: 
  Readline 6.2         GNU library for command line editing (gnu.org/s/readline)
  Soplex 6.0.3         Linear Programming Solver developed at Zuse Institute Berlin (soplex.zib.de) [GitHash: f900e3d0]
  CppAD 20180000.0     Algorithmic Differentiation of C++ algorithms developed by B. Bell (github.com/coin-or/CppAD)
  ZLIB 1.2.7           General purpose compression library by J. Gailly and M. Adler (zlib.net)
  AMPL/MP 4e2d45c4     AMPL .nl file reader library (github.com/ampl/mp)
  bliss 0.77           Computing Graph Automorphism Groups by T. Junttila and P. Kaski (www.tcs.hut.fi/Software/bliss/)
  TinyCThread          Small, portable implementation of the C11 threads API (tinycthread.github.io)

Compiler: gcc 5.1.0

Build options:
 ARCH=x86_64
 OSTYPE=Linux-3.10.0-1160.83.1.el7.x86_64
 COMP=GNU 5.1.0
 BUILD=Release
 DEBUGSOL=OFF
 EXPRINT=cppad
 SYM=bliss
 GMP=false
 IPOPT=false
 WORHP=OFF
 LPS=spx
 LPSCHECK=OFF
 NOBLKBUFMEM=OFF
 NOBLKMEM=OFF
 NOBUFMEM=OFF
 THREADSAFE=ON;FORCE
 READLINE=ON
 SANITIZE_ADDRESS=OFF
 SANITIZE_MEMORY=OFF
 SANITIZE_UNDEFINED=ON
 SANITIZE_THREAD=OFF
 SHARED=ON
 VERSION=8.0.3.0
 API_VERSION=104
 ZIMPL=OFF
 ZLIB=ON


When I call my script it reads the problem and creates a model just fine, but as soon as I call solveConcurrent() it dies:
(conda_scip) -bash-4.2$ python scip_runner.py test
original problem has 15851 variables (0 bin, 15851 int, 0 impl, 0 cont) and 207145 constraints
Segmentation fault (core dumped)

**Comment by lingyh** [comment]
I have the same problem.

When build with TPI=tny, I use function solveConcurrent, and then "UserWarning: SCIP was compiled without task processing interface." happen.

Did you solved it? I need help.

**Comment by lingyh** [comment]
您好，您的邮件已收到，我会尽快回复您。

> 祝好与祝成功顺利。> 凌一宏> 广州大学城外环东路132号中山大学 510006

**Comment by Joao-Dionisio** [comment]
I am closing this issue to clear the issue page, but feel free to reopen it if you're still having problems!

**Comment by lingyh** [comment]
您好，您的邮件已收到，我会尽快回复您。

> 祝好与祝成功顺利。> 凌一宏> 广州大学城外环东路132号中山大学 510006
