### ISSUE TITLE
How can I read nl file in pyscipopt

### ISSUE THREAD

**Issue by rlacjfjin** [scipopt/PySCIPOpt#672]
Hi,
I have a *.nl problem which generated from JuMP, and it is a bilinear problem.
If I use scip -f prob.nl command, it works, but when I use pyscipopt to read the problem, it can't read.
Also, I try convert the nl format to lp,mps,cip but only cip success, and can work scip -f prob.cip but don't work in pyscipopt.
And I found scip found the solution in 9s, but still process to proof the optimilaty, how can I imporve that? (I know the local objective value by ipopt solver).
Please help me, 

Thanks.
Zhe

**Comment by Joao-Dionisio** [comment]
Hello, @rlacjfjin! How are you trying to read the problem? PySCIPOpt has the [readProblem](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#a819904d60b9c60eed2112e1a9748cbd4)   method, and from my experience it works well.

Regarding the time it takes to prove optimality, as far as I know, that is usually a problem in nonlinear optimization. If you are certain that SCIP easily finds the optimal solution quickly and you don't need proof of optimality, then maybe you can stop the optimization process after a certain amount of time has passed, or when you reach a certain gap. If on the other hand, you do require optimality, then maybe take a look at Issue #619. You can tell SCIP to focus more on proving optimality with

```
from pyscipopt import Model, SCIP_PARAMEMPHASIS

scip = Model()
scip.setEmphasis(SCIP_PARAMEMPHASIS.OPTIMALITY)
```

Hope this helped!

**Comment by rlacjfjin** [comment]
> 

Hello,@Joao-Dionisio! 
I'm use readProblem: scip_model.readProblem(filename)  
but it didn't work, and error messages:
File src\pyscipopt\scip.pyx:4697, in pyscipopt.scip.Model.readProblem()

File src\pyscipopt\scip.pyx:255, in pyscipopt.scip.PY_SCIP_CALL()

Exception: SCIP: a required plugin was not found !
 And I read the prob.nl format file.(sorry to confuse, in cip format it's ok.)

In fact, I want to speed up the process, but the dual bound improvement is very slow, is there any strategy to use? 
If you are interesting this, I would send you the problem file which is nl format file.
Thanks.

**Comment by Joao-Dionisio** [comment]
@rlacjfjin Yeah, can you please send the file and your code my way? I think that way it's easier :)

Regarding speeding up the bound, if there are integer variables, usually the formulation will have a very big impact, as normally you would want a stronger relaxation to derive better bounds. But even if it's a pure NLP, sometimes the way you are formulating the nonlinearities can also be impactful. If I am not mistaken, I think that something like $\frac{1}{1-x} \leq b$ should be formulated with an auxiliary variable $y$ such that $\frac{1}{y} \leq b$. I am unsure why this is the case, and even if this is true, but similar things do exist.

As I said, if you require proof of optimality, then changing the SCIP empashis to optimality may help in that regard.

**Comment by Joao-Dionisio** [comment]
Hey @rlacjfjin, I would prefer not to send my email here, sorry... Can't you upload the file to this page? If not, something like wetransfer or pastebin is always a possibility as well!

**Comment by rlacjfjin** [comment]
[test prob.zip](https://github.com/scipopt/PySCIPOpt/files/11287598/test.prob.zip)
Hello,@Joao-Dionisio! This is problem file, and I think three format of problem(lp,nl,cip) is same. You can try to solve it. thanks.

**Comment by rlacjfjin** [comment]
But I use scip command:
  scip -f .\prob_47.nl   It's work well;
![image](https://user-images.githubusercontent.com/24473063/233516400-5f27947a-b998-44f4-b382-d9183f3e4a1d.png)

**Comment by Joao-Dionisio** [comment]
Good morning, @rlacjfjin. Maybe PySCIPOpt and SCIP are searching for the files in different places? Do you only have one SCIP installed, and are they installed globally?

I don't know, but I think your issue can be solved simply by appending the global path to the files. Something like this:

```
from pyscipopt import Model

def run(file_name):  
  m = Model()
  file = "/your/global/path" + file_name
  m.readProb(file)
  m.optimize()
```
And then adding the sys stuff. That way, calling the file with the option ```prob47.nl``` should work.

**Comment by rlacjfjin** [comment]
Hi,@Joao-Dionisio!
May be it is possible that there are some plugins that I did not install properly. (I can't read nl file but I can read lp file)
Anyway, I can solve the problem, but I still can't find a optimal solution in several times(1 hours....), could you help me how can I tuning the parameters?

**Comment by Joao-Dionisio** [comment]
@rlacjfjin, without knowing more details about the model, it's difficult to suggest these things. I can't promise that this will help, but maybe try this out:

```
from pyscipopt import Model, SCIP_PARAMEMPHASIS

m = Model()
m.setEmphasis(SCIP_PARAMEMPHASIS.OPTIMALITY)
```
It tells SCIP to focus on proving optimality. Whenever I used it, my models ended up with slower convergence, but it may be different in this case. 

As I said, difficulty in proving optimality can sometimes be due to the model not having a good continuous relaxation. Perhaps looking at the modeling may be helpful. 

I just remembered an aditional parameter that may be helpful in your case. Assuming that the model has a convex continuous relaxation and SCIP is not detecting it, you can tell that explicitly to SCIP, possibly facilitating the proof of optimality:

```
m.setParam(constraints/nonlinear/assumeconvex, True)
```

**Comment by Joao-Dionisio** [comment]
It seems that the original issue has been fixed, but feel free to reopen it if you are still having problems!
