### ISSUE TITLE
Times of feasible solutions.

### ISSUE THREAD

**Issue by brunompacheco** [scipopt/PySCIPOpt#673]
Is there any way to access the time that a given solution was found through PySCIPOpt?

It seems fairly straightforward to do it using `SCIPsolGetTime` or `SCIPgetSolTime`, but neither seem to be in `scip.pxd`. I wonder if there is any way around this.

My end goal is to compute primal and dual integrals, so any tips on doing this using the current state of PySCIPOpt is valuable.

**Comment by Joao-Dionisio** [comment]
Olá, @brunompacheco :)

As far as I know, you are not able to do it directly yes, but given that it's so easy to do it with SCIP, I imagine it's very easy to add it to PySCIPOpt as well. I suppose something like

```
def getSolTime(self, Solution sol):
    """retrieve time to find solution
    
    :param Solution sol: solution
    """
    return SCIPgetSolTime(self._scip)
```
in the appropriate place might work. Mind you, I've never actually pushed anything to PySCIPOpt, so this might be completely wrong, someone else may be able to help out more.

**Comment by brunompacheco** [comment]
I just tried doing it myself: _https://github.com/brunompacheco/PySCIPOpt/commit/1d846eec22988e709096fe5dd526bc67ab0e3c0a_

I haven't run the tests, but given that it is such a simple change, I guess it could be easily merged.

**Comment by Joao-Dionisio** [comment]
I don't have permissions for accepting PRs, but thank you for taking the initiative! I'm sure you'll get feedback soon.
