### ISSUE TITLE
Get constraint expression

### ISSUE THREAD

**Issue by rlacjfjin** [scipopt/PySCIPOpt#675]
Hi,
How can I get constraint expression in pyscipopt?
My code is:

import pyscipopt
model = pyscipopt.Model()
x = model.addVar(lb=0, ub=10)
y = model.addVar(lb=0, ub=20)
c = model.addCons(x + y <= 30)

and I can get the LHS with constraint c:

model.getLhs(c),  also can get RHS:model.getRhs(c)

But I don't know how can I get the expression of constraint( with or without constant term)...
Is it possible to get? In my case , I want  to get "x+y"  or "x+y<=30".

Thanks.

Zhe

**Comment by Joao-Dionisio** [comment]
Hello, @rlacjfjin! I could not find a way to do what you are asking for, not even in SCIP. But there must be a way to do it, with some more difficulty. 

It does not really help, but if you try to print the constraint directly with ```print(x+y <= 30)``` it yields ```ExprCons(Expr({Term(x1): 1.0, Term(x2): 1.0}), None, 30.0)```. I suspect that even if you manage to print directly from the constraint, the output will look something like this.

**Comment by rlacjfjin** [comment]
Thanks. 
Finally, I read again model file and get constraints line-by-line. 😂
