### ISSUE TITLE
Strange behavior of PyscipOpt

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#680]
Dear support team,

I am trying to solve a problem by testing some of SCIP's internal options in order to compare the solving process. The strange thing is that when I set the following options the solving process seems to get stuck and restart again and the B&B tree leads to a sub-optimal solution.
```
m.setPresolve(SCIP_PARAMSETTING.AGGRESSIVE)
m.setHeuristics(SCIP_PARAMSETTING.AGGRESSIVE)
m.setSeparating(SCIP_PARAMSETTING.AGGRESSIVE)
```
Actually, the correct solution would be 17 while the solver is showing 18.

```
Restart triggered after 50 consecutive estimations that the remaining tree will be large
(run 1, node 1049) performing user restart

(restart) converted 20 cuts from the global cut pool into linear constraints

presolving:
(round 1, fast)       34 del vars, 155 del conss, 0 add conss, 0 chg bounds, 1 chg sides, 291 chg coeffs, 0 upgd conss, 0 impls, 1598 clqs
(round 2, exhaustive) 34 del vars, 182 del conss, 0 add conss, 0 chg bounds, 16 chg sides, 291 chg coeffs, 0 upgd conss, 0 impls, 1752 clqs
(round 3, exhaustive) 34 del vars, 182 del conss, 0 add conss, 0 chg bounds, 16 chg sides, 291 chg coeffs, 114 upgd conss, 0 impls, 1761 clqs
(round 4, fast)       34 del vars, 185 del conss, 0 add conss, 0 chg bounds, 16 chg sides, 291 chg coeffs, 114 upgd conss, 0 impls, 1762 clqs
(round 5, exhaustive) 34 del vars, 438 del conss, 0 add conss, 0 chg bounds, 16 chg sides, 342 chg coeffs, 114 upgd conss, 0 impls, 1810 clqs
(round 6, exhaustive) 34 del vars, 439 del conss, 0 add conss, 0 chg bounds, 16 chg sides, 942 chg coeffs, 114 upgd conss, 0 impls, 1828 clqs
presolving (7 rounds: 7 fast, 5 medium, 5 exhaustive):
 34 deleted vars, 439 deleted constraints, 0 added constraints, 0 tightened bounds, 0 added holes, 16 changed sides, 945 changed coefficients
 0 implications, 1837 cliques
presolved problem has 840 variables (840 bin, 0 int, 0 impl, 0 cont) and 2377 constraints
     35 constraints of type <knapsack>
    603 constraints of type <setppc>
     10 constraints of type <linear>
   1729 constraints of type <logicor>
transformed objective value is always integral (scale: 1)
Presolving Time: 1.09
transformed 14/16 original solutions to the transformed problem space

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
 46.2s|     1 |     0 | 59656 |     - |    86M |   0 | 840 |2377 | 636 |   0 |  0 |2166 |2197 | 1.690000e+01 | 1.800000e+01 |   6.51%| unknown
Computing relative interior point (time limit: 1e+20, iter limit: 596560) ...
 46.8s|     1 |     0 | 59659 |     - |    86M |   0 | 840 |2377 | 636 |   0 |  1 |2166 |2197 | 1.800000e+01 | 1.800000e+01 |   0.00%| unknown
 46.8s|     1 |     0 | 59659 |     - |    86M |   0 | 840 |2377 | 636 |   0 |  1 |2166 |2197 | 1.800000e+01 | 1.800000e+01 |   0.00%| unknown

```
I think the first line in the above snippet of the log shows something unusual. I should note that the model without using any options can turn out the optimal solution. Also, I test the same problem with the console runner and the run time is so decreasing by using these options as I expected it to be with the correct optimal solution. Please, see an MRE [here](https://colab.research.google.com/drive/1Z4TrjnpYulPO8Up4hYQrz9A4kYSbdfGY?usp=sharing).

Another issue that may cause this strange behavior is to install conda. before that I easily install and run conda by the following code:

```
!pip install conda
!pip show conda
```
While nowadays it produces an error as:
```
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement conda (from versions: 3.0.6, 3.5.0, 3.7.0, 3.17.0, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.7, 4.0.8, 4.0.9, 4.1.2, 4.1.6, 4.2.6, 4.2.7, 4.3.13, 4.3.16)
ERROR: No matching distribution found for conda
```
B.T.W I am going ahead to install condacolab and run the problem.

```
!pip install -q condacolab
import condacolab
condacolab.install()
```

I was wondering if, how can I fix that?

Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
Hello again, @abb-omidi :)

I managed to reproduce your issue. I think the suboptimal solution is given by the aggressive heuristics parameter. Using aggressive presolving and separating, the model arrives at the solution of 17, though it takes much longer. I don't think we can help much in this regard, it may be better to talk to SCIP directly. Try using their mailing list or Stack Exchange, they tend to respond relatively quickly! Let me know how this one goes :)

Regarding the conda installation, that really seems to be something to do with conda and google colab, I wouldn't know if it affects SCIP...

**Comment by abb-omidi** [comment]
@Joao-Dionisio,

Thank you so much for your informative comments. I will ask the same question on the SCIP host.

Regards
Abbas
