### ISSUE TITLE
Defining precedence constraint in PySCIPOPT

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#681]
Dear support team,

I am working on a scheduling problem and in one of the constraints, it needs to define a precedence relation between tasks. Suppose, there are | J | tasks that should be processed on the | M | machines. Indices j and k represent task elements. The constraint is something like:

`start[j] + p[j] <= start[k]          forall (j,k) in Precedence `

What I have tried is as follows, but is seems the constraint cannot be applied in the model:

```
processingTimes = [...]
Precedence = [[1, 4], [4, 8], [6, 11],...]
J = range(len(processingTimes))

for (j, k) in Precedence:
      conss_prec.append(m.addCons(start[j] + processingTimes[j] <= start[k]))
```

I was wondering if, where I am doing wrong and how can I fix that?

Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
Hello, @abb-omidi! What issue are you having? From the modeling side, everything looks good. I created a minimal working example, and everything runs as expected.

![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/a4755467-bd67-47f3-8312-f9ea0ee3b87f)

One thing that may cause problems is the indices. Your jobs seem to start at 1, but then you don't check processingTimes[j-1].

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Many thanks for your prompt response. I am not sure understand what you pointed out in the last line, but as I have tested different formulations these modeling issues may cause some strange things. Also, the model has some other constraints. I was wondering if, you could have a look at this [MRE](https://colab.research.google.com/drive/143j_cQPNtoittPW05AAnBgXjjnskYBIL?usp=sharing), editable, and let me know, how can I fix that.

Also, I have seen you have used some Mathjax notation in some comments, but I cannot find any related document on how one can write that. Would you please, is there any related document?

Regards
Abbas

**Comment by abb-omidi** [comment]
@Joao-Dionisio,

I have just edited the model data for simplicity tracking issues. 

Regards
Abbas

**Comment by Joao-Dionisio** [comment]
Ah, I think I know what is wrong regarding the release constraints, and it's indeed a problem with the indices. You are doing this:

``` 
J = range(len(processingTimes)) # = [0,1,...,len(processingTimes)-1]

for j in J:
  conss_release.append(m.addCons(start[j] >= max(1, release_Times[j-1])))
```

So, for task 0, you are saying that ``` start[0] >= max(1, release_Times[-1]) ```, which is 51. This is not what you want, right? I think you need to replace all ```release_Times[j-1]``` with ```release_Times[j]```, and then change the Precedence array accordingly. 


This seems to be a variant of the minimum makespan scheduling problem, whose linear relaxation is a solution to the integer problem as well. Can this be true for your variant as well? Even if it's not true in general, it can be true for this specific instance. 

Regarding Mathjax, I simply use the LaTeX commands. Some of them work, some others don't, but you just need to enclose the expression with a single dollar sign on each side for in-line math, like this: $x^2$. Or with two dollar signs on each side for the expression to have its own spacing, like this:

$$ x ^2 $$

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Thanks for investigating the problem. I changed the data type to better manage the inputs of the models. Now, some things work better, but the issue on the precedence relation is remaining. Even with removing the parameter, just already for testing, the constraint does not work. Unfortunately, till this issue would be resolved I cannot get an LP format to make better sense of which part caused this strange behavior. 

> This seems to be a variant of the minimum makespan scheduling problem, whose linear relaxation is a solution to the integer problem as well. Can this be true for your variant as well? Even if it's not true in general, it can be true for this specific instance.

No. In my case, this is not happening. In the following, you can see the SCIP log that solved the same problem with the Pyomo package. 
```
SCIP version 8.0.3 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: Soplex 6.0.3] [GitHash: 62fab8a2e3]
Copyright (C) 2002-2022 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)

External libraries: 
  Soplex 6.0.3         Linear Programming Solver developed at Zuse Institute Berlin (soplex.zib.de) [GitHash: f900e3d0]
  CppAD 20180000.0     Algorithmic Differentiation of C++ algorithms developed by B. Bell (github.com/coin-or/CppAD)
  ZLIB 1.2.13          General purpose compression library by J. Gailly and M. Adler (zlib.net)
  GMP 6.2.1            GNU Multiple Precision Arithmetic Library developed by T. Granlund (gmplib.org)
  ZIMPL 3.5.3          Zuse Institute Mathematical Programming Language developed by T. Koch (zimpl.zib.de)
  AMPL/MP 4e2d45c4     AMPL .nl file reader library (github.com/ampl/mp)
  PaPILO 2.1.2         parallel presolve for integer and linear optimization (github.com/scipopt/papilo) [GitHash: 2fe2543]
  bliss 0.77           Computing Graph Automorphism Groups by T. Junttila and P. Kaski ([www.tcs.hut.fi/Software/bliss/](http://www.tcs.hut.fi/Software/bliss/))
  Ipopt 3.14.12        Interior Point Optimizer developed by A. Waechter et.al. (github.com/coin-or/Ipopt)

user parameter file <scip.set> not found - using default parameters
read problem </tmp/tmpelwyqwg_.pyomo.nl>
============

original problem has 96 variables (85 bin, 0 int, 0 impl, 11 cont) and 394 constraints

solve problem
=============

presolving:
(round 1, fast)       0 del vars, 10 del conss, 0 add conss, 15 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 10 clqs
(round 2, fast)       0 del vars, 10 del conss, 0 add conss, 16 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 10 clqs
   (0.0s) running MILP presolver
   (0.0s) MILP presolver (2 rounds): 0 aggregations, 0 fixings, 11 bound changes
(round 3, medium)     0 del vars, 10 del conss, 0 add conss, 27 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 10 clqs
(round 4, exhaustive) 0 del vars, 10 del conss, 0 add conss, 27 chg bounds, 0 chg sides, 0 chg coeffs, 10 upgd conss, 0 impls, 10 clqs
   (0.0s) probing: 51/85 (60.0%) - 0 fixings, 0 aggregations, 0 implications, 0 bound changes
   (0.0s) probing aborted: 50/50 successive totally useless probings
   (0.0s) symmetry computation started: requiring (bin +, int -, cont +), (fixed: bin -, int +, cont -)
   (0.0s) symmetry computation finished: 3 generators found (max: 1500, log10 of symmetry group size: 1.4)
(round 5, exhaustive) 7 del vars, 10 del conss, 1 add conss, 27 chg bounds, 0 chg sides, 0 chg coeffs, 10 upgd conss, 0 impls, 9 clqs
(round 6, fast)       9 del vars, 12 del conss, 1 add conss, 27 chg bounds, 0 chg sides, 0 chg coeffs, 10 upgd conss, 0 impls, 8 clqs
(round 7, exhaustive) 9 del vars, 20 del conss, 1 add conss, 27 chg bounds, 6 chg sides, 0 chg coeffs, 10 upgd conss, 0 impls, 8 clqs
   (0.0s) probing: 56/85 (65.9%) - 0 fixings, 0 aggregations, 0 implications, 0 bound changes
   (0.0s) probing aborted: 50/50 successive totally useless probings
presolving (8 rounds: 8 fast, 5 medium, 4 exhaustive):
 9 deleted vars, 20 deleted constraints, 1 added constraints, 27 tightened bounds, 0 added holes, 6 changed sides, 0 changed coefficients
 0 implications, 8 cliques
presolved problem has 88 variables (77 bin, 0 int, 0 impl, 11 cont) and 375 constraints
      8 constraints of type <setppc>
    366 constraints of type <linear>
      1 constraints of type <orbitope>
Presolving Time: 0.03

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
p 0.0s|     1 |     0 |    14 |     - |shiftand|   0 |  88 | 377 | 374 |   0 |  0 |   2 |   0 | 8.200000e+01 | 1.030000e+02 |  25.61%| unknown
  0.0s|     1 |     0 |    34 |     - |  4057k |   0 |  88 | 285 | 374 |   0 |  0 |   2 |   0 | 8.200000e+01 | 1.030000e+02 |  25.61%| unknown
  0.0s|     1 |     0 |    44 |     - |  4220k |   0 |  88 | 285 | 381 |   7 |  1 |   2 |   0 | 8.200000e+01 | 1.030000e+02 |  25.61%| unknown
r 0.0s|     1 |     0 |    44 |     - |shifting|   0 |  88 | 285 | 381 |   7 |  1 |   2 |   0 | 8.200000e+01 | 8.200000e+01 |   0.00%| unknown
  0.0s|     1 |     0 |    44 |     - |  4224k |   0 |  88 | 285 | 381 |   7 |  1 |   2 |   0 | 8.200000e+01 | 8.200000e+01 |   0.00%| unknown

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 0.04
Solving Nodes      : 1
Primal Bound       : +8.20000000000000e+01 (2 solutions)
Dual Bound         : +8.20000000000000e+01
Gap                : 0.00 %

```
At the moment I am not sure how can I fix this, but let me check and back to you.

Also, for the Mathjax, thanks once again. Now, it works. :)

Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
@abb-omidi, I think I fixed an error in your code (the keys of your dictionary were "1", "2",... instead of 1,2,....). The model runs now. 

There doesn't seem to be a problem with the solving process, however. The solution satisfies all the constraints, from a quick look. 

If you have any more problems with PySCIPOpt, please let me know!

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Ah, you are absolutely right. I totally forget to change the dictionary keys. Many thanks for mentioning and correcting that. I should check the model with the whole data and investigate how it works. I am still full of doubt about how the solver performs the problems without sending that in the B&B tree(!!!). As you can see in the log file for Pyomo, it seems the behavior of the solver is totally different VS when one uses the solver API directly. I will check that and back to you if I have any issues.

Thanks once again.
Sincerely yours
Abbas

**Comment by Joao-Dionisio** [comment]
Hey, @abb-omidi! 

The optimal solution is also different. Using Pyomo it's 82, using PySCIPOPt normally it's 79, if I remember correctly. Nevertheless, the constraints are being satisfied with PySCIPOpt, so it doesn't seem to be a problem on our end. 

Can I close this issue and then you open another one if you have other problems?

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Many thanks for your prompt response. I eventually could solve the problems issues. Actually, the strange behavior of the solver back to the last constraint of the model, and with some tweaking, the solver process goes very well as I expected. I confirm that everything works fine for now. 

Thanks for your time and hints.
Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
I am very happy to hear it, @abb-omidi!

Feel free to create other issues when you're having problems :)

Best,
João
