### ISSUE TITLE
Optimizer stuck in loop

### ISSUE THREAD

**Issue by ICYosoro** [scipopt/PySCIPOpt#682]
My program is using the optimizer's output to calculate the next round optimizer's input param. So I called the optimizer in a loop. However, in some situation, the optimizer just got stuck forever !!
Then I use the last input param in the same optimizer model straight-forward without loop. This time I got the optimal result, immediately!
![image](https://github.com/scipopt/PySCIPOpt/assets/41278239/bf3c1c5b-611a-42a1-a157-a7e9a5aab6a3)
![image](https://github.com/scipopt/PySCIPOpt/assets/41278239/88b44d49-4946-4d73-b2aa-c2e0f232b0f1)
I use conda install the v4.3.0 version of pyscipopt with python 3.10.11 on windows 11.
------------------------------------------------------------------------------------------------------------------------------------------
I tried 3.5.0 version of pyscipopt. It works well with my code !!!

**Comment by Joao-Dionisio** [comment]
Hello, @ICYosoro! To see if I understood your problem correctly: You are trying to solve variations of the same problem in a loop, using the result of one iteration in the next one. However, in a specific iteration, SCIP freezes for some reason. This happens with pyscipopt v4.3.0, but with pyscipopt 3.5.0 it works. Is this it?

Can you please share a minimal reproducible example of your problem, so that I can try it out?

**Comment by ICYosoro** [comment]
Hello, @Joao-Dionisio you got me right! 
Here is the code.
[reproducing_freeze.zip](https://github.com/scipopt/PySCIPOpt/files/11539983/reproducing_freeze.zip)
I am a beginner for PySCIPOpt. I am glad that you could help me out if my usage is wrong. >_<

**Comment by Joao-Dionisio** [comment]
Hello, @ICYosoro!

No worries :) Unfortunately, I was unable to reproduce your problem... I even created another conda environment with your specifications, but running the ```it_freeze_here.py``` file, it runs until it says ```Loop end due to addition < epsilon```.

![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/850a3030-102b-4025-8911-6e2f64d8df0b)

Your instructions for installing pyscipopt with anaconda are different from the ones in here. Can that be it? The only difference I can see is that I'm running Linux (you appear to be using Windows), and my conda environment is different. Here:

```
name: scipopt_test
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ampl-mp=3.1.0=h2cc385e_1006
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - cppad=20230000.0=hcb278e6_0
  - gmp=6.2.1=h58526e2_0
  - icu=72.1=hcb278e6_0
  - ipopt=3.14.12=hf9e1ecf_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=16_linux64_openblas
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.38.1=h0b41bf4_0
  - libxml2=2.10.4=hfdac1af_0
  - libzlib=1.2.13=h166bdaf_4
  - metis=5.1.0=h58526e2_1006
  - mumps-include=5.2.1=ha770c72_11
  - mumps-seq=5.2.1=h2104b81_11
  - ncurses=6.3=h27087fc_1
  - openssl=3.1.0=hd590300_3
  - pip=23.1.2=pyhd8ed1ab_0
  - pyscipopt=4.3.0=py310heca2aa9_0
  - python=3.10.11=he550d4f_0_cpython
  - python_abi=3.10=3_cp310
  - readline=8.2=h8228510_1
  - scip=8.0.3=h4a32fe0_2
  - scotch=6.0.9=hb2e6521_2
  - setuptools=67.7.2=pyhd8ed1ab_0
  - tbb=2021.9.0=hf52228f_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2023c=h71feb2d_0
  - unixodbc=2.3.10=h583eb01_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
prefix: /home/dionisio/anaconda3/envs/scipopt_test
```
