### ISSUE TITLE
Add binding to chgCoefPos() 

### ISSUE THREAD

**Issue by FranekStark** [scipopt/PySCIPOpt#683]
SCIPopt C++ API offers the possibility to change a coefficient of a linear constraint at a given position via https://scipopt.org/doc-8.0.3/html/cons__linear_8c.php#a498394b8ed78671c6db66d7b621f9d8b
I think, it'd be great to see this also binded to the python interface, as it would allow me to change constraints very fast.
I'm using SCIP for an MPC project, during each control step I have to linearize the system and therefore need to change the dynamic constraints.

**Comment by Joao-Dionisio** [comment]
Good morning, @FranekStark! You are right, unfortunately, that is still not possible to do with PySCIPOpt. Do you think you can create a PR to add this functionality? It would be very useful!

In the meantime, there is [chgLhs](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#a67467e250c9007e702e2a8c8be141bbf)... It's not really what you wanted, but it might help.

**Comment by FranekStark** [comment]
Hi @Joao-Dionisio, https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#a67467e250c9007e702e2a8c8be141bbf I already use heavily ;)
For now I just delete and re add the constraints, but yeah as soon as it turns out that SCIP is doing a great job I need the functionality and then of course I will submit a Pull request.

**Comment by FranekStark** [comment]
@Joao-Dionisio just opened https://github.com/scipopt/PySCIPOpt/pull/686
