### ISSUE TITLE
Trouble getting dual values with getDualsolLinear

### ISSUE THREAD

**Issue by brmanuel** [scipopt/PySCIPOpt#684]
Using PySCIPOpt 4.3.0 I get unexpected results when using getDualsolLinear. 

My understanding is
- calling `model.getDualsolLinear(c)` after having optimized `model` should give me the optimal value of the dual variable corresponding to the constraint `c`. I'm aware of the limitations and have disabled presolve, heuristics and propagation. Moreover, my problem does not contain any bound constraints.
- In particular, `getDualsolLinear` should achieve the same thing as calling `getDualSolVal`. Looking at their docstrings they sound similar enough: `gets the dual solution of the linear constraint in the current LP` vs. `returns dual solution value of a constraint`

I test these hypotheses by solving an LP and its dual (derived manually) both with PySCIPOpt, then comparing the output of getDualsolLinear and getDualSolVal with the solution:
```python
primal = Model()
x = primal.addVar("x", lb=0)
y = primal.addVar("y", lb=0)
c1 = primal.addCons(x + 2*y <= 21)
c2 = primal.addCons(2*x + y <= 24)
primal.setObjective(x+y, sense="maximize")
# to get duals, we need to switch off some features of SCIP!
# c.f. https://github.com/scipopt/PySCIPOpt/issues/136
primal.setPresolve(SCIP_PARAMSETTING.OFF)
primal.setHeuristics(SCIP_PARAMSETTING.OFF)
primal.disablePropagation()
primal.optimize()

dual = Model()
a = dual.addVar("a", lb=0)
b = dual.addVar("b", lb=0)
d1 = dual.addCons(a + 2*b >= 1)
d2 = dual.addCons(2*a + b >= 1)
dual.setObjective(21*a + 24*b, sense="minimize")
dual.setPresolve(SCIP_PARAMSETTING.OFF)
dual.setHeuristics(SCIP_PARAMSETTING.OFF)
dual.disablePropagation()
dual.optimize()

primal_sol = primal.getBestSol()
dual_sol = dual.getBestSol()

print("solution: x* =", primal_sol[x], ", y* =", primal_sol[y], ", a* =", dual_sol[a], ", b* =", dual_sol[b])
print("getDualSolVal: a* =", primal.getDualSolVal(c1), ", b* =", primal.getDualSolVal(c2))
print("getDualsolLinear: a* =", primal.getDualsolLinear(c1), ", b* =", primal.getDualsolLinear(c2))
```
Output:
```bash
solution: x* = 9.0 , y* = 6.0 , a* = 0.3333333333333333 , b* = 0.33333333333333337
getDualSolVal: a* = 0.3333333333333333 , b* = 0.33333333333333337
getDualsolLinear: a* = -0.3333333333333333 , b* = -0.33333333333333337
```

Apparently, my understanding is wrong. My questions are:
- Is this a bug in getDualsolLinear or is my understanding wrong?
- What exactly does getDualsolLinear return and how is it different from getDualSolVal?

**Comment by Joao-Dionisio** [comment]
Hello, @brmanuel! Thank you for the detailed issue! 

When you encountered this issue, has it always happened that one was $-1$ times the other? Looking at the SCIP documentation, the only difference I can find is that it seems that ```getDualSolLinear``` doesn't check whether it's a minimization or maximization problem, whereas ```getDualSolVal``` does (it multiplies the answer by $-1$). This seems to be the problem, since if I change the objective sense in your example (and adjust the inequalities), everything adds up. The solvers tend to assume that a linear problem is a minimization problem by default.

If this is indeed the issue, do you think you can send a message to the guys at SCIP? It doesn't seem to be a PySCIPOpt issue. Either way, thank you!

**Comment by brmanuel** [comment]
Hi @Joao-Dionisio 
Thanks a lot for your answer. You're explanation makes sense to me. I think, all instances I looked at had the inverted sign, so this seems plausible. Trying to recreate the issue for SCIP with their C-API yields a different (wrong) dual value. But this is probably due to me using the C-API incorrectly. Anyway, I'm hoping their answer will clear things up for me.

**Comment by mmghannam** [comment]
Hi @brmanuel, 

As a follow up to the answer on the C-API repository issue. You are probably wondering why would `getDualsolLinear` return different results in the different APIs. So, in the C-API calling this on original constraint (not the transformed ones) would return zeros since the original constraints are not part of the problem (not active). But it turns out that the same function in the python API retrieves the corresponding transformed constraint before calling the same function in C. and as to why it is a negative value it is probably because the original problem is a maximization problem, and the transformed one is always minimization that's why the sign is flipped. This complexity is hidden by `getDualSolVal` as it flips the sign back. 

Here's the implementation of `SCIPgetDualSolVal` if you want to look in further https://github.com/scipopt/scip/blob/ed7ea0f660d148e58d4ca02f87b226eb7d3f1ba5/src/scip/scip_sol.c#L1956

**Comment by 4YHa** [comment]
Hi there,I'm using C++ to try to solve this, and I've tried both of the above methods, but I'm getting a result of 0. What's going on here?
![问题](https://github.com/scipopt/PySCIPOpt/assets/140891835/7c3cfc63-05df-4fa2-9d47-5ae9425fdf5f)
![结果](https://github.com/scipopt/PySCIPOpt/assets/140891835/f26645d4-9a1c-4a85-b32f-a6f76dfc7265)

**Comment by Joao-Dionisio** [comment]
Hello, @4YHa! Sorry about this, can you please show the constraints you're using?

**Comment by 4YHa** [comment]
Hello,@Joao-Dionisio !
I'm working on a linear programming problem, which you can see in Figure.The full code is copied below.I'm a bit confused about why the objective function of the dyadic problem is 44 when the value of the dyadic variable is 0. Could you let me know if there are any prerequisites for using the methods SCIPgetDualSolVal() and SCIPgetDualsolLinear? Do they require the same number of variables and the same number of constraints?
![具体问题](https://github.com/user-attachments/assets/1fdd8bb7-0aef-43ac-94c3-7ac8417ab560)
#include "scip/scip.h"
#include "scip/scipdefplugins.h"
#include <iostream>
int main() {
    // 初始化SCIP环境
    SCIP* scip = nullptr;
    SCIP_CALL(SCIPcreate(&scip));
    // 加载默认插件，包括LP求解器
    SCIP_CALL(SCIPincludeDefaultPlugins(scip));
    // 创建空的SCIP模型
    SCIP_CALL(SCIPcreateProbBasic(scip, "LinearProgrammingExample"));
    SCIPsetObjsense(scip, SCIP_OBJSENSE_MINIMIZE);
    // 创建变量 y1 和 y2
    SCIP_VAR* y1 = nullptr;
    SCIP_VAR* y2 = nullptr;
    SCIP_CALL(SCIPcreateVarBasic(scip, &y1, "y1", 0.0, SCIPinfinity(scip), 8.0, SCIP_VARTYPE_CONTINUOUS));
    SCIP_CALL(SCIPcreateVarBasic(scip, &y2, "y2", 0.0, SCIPinfinity(scip), 12.0, SCIP_VARTYPE_CONTINUOUS));
    // 将变量添加到模型中
    SCIP_CALL(SCIPaddVar(scip, y1));
    SCIP_CALL(SCIPaddVar(scip, y2));
    // 创建约束 2y1 + 2y2 >= 2
    SCIP_CONS* cons1 = nullptr;
    SCIP_CALL(SCIPcreateConsBasicLinear(scip, &cons1, "cons1", 0, nullptr, nullptr, 2.0, SCIPinfinity(scip)));
    SCIP_CALL(SCIPaddCoefLinear(scip, cons1, y1, 2.0));
    SCIP_CALL(SCIPaddCoefLinear(scip, cons1, y2, 2.0));
    SCIP_CALL(SCIPaddCons(scip, cons1));
    // 创建约束 2y2 >= 1
    SCIP_CONS* cons2 = nullptr;
    SCIP_CALL(SCIPcreateConsBasicLinear(scip, &cons2, "cons2", 0, nullptr, nullptr, 1.0, SCIPinfinity(scip)));
    SCIP_CALL(SCIPaddCoefLinear(scip, cons2, y2, 2.0));
    SCIP_CALL(SCIPaddCons(scip, cons2));
    // 创建约束 y1 + y2 >= 5
    SCIP_CONS* cons3 = nullptr;
    SCIP_CALL(SCIPcreateConsBasicLinear(scip, &cons3, "cons3", 0, nullptr, nullptr, 5.0, SCIPinfinity(scip)));
    SCIP_CALL(SCIPaddCoefLinear(scip, cons3, y1, 1.0));
    SCIP_CALL(SCIPaddCoefLinear(scip, cons3, y2, 1.0));
    SCIP_CALL(SCIPaddCons(scip, cons3));
    // 创建约束 y1 + 2y2 >= 6
    SCIP_CONS* cons4 = nullptr;
    SCIP_CALL(SCIPcreateConsBasicLinear(scip, &cons4, "cons4", 0, nullptr, nullptr, 6.0, SCIPinfinity(scip)));
    SCIP_CALL(SCIPaddCoefLinear(scip, cons4, y1, 1.0));
    SCIP_CALL(SCIPaddCoefLinear(scip, cons4, y2, 2.0));
    SCIP_CALL(SCIPaddCons(scip, cons4));
    // 求解模型
    SCIP_CALL(SCIPsolve(scip));
    // 获取并打印最优解
    SCIP_SOL* sol = SCIPgetBestSol(scip);
    std::cout << "Optimal value: " << SCIPgetSolOrigObj(scip, sol) << std::endl;
    if (sol != nullptr) {
        std::cout << "Optimal solution found:" << std::endl;
        std::cout << "y1 = " << SCIPgetSolVal(scip, sol, y1) << std::endl;
        std::cout << "y2 = " << SCIPgetSolVal(scip, sol, y2) << std::endl;
        std::cout << "SCIPgetDualSolVal:Dual value:" << SCIPgetDualbound(scip) << std::endl;
        double c1;
        double c2;
        double c3;
        double c4;
        SCIPgetDualSolVal(scip, cons1, &c1, NULL);
        SCIPgetDualSolVal(scip, cons2, &c2, NULL);
        SCIPgetDualSolVal(scip, cons3, &c3, NULL);
        SCIPgetDualSolVal(scip, cons4, &c4, NULL);
        std::cout << "******************Dual values by SCIPgetDualSolVal:***********************" << std::endl;
        std::cout << "cons1 dual value = " << c1 << std::endl;
        std::cout << "cons2 dual value = " << c2 << std::endl;
        std::cout << "cons3 dual value = " << c3 << std::endl;
        std::cout << "cons4 dual value = " << c4 << std::endl;
        // Get dual variable (shadow price) for the constraints
        std::cout << "******************Dual values by SCIPgetDualsolLinear:***********************" << std::endl;
        std::cout << "Dual variable value for cons1: " << SCIPgetDualsolLinear(scip, cons1) << std::endl;
        std::cout << "Dual variable value for cons2: " << SCIPgetDualsolLinear(scip, cons2) << std::endl;
        std::cout << "Dual variable value for cons3: " << SCIPgetDualsolLinear(scip, cons3) << std::endl;
        std::cout << "Dual variable value for cons4: " << SCIPgetDualsolLinear(scip, cons4) << std::endl;
    }
    else {
        std::cout << "No optimal solution found." << std::endl;
    }
    
    // 释放资源
    SCIP_CALL(SCIPreleaseCons(scip, &cons1));
    SCIP_CALL(SCIPreleaseCons(scip, &cons2));
    SCIP_CALL(SCIPreleaseCons(scip, &cons3));
    SCIP_CALL(SCIPreleaseCons(scip, &cons4));
    SCIP_CALL(SCIPreleaseVar(scip, &y1));
    SCIP_CALL(SCIPreleaseVar(scip, &y2));
    SCIP_CALL(SCIPfree(&scip));
    return 0;
}

**Comment by leoneifler** [comment]
You need to disable presolving, most likely that is the issue. `SCIP_CALL( SCIPsetPresolving(scip, SCIP_PARAMSETTING_OFF, TRUE) );` should do the trick.

**Comment by 4YHa** [comment]
Hi, @leoneifler 
Thank you very much for your answer here !
This clears up my confusion.
