### ISSUE TITLE
[WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by namogg** [scipopt/PySCIPOpt#696]
I am getting this error on this line of code when i tried to debug. 
i am using SCIP 8.0.3, pyscipopt 4.3.2 and python 3.8.5
model.getLPRowsData()
Please help me with this one. I really appreciate your help

**Comment by namogg** [comment]
This is my simple model
# Create a SCIP model
model = scip.Model()

# Add variables to the model
x = model.addVar("x", vtype="INTEGER")
y = model.addVar("y", vtype="CONTINUOUS")

# Set objective function
model.setObjective(2 * x + y)

# Add constraints
model.addCons(x + 2 * y <= 10, "constraint1")
model.addCons(3 * x - y >= 5, "constraint2")

The error appear at 
model.getLPRowsData().
[WinError 10054] An existing connection was forcibly closed by the remote host 

Other function appear work perfectly, except for this one

**Comment by Joao-Dionisio** [comment]
Good evening, @namogg! Can you please share the code that is producing this issue?

But as a heads up, the method can only be called during the solving stage (see [here](https://www.scipopt.org/doc/html/group__PublicLPMethods.php#ga488366019cc364f8cb723f7a3e6f3c7b)). 

I also don't know whether the method works with integer variables, if it looks at the linear relaxation or just returns an error.

**Comment by namogg** [comment]
The code is just simple as this, i have change integer variables to continous but didnt work so far.
# Create a SCIP model
model = scip.Model()

# Add variables to the model
x = model.addVar("x", vtype="CONTINUOUS")
y = model.addVar("y", vtype="CONTINUOUS")

# Set objective function
model.setObjective(2 * x + y)

# Add constraints
model.addCons(x + 2 * y <= 10, "constraint1")
model.addCons(3 * x - y >= 5, "constraint2")
#Error here 
cols = model.getLPColsData()

**Comment by namogg** [comment]
Yes, i understand the problem, but how can i enter the solving stage. I am trying to extract some feature of the MIP model. 
Thanks for the respond.

**Comment by Joao-Dionisio** [comment]
It depends on what you are trying to do. You can create a branching rule, that decides how to branch on integer variables, or a constraint handler, to stipulate how constraints should be enforced, or a pricer, to dynamically generate new columns, etc. etc.

Perhaps more simply, you can create an event handler to do something when the solving process triggers a certain condition. You have an example [here](https://github.com/scipopt/PySCIPOpt/blob/master/tests/test_event.py).

**Comment by namogg** [comment]
Thank you so much for your help. I understand the problem now.
