### ISSUE TITLE
The issues to take getLPCols/RowsData()

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#698]
Dear support team,

I am currently trying to understand how the SCIP internal functions work. At the moment, am willing to know about the following methods:

```
1)  scip.isLPSolBasic() : returns whether the current LP solution is basic
2)  scip.getVars(transformed = True) : ?
3)  scip.getLPCols/RowsData() : Retrieve current LP columns/rows
4)  SCIP_RESULT.DIDNOTRUN : the method was not executed
```

Also, when I call some of these methods, it seems the solver got stuck and the session crashed. 

```
from pyscipopt import *
scip = Model("Example")  # model name is optional
scip.printVersion()

x_1 = scip.addVar("x_1", vtype="C")
x_2 = scip.addVar("x_2", vtype="C")

scip.setObjective(7*x_1 + 9*x_2)
scip.addCons(-1*x_1 + 3*x_2 <= 6)
scip.addCons( 7*x_1 +   x_2 <= 35)

print('------------------------------------------------')
vars = scip.getVars(transformed = True)
print(vars)

# cause an issue
basic = scip.isLPSolBasic()
print("basic ", basic)


# cause an issue
cols = scip.getLPColsData()
rows = scip.getLPRowsData()
print(cols)
print(rows)

# cause an issue
basisind = scip.getLPBasisInd()
print("basisind :", basisind)
print()
print('------------------------------------------------')

scip.redirectOutput()
scip.setMaximize()
scip.setPresolve(SCIP_PARAMSETTING.OFF)
scip.setHeuristics(SCIP_PARAMSETTING.OFF)
scip.setSeparating(SCIP_PARAMSETTING.OFF)

scip.optimize()
```

another strange thing is that, when I set `scip.printVersion()` after defining the model, it cannot print the solver version, but when I write it before the model definition, `scip = Model()`, it can print the log!!! (It would not actually be possible in the normal way).

I was wondering if, what do the right definitions of the mentioned methods mean, and also is there any specific way to use those to get the simplex tableau attributes?

Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
Hello, @abb-omidi! Please take a look at the documentation when these sort of problems appear. For example, [SCIPisLPSolBasic](https://www.scipopt.org/doc/html/group__PublicLPMethods.php#gace392f53d4615f0d4baaf49fc46d1c05) can only be called in stage SOLVING (when the model is being solved). The same is true for all other functions. The problem here is with PySCIPOpt's error handling, really.

I managed to print the log with no problems.

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Thank you so much for your reply, and also sorry for my late answer. The mentioned documents differ slightly from what I have seen on the SCIP host. This contains more descriptions around methods. I will look at this. 🙏.

I am not sure to understand what `when the model is being solved` means. would you please, more elaborate on? I am trying to call these methods in the solution process in this [MRE](https://colab.research.google.com/drive/143j_cQPNtoittPW05AAnBgXjjnskYBIL?usp=sharing), but It seems I need to inject this class, somehow, in the SCIP to invoke what I want towards the optimization process. I was wondering if, you could take a look and correct that if I am doing wrong. (However, the method does not throw an issue).

Would you please, how you managed to print the log with no problems by `printVersion()`? I am still unable to get that!!

Best regards
Abbas

**Comment by abb-omidi** [comment]
@Joao-Dionisio,

Would you please, take a look at the above model.
Regards

**Comment by Joao-Dionisio** [comment]
Hello @abb-omidi.

If you want to use ```isLPSolBasic()```, most likely you want to call it when SCIP finds a new LP solution. For that, you need to create an event handler that is activated whenever this happens and then does the things you program it to do. Here is an example of a simple event handler in PySCIPOpt: [link](https://github.com/scipopt/PySCIPOpt/blob/master/tests/test_event.py). And here is the page on event handlers in SCIP: [link](https://www.scipopt.org/doc/html/EVENTHDLR_MAIN.php). I never used an event handler, so I can't give you specifics.

As for log printing, I did not do anything, I can print the version whenever I want, I think.

![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/1df565a5-498b-4f40-af28-68ff10574387)

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Thanks for your prompt response. With a quick view, I think the provided link is very similar to what I am looking for. Please, let me work around this and inform you if I have any issues. For printing log, I have used its caller usually before the optimize() method and this is why the solver cannot print that. However, as it seems to be a strange behavior, it works at all. 

Sincerely yours
Regards
Abbas

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

I hope you are doing well. 
First, I managed to test and work with the event handler and I have some sort of questions that were asked [here](https://stackoverflow.com/q/76594631/7414813). I hope someone can address to fix the issues.

Second, I think the correct way to write `printVersion` is by following the `redirectOutput`. By that, everything works well and the output seems to be reasonable. 
```
s = model()
s.redirectOutput()
s.printVersion()
```
Also, as far as I see SCIP has some methods like `transformed model`, `empty rows`, etc. I am wondering if, is there any example to explain what they mean and how they work. (Also, except Gomory example).


Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
> Also, as far as I see SCIP has some methods like transformed model, empty rows, etc. I am wondering if, is there any example to explain what they mean and how they work. (Also, except Gomory example).

I don't think so, but you can take a look at the technical reports that SCIP publishes whenever a new major version is released. [Google Scholar link](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=scip&btnG=)

**Comment by abb-omidi** [comment]
@Joao-Dionisio,

Thank you so much.
Regards

**Comment by abb-omidi** [comment]
@Joao-Dionisio, 

I hope you be fine. I finally can solve my issue by some points of SCIP's experts on [StackOverflow](https://stackoverflow.com/questions/76594631/bestsolfound-event-handler-on-pyscipopt/76610014#76610014). The issue was related to defining a more code line and I can print the event I wanted.

Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
I am happy to hear that, Abbas. Have a nice weekend.
