### ISSUE TITLE
Defining logical expression  

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#701]
I would like to know if there exists any way to define a logical expression or pure logical expression as follows by pySCIPopt:

$$ (\sum_{i} a_{i,j}x_{i,j} \leq b) \implies (\sum_{i} c_{i,s}y_{i,s} \leq d) \quad \forall j \in J, s \in S \quad (1) $$

where $x$ and $y$ are positive variables, and also for pure logic can we invoke the CNF/DNF of the logical expression in an LP format? E.g. can we write the following:

$$ (x \lor y) \implies z \quad (2) \quad (x,y,z) \in \mathbb{B}$$

 and SCIP makes the output under a hood as:

$$ x - z \leq 0 \quad (2_1) $$

$$ y -z \leq 0 \quad (2_2) $$

P.S: the first one as far as I know needs to introduce indicator variables to automate translating the expression. And the second is very similar to what the SAT solvers do in whose internal translators.

 
Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
SCIP is able to directly linearize some logical constraints, with ```model.addConsAnd()```, for example, as described [here](https://stackoverflow.com/questions/68156714/logical-constraints-in-scip-pyscipopt) and [here](https://scipopt.github.io/PySCIPOpt/docs/html/tutorial_2logical_8py_source.html). With these methods, you should be able to do what you want.

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Thanks for your suggestion. I actually saw this, but it is different from what I was meaning. Let me say, I am working on a scheduling problem that uses Generalized Disjunctive Programming that needs to be converted, in the next phase, as the logical forms into those equivalent linear expressions. If you test Gurobi or CPLEX, they have a nice feature to deal with this form of the problem by either indicator variables or pure logic form which I guess is still a special form of indicator variable. 

I think what is implemented in the SCIP is a bit different from what exists in the CPLEX or Gurobi. For example, the mentioned AND constraint is really meant by $(x \land y \land z)$ that in the CPLEX can be written directly as (x && y && z). BTW, in this situation, the auxiliary variable $r$ defined for the [resultant](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#a692d1265addca9f5c156df4c399f3825) which is different from implicating an indicator variable. (If I am wrong please, correct me). 

However, I am trying to write ($(\sum_{i} a_{i,j}x_{i,j} \leq b) \implies (\sum_{i} c_{i,s}y_{i,s} \leq d) \quad \forall j \in J, s \in S$) as some of the separated disjunct, $(\text{[D1]} \lor \text{[D2]})$, but SCIP cannot extract the expressions. The following is the first disjunct of the mentioned expression I have tried to write:

```
for j in J:
  model.addConsOr([(quicksum(x[i,j]*a[i,j] for i in I) <= 3)], r_1[j])
(x and r are binary variables)
```
that means $r$ would be a `resultant`/`implication` (!!?) of the first argument. However, as SCIP does not show any error, it seems the expression cannot be extracted and the solver got stuck. I appreciate it if, does SCIP deal with this kind of expression as a list of binary/positive variables to be included?


Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
I've never really looked at indicator constraints, so I cannot tell you much about its inner workings... But looking [here](https://www.scipopt.org/doc/html/cons__or_8c_source.php#l02100) they mean that the resultant is simply the result of the expression as a binary variable. 

Your implication can be modeled as: $(\sum_i c_{i,s}y_{i,s} \leq d) \lor \neg (\sum_i a_{i,j}x_{i,j} \leq b)$. ```addConsOr``` requires variables in the arguments, so adding indicator variables yourself for each of the clauses should do the trick. Then you would just need ```model.addConsOr([I_1, I_2], r)```.

**Comment by abb-omidi** [comment]
@Joao-Dionisio,

Thank you so much for pointing this out. I actually, do the same as you suggested and the posted snippet code was belonging to that model. I managed to produce a simple example to see how SCIP can behave again such a situation, but as I said, it crashed. The model is:

```
from pyscipopt import *

model = Model()
I = range(3)
J = range(2)
S = range(3)

x ={}
for i in I:
  for j in J:
    x[i, j] = model.addVar(f"x_{i}_{j}", vtype="B")

y ={}
for i in I:
  for s in S:
    y[i, s] = model.addVar(f"y_{i}_{s}", vtype="B")

r_1 ={}
for j in J:
  r_1[j] = model.addVar(f"r1_{j}", vtype="B")

r_2 ={}
for s in S:
  r_2[s] = model.addVar(f"r2_{s}", vtype="B")


r = model.addVar("r", "B")

for j in J:
  model.addConsAnd([(quicksum(x[i,j] for i in I) <= 3)], r_1[j])

for s in S:
  model.addConsAnd([(quicksum(y[i,s] for i in I) <= 4)], r_2[s])

for j in J:
  for s in S:
    model.addConsOr([r_1[j],r_2[s]], r)

model.optimize()
```

P.S: disjunctive form as ($\text{[D1]} \lor \text{[D2]}$), indicates that each of the separated disjunct would be a form of a AND. That means, e.g. the first clause is meaning if an auxiliary binary variable is equal to one AND $\text{[D1]}$ would be activated. Then these auxiliary binary variables are internally aggregated by an XOR constraint.

Also, I can translate these logical constraints with the aid of a standard way like the $BigM$ method, but I am really willing to test that by a solver as the solvers do have many other tricks to speed up the solution process. This is why I have tried that.

Would you please, take a look at this?
Regards
Abbas

**Comment by Joao-Dionisio** [comment]
I meant that these methods take variables as inputs. ```(quicksum(y[i,s] for i in I) <= 4)``` is not a variable, it's an expression, and so it cannot be used as an argument for ```addConsAnd```. From my limited understanding, you probably really need to use some sort of big-M for the inner clauses and then use ```addConsOr``` for the outer disjunction.

For potential tricks that SCIP may employ with these constraints, you can check out their source, or perhaps try to talk to SCIP directly.

**Comment by abb-omidi** [comment]
@Joao-Dionisio,

Thank you so much for your informative comments and also for your time. 

Sincerely yours
Abbas
