### ISSUE TITLE
Eventexec does not working

### ISSUE THREAD

**Issue by namogg** [scipopt/PySCIPOpt#703]
I am trying to catch a event to get to the solving stage. The event init works fine but the eventexec does not hit. How can i fix that and is there any other way to solve the problem? Thank you

```
import pyscipopt as scip
from pyscipopt import Model, Eventhdlr, SCIP_RESULT, SCIP_EVENTTYPE, SCIP_PARAMSETTING, SCIP_STAGE
class MyEvent(Eventhdlr):
    def eventinit(self):
        self.model.catchEvent(SCIP_EVENTTYPE.LPSOLVED, self)

    def eventexit(self):
        self.model.dropEvent(SCIP_EVENTTYPE.LPSOLVED, self)

    def eventexec(self, event):
        print("a")

def solve_mip_example():
    model = Model("Example")  # model name is optional
    model.printVersion()

    x_1 = model.addVar("x_1", vtype="I")
    x_2 = model.addVar("x_2", vtype="I")

    model.setObjective(7*x_1 + 9*x_2)
    model.addCons(-1*x_1 + 3*x_2 <= 6)
    model.addCons( 7*x_1 +   x_2 <= 35)
    model.setPresolve(SCIP_PARAMSETTING.OFF)
    model.setMaximize() 
    # Solve the problem
    eventhdlr = MyEvent()
    model.includeEventhdlr(eventhdlr, "TestFirstLPevent", "python event handler to catch FIRSTLPEVENT")

    model.optimize()
    return
solve_mip_example()
```

**Comment by namogg** [comment]
Another question, can i cancel the solving process after i call model.optimize() ?

**Comment by mattmilten** [comment]
The comment actually means that the user has to implement this callback method while many of the other callback methods can be left empty.

The optimization process can be interrupted using the [Model.interrupt() method](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#af36829d20ea04944535e0f2f17dcf2ea).

**Comment by mattmilten** [comment]
Can you try solving a bigger model? It may happen that even without presolving, the LP relaxation is not solved here.

**Comment by namogg** [comment]
I encounter another problem when i debug. I have tried bigger model but it is still not working. The eventinit works fine, the breakpoint in eventexec doesnt hit. Then when eventexit run, i get this error. 
```
self.model.dropEvent(SCIP_EVENTTYPE.LPEVENT, self)
ReferenceError: weakly-referenced object no longer exists
```

**Comment by namogg** [comment]
I have sucessfully enter solving stage but all the constrain is deleted and it leads to model.getLPColsData() being empty. If i model.freeTransform(), then i can see my constrains. Why is this happening?

**Comment by Joao-Dionisio** [comment]
Hello, @namogg! Sorry for the super large delay. What is the status of this? Is it still a problem, and if so, can you please share your code?

**Comment by namogg** [comment]
ohhh thanks for the respond, i solved it so im closing now. Thanks you guys so much for your help, you guys are the best
