### ISSUE TITLE
Variable upper bound is not set correctly

### ISSUE THREAD

**Issue by igorbanfi** [scipopt/PySCIPOpt#704]
Hello,
I am currently encountering an issue while using PySCIPOpt version 4.3.0 and SCIP version 8.0.3.5 (GitHash: 26bef13099). The problem lies in setting the upper bounds of variables, which does not seem to function correctly.

For instance, when writing the master problem from `examples/finished/flp-benders.py` to file the output is:

```plaintext
STATISTICS
  Problem name     : flp-master
  Variables        : 3 (3 binary, 0 integer, 0 implicit integer, 0 continuous)
  Constraints      : 0 initial, 0 maximal
OBJECTIVE
  Sense            : minimize
VARIABLES
  [binary] <y(1)>: obj=1000, original bounds=[0,2.20687562260388e-312]
  [binary] <y(2)>: obj=1000, original bounds=[0,2.20687562260388e-312]
  [binary] <y(3)>: obj=1000, original bounds=[0,2.20687562260388e-312]
END
```

The upper bounds are not being set as expected. However, when using SCIP version 8.0.3.5 (GitHash: 30e271fdb9), the bounds are set correctly:

```plaintext
STATISTICS
  Problem name     : flp-master
  Variables        : 3 (3 binary, 0 integer, 0 implicit integer, 0 continuous)
  Constraints      : 0 initial, 0 maximal
OBJECTIVE
  Sense            : minimize
VARIABLES
  [binary] <y(1)>: obj=1000, original bounds=[0,1]
  [binary] <y(2)>: obj=1000, original bounds=[0,1]
  [binary] <y(3)>: obj=1000, original bounds=[0,1]
END
```

Was not sure if issue is with SCIP or PySCIPOpt. However since all test on SCIP are passing, I decided to report it here.

**Comment by igorbanfi** [comment]
Hello @Joao-Dionisio, 

https://gist.github.com/igorbanfi/bd7c3d653d7fa5b500709a140119aada

I am building SCIP on ubuntu 22.04

**Comment by Joao-Dionisio** [comment]
This is very strange, @igorbanfi, I cannot reproduce your problem. The only difference is that I'm using SCIP 8.0.3. In your original post you are saying that there are issues if you write the problem using PySCIPOpt, but not if you use SCIP directly, is that it?

Also, how did you install PySCIPOpt?

**Comment by igorbanfi** [comment]
After doing a clean install of both PySCIPOpt and Scip, the issue disappeared. I can't really explain why it happened in the first place. Thank you @Joao-Dionisio for your help and patience.
