### ISSUE TITLE
Why did the CONSENFOLP callback assertion fail when the problem has a primal feasible solution?

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#709]
I am working on the problem that I am willing to use SCIP's `conshdlr` callback to check how the constraints might be added to the model. I am using the following manner:

```
class MyConshdlr(Conshdlr):

    ## fundamental callbacks ##
    def consenfolp(self, constraints, nusefulconss, solinfeasible):
    calls.add("consenfolp")
    for constraint in constraints:
      assert id(constraint) in ids
    return {"result": SCIP_RESULT.FEASIBLE}

    def consenfops(self, constraints, nusefulconss, solinfeasible, objinfeasible):
    calls.add("consenfolp")
    for constraint in constraints:
      assert id(constraint) in ids
    return {"result": SCIP_RESULT.FEASIBLE}


    def conscheck(self, constraints, solution, checkintegrality, checklprows, printreason, completely):
    calls.add("conscheck")
    for constraint in constraints:
      assert id(constraint) in ids
    return {"result": SCIP_RESULT.FEASIBLE}

    def conslock(self, constraint, locktype, nlockspos, nlocksneg):
    calls.add("conslock")
    assert id(constraint) in ids

    ## Optinal callbacks ##
    def consactive(self, constraint):
    calls.add("consactive")
    assert id(constraint) in ids

    def consgetnvars(self, constraint):
    calls.add("consgetnvars")
    assert id(constraint) in ids
    return {"nvars": 1, "success": True}
    
    def test_conshdlr():

        def create_model():
            # create solver instance
            s = Model()


            # Optimization model
            ...

            # create conshdlr and include it to SCIP
            conshdlr = MyConshdlr()
            s.includeConshdlr()
            
            # creating constraint
            cons1 = s.createCons()
            ...

            # add these constraints
            s.addPyCons()
            ...
            
            return s

        s = create_model()
        # solve problem
        s.optimize()

        del s
        assert "consenfolp" in calls
        assert "consenfops" in calls
        assert "conscheck" in calls
        assert "conslock" in calls
        assert "consactive" in calls
```

As long as the problem is solved by the usual paradigm, the solver returns the optimal solution, but when I add the constraints by callbacks, it throws an issue as follows:

```
AssertionError                            Traceback (most recent call last)
<ipython-input-7-9a59f5f7b72a> in <cell line: 154>()
    153 
    154 if __name__ == "__main__":
--> 155   test_conshdlr()

<ipython-input-7-9a59f5f7b72a> in test_conshdlr()
    137   del s
    138 
--> 139   assert "consenfolp" in calls

AssertionError: 
```

Also, I have a look at SCIP's documents where CONSENFOLP is defined as:

> The CONSENFOLP method is called after the price-and-cut loop was finished and an LP solution is available. Like the CHECK call, the ENFOLP method should return a result SCIP_FEASIBLE, if the solution satisfies all the constraints. However, the behavior should be different, if the solution violates some of the associated constraints. The constraint handler may return a result SCIP_INFEASIBLE in this situation, but this is not the best what one can do.

Now, my questions are:
* Is it still necessary to use `del s` to remove the model? And if one does not use `del s`, what's happened? 
* What does exactly CONSENFOLP mean? and how does it work?
* As the other callbacks seem to work fine, how is it possible to reject the solution by CONSENFOLP?

All the best
Abbas

**Comment by Joao-Dionisio** [comment]
Hey @abb-omidi, is this still relevant?

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Thanks. I sent some sort of emails to SCIP community and get some useful comments. I will add this ASAP as may be useful to ordes. 

Regards

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

I tried to sum up my questions w.r.t the main issue I had and asked on the SCIP community. I added some useful hints from [Mathieu Besançon](https://www.zib.de/members/besancon) that answered these questions.

The questions:

> 1) As the definition of consenfolp/consenfops is very specific and contains the term price-and-cut loop, What does the price-and-cut loop mean?
> 
> 2) What is the difference between consenfolp/consenfops and conscheck when applied to the model?
>   
> 3) As my problem has a primal feasible solution, actually optimal one, and already other callbacks seem to work fine, how is it possible to reject the constraints/solution by consenfolp/consenfops?
> 
> 3) Is it still necessary to use conshdlr.createData when we want to add the constraint? 

The answers:

> 1. The price-and-cut-loop happens before the constraint handler is called, this corresponds to the step where the LP relaxation has been solved, and the rounds of cuts (from separator plugins) have already happened.
> 
> 2. consenfoXYZ acts on a primal solution by adding a constraint, cut, or something else. In contrast, the check function only computes whether a violation of the constraint represented by the constraint handler is present at the current solution, and returns whether the solution is feasible or infeasible.
> https://www.scipopt.org/doc/html/CONS.php
> 
> 3. I am not sure to understand what you mean by this one. Is the solution feasible for your constraint? If yes, you can just use SCIP_FEASIBLE as a result. If this solution is not feasible, then you can do one of the actions detailed in the documentation page linked above. If the only possible thing is determining the current solution as infeasible, then the ENFO constraint can use a result SCIP_INFEASIBLE.
> 
> 3. I don't think create data is necessary for a constraint handler but not sure on this one.

For more details Please, see this [link](http://listserv.zib.de/pipermail/scip/2023-August/004717.html).

Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
Thank you very much for taking the time to help the community, @abb-omidi!

I'll be closing the issue, then.
