### ISSUE TITLE
Negetive value for variables

### ISSUE THREAD

**Issue by zsasan** [scipopt/PySCIPOpt#710]
Hello Pyscipopt workers,

I have modeled a problem and there is a decision variable in the problem that should take positive and negative integer values.
But after implementing with Pyscipopt package, this variable does not accept negative values.
I also tested a much simpler example for negative integer values and the problem was there
Thank you for guiding me on how to define this variable.

Below is the code related to the simple problem.
When running this code, the problem becomes infeasible.

------------------------------------------------
from pyscipopt import Model
model = Model("Example")  # model name is optional

x = model.addVar("x", vtype="INTEGER")
y = model.addVar("y", vtype="INTEGER")
model.setObjective(x + y, "maximize")
model.addCons(x <= -3)
model.addCons(y <= -2)
model.optimize()
print(model.getStatus())
print(model.getObjVal(x))
print(model.getObjVal(y))

**Comment by Joao-Dionisio** [comment]
Hello, PySCIPOpt user! :) 

The problem here is that by default, PySCIPOpt assumes that variables have a lowerbound of 0 and an upper bound of infinity. To change this, you simply have to do the following:

 ```
x = model.addVar("x", lb = -float("inf"), vtype="INTEGER")
```

This makes it so the lower bound for x is $-\infty$. You can of course use a different lower bound, if you want. You can change the upper bound as well, by adding ```ub=...``` to the variable creation.

**Comment by zsasan** [comment]
> Hello, PySCIPOpt user! :)
> 
> The problem here is that by default, PySCIPOpt assumes that variables have a lowerbound of 0 and an upper bound of infinity. To change this, you simply have to do the following:
> 
> ```
> x = model.addVar("x", lb = -float("inf"), vtype="INTEGER")
> ```
> 
> This makes it so the lower bound for x is −∞. You can of course use a different lower bound, if you want. You can change the upper bound as well, by adding `ub=...` to the variable creation.

Thank you very much for your explanation
With these changes, my problem in implementation was solved
