### ISSUE TITLE
Not being able to addVar after model is solved

### ISSUE THREAD

**Issue by noamgold** [scipopt/PySCIPOpt#711]
After solving a model / running optimize! we generate some scanario corresponding to a variable and constraint and then resolve.
We get an exception:
  File "/Users/stephenshin/Desktop/Israel research material/knapsack.py", line 80, in update_rebpp
    alpha[scenario_num+1] = model.addVar(vtype="C",name="alpha(%s)"%j)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/pyscipopt/scip.pyx", line 1446, in pyscipopt.scip.Model.addVar
  File "src/pyscipopt/scip.pyx", line 252, in pyscipopt.scip.PY_SCIP_CALL
Exception: SCIP: method cannot be called at this time in solution process!

Why wouldn't it be possible  to call addVar on a model after it is solved?

**Comment by Joao-Dionisio** [comment]
Hello, @noamgold! Why do you want to add a variable to a model after it is solved? I am asking because that way I may be able to tell you how someone could achieve what you want with PySCIPOpt.

Perhaps creating a new model, equal to the previous one can do what you want.

``` 
m = Model()
.
.
.
m.optimize()
m2 = Model(sourceModel = m)
m2.addVar()
.
.
.
m2.optimize()
```

**Comment by noamgold** [comment]
We are generating both constraints and variables (columns) for for an MILP. 
The problem with creating a new model is that it seems to invalidate the previous variable references.

If we need to create a variable say y at each iteration and append it to a list 
 y[K] = model.addVar(vtype="C", name="y(%s)") 
but we also have variables x, z
it seems that there is no starightforward way to do getVars() or something similar to obtain only the y array. Ideally we can just maintain the reference to y and append to it at each iteration. Most solvers and interfaces allow one to resolve a model without copying/"cloning" it (e.g., Pulp, JuMP, Gurobi whether in Python or Julia etc.)

**Comment by mattmilten** [comment]
You just have to tell SCIP to clean up the internal data structures and reset the problem status via model.freetransform(). Then you can also add new variables without losing the previous references.

**Comment by noamgold** [comment]
Thank you, it worked.
