### ISSUE TITLE
I got an error installing PySCIPOpt package

### ISSUE THREAD

**Issue by Nazanin-87** [scipopt/PySCIPOpt#712]
I am trying to install the PySCIPOpt package for solving a linear optimization problem. I want to install PySCIPOpt on Windows 10.
The requirements I installed are as follows:
Python 3.8
pip 23.2.1
scip 8.0.3
When I run pip install PySCIPOpt via the command window I get an error shown in the following.

C:\Windows\system32>python -m pip install pyscipopt 
Collecting pyscipopt 
  Using cached PySCIPOpt-4.3.0.tar.gz (665 kB) 
  Installing build dependencies ... done 
  Getting requirements to build wheel ... done 
  Installing backend dependencies ... done 
  Preparing metadata (pyproject.toml) ... done 
Building wheels for collected packages: pyscipopt 
  Building wheel for pyscipopt (pyproject.toml) ... error 
  error: subprocess-exited-with-error 
 
  × Building wheel for pyscipopt (pyproject.toml) did not run successfully. 
  │ exit code: 1 
  ╰─> [32 lines of output] 
      Using include path C:\Program Files\SCIPOptSuite 8.0.3\include. 
      Using SCIP library libscip at C:\Program Files\SCIPOptSuite 8.0.3\lib. 
 
      running bdist_wheel 
      running build 
      running build_py 
      creating build 
      creating build\lib.win-amd64-cpython-38 
      creating build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\Multidict.py -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\init.py -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\scip.pyx -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\scip.pxd -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\benders.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\benderscut.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\branchrule.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\conshdlr.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\cutsel.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\event.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\expr.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\heuristic.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\lp.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\nodesel.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\presol.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\pricer.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\propagator.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\reader.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\relax.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      copying src\pyscipopt\sepa.pxi -> build\lib.win-amd64-cpython-38\pyscipopt 
      running build_ext 
      building 'pyscipopt.scip' extension 
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
 
      [end of output] 
 
  note: This error originates from a subprocess, and is likely not a problem with pip. 
  ERROR: Failed building wheel for pyscipopt 
Failed to build pyscipopt 
ERROR: Could not build wheels for pyscipopt, which is required to install pyproject.toml-based projects

**Comment by Joao-Dionisio** [comment]
Hello, @Nazanin-87! Have you followed the instructions on the [installation page](https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md) correctly (namely when it comes to setting the ```SCIPOPTDIR``` variable)? 

Also, from my experience, installing PySCIPOpt using Anaconda is much simpler, especially on Windows.

**Comment by skadio** [comment]
Possible that either 
- you didn't install the pre-packaged C++ backends (see https://visualstudio.microsoft.com/visual-cpp-build-tools/ and https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170)

and/or 
- didn't add the environment variable SCIPOPTDIR to point to scip installation folder (sth like C:\Program Files\SCIPOptSuite 8.0.0)

**Comment by Joao-Dionisio** [comment]
I'm closing this issue to clear the Issue page, but feel free to reopen it if you are still having problems!
