### ISSUE TITLE
Accessing information of constraints

### ISSUE THREAD

**Issue by MoRic3** [scipopt/PySCIPOpt#713]
I am using PySCIPopt version 4.3.0 which corresponds to SCIP version 8.0.3.

I am wondering if PySCIPopt/SCIP allows to do something like the following:

Given a model object, I want to access information of a constraint. In fact, I want to know which variables appear in the specific constraint. And I want to get the constraint rule/expression, so I can use it further, e.g., for embedding it into a new constraint.

I attached code showing what I want to do using the Pyomo environment (see [https://anaconda.org/conda-forge/pyomo](https://anaconda.org/conda-forge/pyomo)). 

Do you see any possibility of doing something similar in PySCIPopt?
Thanks a lot.

```
from pyomo.environ import *
from pyomo.core.expr.current import identify_variables

# define the model
def build_model():
    model = ConcreteModel()

    # define variables
    model.x1 = Var(within=Reals, bounds=(0,1))
    model.x2 = Var(within=Reals, bounds=(0,1))
    model.x3 = Var(within=Integers, bounds=(-4,1))

    # define constraint
    model.cons_nonlin0 = Constraint(expr = (1 - model.x1**2 - model.x2**2) <= 0)

    # define objective
    model.objective0_nonlin = Objective(expr = model.x2 - exp(model.x3))

    return model

model = build_model()

for c in model.component_objects(Constraint):
    var_list = list(identify_variables(c.body))
    print('appearing variables (pyomo objects):', var_list)
    
    print('constraint expression:', c.body)
    
    # add modified constraint
    model.add_component('modified_'+c.name,
                        Constraint(expr = c.body + 5 <= 0))
    
    # deactivate old one
    c.deactivate()
```

**Comment by Joao-Dionisio** [comment]
I did not manage to find anything, sorry... @mattmilten @fserra, do any of you know how one would do this? Ambros asked something about it a few days ago as well and I didn't know how to answer.

**Comment by ambros-gleixner** [comment]
I guess for this we would just need to interface SCIPconsGetVars(), see https://scipopt.org/doc/html/cons_8c.php#aeacdfba7623596329c1cfb1500cfdb36, right? That should not be too hard to do.

**Comment by Joao-Dionisio** [comment]
I think I've already done everything, Ambros, I'm only having some issues with the compilation (it's my first modification to the source code). I'm waiting for some help with it, but with the weekend and people on vacation, it may take a bit.

**Comment by ambros-gleixner** [comment]
Great, thanks!

**Comment by MoRic3** [comment]
Wow, you are awesome! I am looking forward. Thanks a lot!! Let me know if there is anything I can help with (but be aware that I have no experience with the SCIP source code).

**Comment by MoRic3** [comment]
Hello, @Joao-Dionisio ! Thanks a lot for your effort, it sounds very nice. I'll try it out and follow the updates closely.

**Comment by Joao-Dionisio** [comment]
Hello, @MoRic3! This ended up taking longer than expected, sorry about that. I just added PR #760 with the possibility of adding a nonlinear expression to a nonlinear constraint. If you need to use it on a linear constraint, just add a dummy variable and square it 

```x = m.addVar(lb=0,ub=0), m.addCons(your_linear_cons + x**2 <= right_hand_side)```

The function will probably be changed in the future since it's a bit hacky, but I think it does what you want. Please let me know if it works in your own work! I ran some tests, but it seems bugs always manage to slip through :)
