### ISSUE TITLE
ReadProblem Exception: SCIP: a required plugin was not found

### ISSUE THREAD

**Issue by skadio** [scipopt/PySCIPOpt#714]
Team, 

I can build and run PyScip models but reading MIPLIB instances throws an error. 

My installation details are below. 

Any pointers? 

```
   model.readProblem("noswot.mps.gz")
   File "src\pyscipopt\scip.pyx", line 4879, in pyscipopt.scip.Model.readProblem
   File "src\pyscipopt\scip.pyx", line 259, in pyscipopt.scip.PY_SCIP_CALL
Exception: SCIP: a required plugin was not found !
```

I also tried the extension parameter with "mps.gz", "gz", ".mps.gz", ".gz" etc. What's the best practice on extensions for MIPLIB?

==

Installed PySCIP on Windows as suggested:
- Installed pre-packaged C++ backend
- Installed a compatible scip version v8.0.0 with pyscip 4.2
- Set the env variable for SCIPOPTDIR to point to the installation
- Installed PyScip via "conda install --channel conda-forge pyscipopt"

Building and solving example models work. Reading and solving ".cip" example also work

**Comment by Joao-Dionisio** [comment]
Good morning, @skadio! I don't know the file format, but it seems that ```mps.gz``` is just a compressed ```mps```, right? Don't you need to extract it (like [here](https://linuxize.com/post/how-to-unzip-gz-file/)) and then read the ```mps``` file like usual?

Anyhow, you can see here the list of file readers that SCIP has: [https://scipopt.org/doc-7.0.1/html/group__FILEREADERS.php](https://scipopt.org/doc-7.0.1/html/group__FILEREADERS.php), and here [https://scipopt.org/doc-7.0.1/html/READER.php](https://scipopt.org/doc-7.0.1/html/READER.php) how to add a new file reader to SCIP.

**Comment by skadio** [comment]
Hello @Joao-Dionisio, thank you very much for the pointers!

Yes, I believe these are compressed mps files. 

I am %100 certain that reading-and-solving “.mps.gz” works with Scip —I have done it before, and other members in our group verifies. 

Let me try manually unziping first and then sending it to Scip

I suspect the issue here is about the installation so I wanted to check if it is a commonly faced / obvious error.

I tried another clean install, leading to same error.. so not sure how to proceed

**Comment by mattmilten** [comment]
On Windows, zlib is not easily available and the SCIP binaries and libraries and built without it. You can see that there is no zlib in the Windows version: https://scipopt.org/index.php#download

I'd recommend using WSL2 and running everything in there. This Linux environment is much more straightforward to use and less error-prone.

**Comment by skadio** [comment]
I see, thanks explains all the mystery —thank you! 

Zlib is the missing plug-in in this case (and in cases where I know it worked must have that available)

Reading “.mps” files, as you suggested, works also fine —thank you!

**Comment by Joao-Dionisio** [comment]
Thanks for the help, Mathias, and glad your problem was solved, @skadio :) I'm going to close the issue now then, but feel free to reopen it if you think it makes sense!
