### ISSUE TITLE
The issue on solving TSP example

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#715]
Dear support team,

I am working on the TSP example, [Link](https://colab.research.google.com/drive/1M060XzcZ-A8dsmM-CbHqoRn6BSnlx8YG?usp=sharing), to understand how to add a lazy constraint by PySCIPopt. It seems the problem should work fine as it is solved in the small instances very well with the same objective function in both either adding directly or by using a lazy one the subtours elimination constraints.

The issue is that when I want to test the large model, say the number of nodes is more than 100,  the objective function values are different. For example, as long as I am using SEC directly the OF value is 8 while by adding SEC as a lazy it is around 8.17. By checking the solution from both solves it seems as long as I added SEC as a lazy, the binary variables in the solution have the fractional values.

```
x_7_22                                              1 	(obj:0.06)
x_7_76                                              1 	(obj:0.14)
x_8_18                                            0.5 	(obj:0.11)
x_8_23                                            0.5 	(obj:0.09)
```

Also, I set the priority number of some conshdlr callbacks as follows, but the results are the same!!

```
model.includeConshdlr(conshdlr, "TSP", "TSP subtour eliminator",
                      sepapriority = -1, enfopriority = -1, chckpriority = -1, sepafreq = -1, propfreq = -1,
                      eagerfreq = -1, maxprerounds = 0, delaysepa = False, delayprop = False, needscons = False,
                      presoltiming = SCIP_PRESOLTIMING.FAST, proptiming = SCIP_PROPTIMING.BEFORELP
                      )
```

I was wondering if, what is going wrong and how can I fix that?

Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
Good afternoon, @abb-omidi! 

I think I can answer one of your concerns for now, regarding the fractional variables. I think that ```printSol``` maybe prints the solution of the transformed problem, rather than the original one. If you do something like

```
for v in model.getVars():
    if model.getVal(v) != 0:
        print(v.name, model.getVal(v))
``` 

You will see that all the variables are binary.

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Thank you so much for your reply. I tried to test and check `printSol` for some other models and the results are the same as when I am using `model.getVars()`. Maybe I have been lucky to get this. Also, this is rising up a question about, **_how is it possible to write a transformed model to compare to the original one?_**

Also, I change the input data as decimals form into the integer to calculate the traveling costs. By that, the objective function value of both methods is the same and it seems that the difference is corresponding to the rounding floating points. **_May I have your insight?_**

Another issue I have faced is as long as the problem write by `model.writeProblem("test_1.cip")`, the output and the solving process work well, but when I use `model.writeLp("test_1.lp")` the solving process and also the session is crased. You can check and see it on the example. **_Would you please, is there another method to write an LP file?_**


Best regards
Abbas

**Comment by mattmilten** [comment]
Hi Abbas,

The file extension determines the file format, so you just have to call `model.writeProblem("test_1.lp")` to write out an LP file.
To write the transformed problem to a file, you can just call `model.writeProblem("trans.lp", trans=True)` as indicated in the [writeProblem() documentation](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#aaeea39150fbf007180b7ab7d8e476d2e).

Cheers,
Matthias

**Comment by abb-omidi** [comment]
Dear @mattmilten,

Thanks for your comments. Actually, I have used `model.writeProblem("test_1.lp")` to write and show the model. But, I have some difficulties to download the files as other libraries do not have this. Also, for the second, let me check and get back to you if I have any questions.

All the best 
Regards
Abbas

**Comment by abb-omidi** [comment]
Dera @Joao-Dionisio, @mattmilten,

The mentioned method to write the transformed problem is so interesting and can provide many hidden details. 

Best regards
Abbas
