### ISSUE TITLE
Illegal instruction Error

### ISSUE THREAD

**Issue by therealpeterpython** [scipopt/PySCIPOpt#718]
Hello PySCIPOpt-Team,

I tried to implement the problem I am working on and I got an unexpected error message that I think is a bug. I build a minimal working example that reproduces the bug for me. If I implement this example in zimpl and convert & solve it with Zimpl & Scip it gets solved without any problems.

Here you can find the [minimal_example.py.txt](https://github.com/scipopt/PySCIPOpt/files/12291130/minimal_example.py.txt) (renamed to .txt to upload it here).
Here is the corresponding .zimpl file: [minimal_example.zimpl.txt](https://github.com/scipopt/PySCIPOpt/files/12291172/minimal_example.zimpl.txt)

If I run the minimal_example.py I get:
```
presolving:
(round 1, fast)       0 del vars, 0 del conss, 0 add conss, 4 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 0 clqs
   (0.0s) symmetry computation started: requiring (bin +, int +, cont +), (fixed: bin -, int -, cont -)
   (0.0s) symmetry computation finished: 1 generators found (max: 1500, log10 of symmetry group size: 0.3)
   (0.0s) no symmetry on binary variables present.
(round 2, exhaustive) 0 del vars, 0 del conss, 1 add conss, 4 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 0 clqs
presolving (3 rounds: 3 fast, 2 medium, 2 exhaustive):
 0 deleted vars, 0 deleted constraints, 1 added constraints, 4 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 0 cliques
presolved problem has 2 variables (0 bin, 0 int, 0 impl, 2 cont) and 3 constraints
      1 constraints of type <linear>
      2 constraints of type <nonlinear>
transformed objective value is always integral (scale: 1)
Presolving Time: 0.00

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
  0.0s|     1 |     0 |     3 |     - |   661k |   0 |   6 |   3 |   8 |   0 |  0 |   0 |   0 | 0.000000e+00 |      --      |    Inf | unknown
Illegal instruction (core dumped)
```

I use version 4.3.0 of pyScipOpt and version 3.11.4 of python on a Linux Mint 21 Cinnamon (5.4.12).

If I can help you diagnose this problem further please let me know.

**Comment by Joao-Dionisio** [comment]
Good afternoon, @therealpeterpython! That is strange, I'm able to solve your model just fine...

![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/a4e299bf-b87f-4dd7-a9c8-716d745847ce)


Gets me this

![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/8364534b-75c0-4e41-85df-c78e7eb0651b)


How did you install PySCIPOpt?

**Comment by therealpeterpython** [comment]
Hello @Joao-Dionisio, thanks for your fast response. I installed PyScipOpt via conda `conda install -c conda-forge pyscipopt`. The exact Version conda installed is `conda-forge/linux-64::pyscipopt-4.3.0-py311hcafe171_0`.

**Comment by therealpeterpython** [comment]
I looked for the coredump and the error appears to happen in libmetis.so. The relevant line from the coredump is
```
Thread 1 "python3.11" received signal SIGILL, Illegal instruction.
0x00007ffff35ff84f in libmetis.iset () from [...]/libmetis.so
```

**Comment by Joao-Dionisio** [comment]
Hello, @therealpeterpython! Thank you for your responses and detailed issue. You have located the error and it isn't related to SCIP, right? Can we close the issue here?

**Comment by therealpeterpython** [comment]
If you have any influence on the conda recipe for installing pyscipopt you could prevent the usage of metis-5.1.1. Other than that I think there is nothing to do here. Thanks for your work!  :)

**Comment by Joao-Dionisio** [comment]
Oh, thanks for the tip, I don't know anything about it :) 


You know about conda, right, @fschloesser? Can you help with this?  

> conda recipe for installing pyscipopt you could prevent the usage of metis-5.1.1

**Comment by ju-manns** [comment]
@therealpeterpython Hey. Thank for looking into this. Is it correct that you worked around this issue by manually installing an older version of metis so that conda does not install Metis 5.1.1 when installing PySCIPOpt?
I cannot find metis as a direct dependency of either PySCIPOpt or the SCIP conda package so I am not sure if we can downgrade the dependency.

**Comment by therealpeterpython** [comment]
Hello @ju-manns. That is right. Instead of using Metis 5.1.1 from the conda-forge channel I installed 5.1.0 from the anaconda channel. I didn't reinstall PySCIPOpt after that, the change of Metis alone fixed the problem for me.
