### ISSUE TITLE
Model is solving too long without correct result on MacOS

### ISSUE THREAD

**Issue by vlraio** [scipopt/PySCIPOpt#722]
Hi there!
I installed scip on MacOS using SCIP Optimization Suite. When I try to run one of your [examples](https://github.com/scipopt/PySCIPOpt/blob/master/examples/finished/weber_soco.py), I don't get any result. I just see a long-long calculating process.
Part of logs:

> time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
  302s|  3987k|581873 |     0 |   0.0 |  2817M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404515e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3987k|581886 |     0 |   0.0 |  2817M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404519e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3987k|581900 |     0 |   0.0 |  2817M | 146 |  24 |   7 |   0 |   0 |  0 |   0 |   0 | 8.404519e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3987k|581924 |     0 |   0.0 |  2817M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404522e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3987k|581962 |     0 |   0.0 |  2818M | 146 |  24 |   7 |   0 |   0 |  0 |   0 |   0 | 8.404522e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3987k|581990 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404523e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3987k|581989 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404523e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3988k|582017 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404523e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3988k|582037 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404525e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3988k|582051 |     0 |   0.0 |  2818M | 146 |  24 |   7 |   0 |   0 |  0 |   0 |   0 | 8.404525e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3988k|582085 |     0 |   0.0 |  2818M | 146 |  24 |   7 |   0 |   0 |  0 |   0 |   0 | 8.404526e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3988k|582113 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404526e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3988k|582127 |     0 |   0.0 |  2818M | 146 |  24 |   7 |   0 |   0 |  0 |   0 |   0 | 8.404526e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3988k|582148 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404526e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3988k|582154 |     0 |   0.0 |  2818M | 146 |  24 |   7 |   0 |   0 |  0 |   0 |   0 | 8.404526e+02 | 8.916013e+05 |  Large |  34.22%
 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
  302s|  3988k|582174 |     0 |   0.0 |  2818M | 146 |  24 |   7 |   0 |   0 |  0 |   0 |   0 | 8.404528e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3988k|582204 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404529e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3989k|582227 |     0 |   0.0 |  2818M | 146 |  24 |   7 |   0 |   0 |  0 |   0 |   0 | 8.404532e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3989k|582243 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404532e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3989k|582273 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404533e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3989k|582297 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404534e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3989k|582317 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404534e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3989k|582339 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404535e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3989k|582359 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404538e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3989k|582389 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404538e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3989k|582435 |     0 |   0.0 |  2818M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404542e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3989k|582453 |     0 |   0.0 |  2818M | 146 |  24 |   7 |   0 |   0 |  0 |   0 |   0 | 8.404542e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3990k|582473 |     0 |   0.0 |  2819M | 146 |  24 |   7 |   0 |   0 |  0 |   0 |   0 | 8.404545e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3990k|582479 |     0 |   0.0 |  2819M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404545e+02 | 8.916013e+05 |  Large |  34.22%
  302s|  3990k|582510 |     0 |   0.0 |  2819M | 146 |  24 |   7 |  16 |   0 |  0 |   0 |   0 | 8.404545e+02 | 8.916013e+05 |  Large |  34.22%

**OS:** MacOS Ventura 13.5
**Processor:** 2,3 GHz Quad-Core Intel Core i7
**scip:** 8.0.4

What could be causing this behaviour?
How can I fix it?

**Comment by Joao-Dionisio** [comment]
Hello, @akimovve! That is weird, I can solve the problem in 0.3s on Ubuntu. 

How did you install pyscipopt? Also, you said you installed SCIP through SCIPOptSuite, but how did you do it? Was it with the precompiled packages or did you build it from source?

**Comment by Joao-Dionisio** [comment]
Since the model is running, I assume it's not a problem with pyscipopt, but I don't know. Can you please try to write the problem to a file and then solve it using scip directly? If it takes a long time to solve as well, then I think [contacting](https://scipopt.org/index.php#contact) SCIP directly will be better.

**Comment by Joao-Dionisio** [comment]
I'm going to close the issue to clear the issue page, but if you're still having problems, feel free to reopen it!
