### ISSUE TITLE
How to get the coefficients matrix in an MILP

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#724]
Dear support team,

I am trying to do some sort of analysis on an MILP and I already need to write the coefficients matrix of a linear expression. I read [this](https://github.com/scipopt/PySCIPOpt/issues/713) and [this](https://stackoverflow.com/questions/67828685/how-to-get-constraint-matrix-after-presolving-in-pyscipopt) links, but they seemed cannot make sense. I can write the problem in an LP format and see what's happening, but it takes a long time and also has some difficulties to investigate by hand. I was wondering if, is there any way to do that? (An editable MRE can be found [here](https://colab.research.google.com/drive/1qN-SZlW32LmvMWyDNjWCbyChaDHPHILZ?usp=sharing)).

```
for i in conss_assignment:
  constr = m.getConss()[i]

coeff_dict = m.getValsLinear(constr)
print(coeff_dict)
```

The error:
`TypeError: list indices must be integers or slices, not pyscipopt.scip.Constraint
`

Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
Hello again, @abb-omidi!

Your problem is not in retrieving the coefficients. The error is in your loop. ```conss_assignment``` is a list of constraints, so each ```i``` will be a constraint and you are trying to use it as an index. You probably want something like this:

```
for i in conss_assignment:
  coeff_dict = m.getValsLinear(i)
  print(coeff_dict)
```

Output:
![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/0c072ebd-ddb8-46c5-9bd9-ca0d8d4e5d88)

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Thanks for your prompt response. It seems this is what I was looking for. And just for clarification, would you confirm that:

1) Does each line correspond to each row of the constraints, in this case, assignment constraint?
2) And if there is not e.g. $x_{0,0}$ in the second row, it means its corresponding coefficient is equal to zero? 
3) Also, is there any way to use this method to print the variables with zero coefficients?
4) Is there a way to print the variables with a more readable format? (e.g. $x_{item1,bin1}$)


Best regards
Abbas

**Comment by Joao-Dionisio** [comment]
1. Yes, this is iterating over the ```conss_assignment``` array, so it will print the rows in the order that they appear inside this array.
2. Yes, it only prints active variables
3. I don't think so, but you can easily deduce which ones are missing.
4. Yes, this is printing the variables with the names you defined. So you would need to do ```x[i, b] = m.addVar(f"x_item{i},bin{b}", vtype="B")``` when defining them at the beginning.

Best,
João

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Thank you so much for your informative comments. 

All the best
Abbas
