### ISSUE TITLE
PyRelaxExec does not connect all parameters

### ISSUE THREAD

**Issue by BrannonKing** [scipopt/PySCIPOpt#735]
The implementation of PyRelaxExec in relax.pxi does not connect all the parameters. I need the ability to set result and lowerbound. Please ensure that those get set after the call to relaxexec.

**Comment by BrannonKing** [comment]
I added these lines:

```python
    result_dict = PyRelax.relaxexec()
    lowerbound[0] = result_dict.get("lowerbound", <SCIP_Real>lowerbound[0])
    result[0] = result_dict.get("result", <SCIP_RESULT>result[0])
```

The result seems to work, although I cannot see that it actually utilizes my improved lowerbound yet. Well, it does print L on the left side of the console output, which I assume means it is seeing a better lower bound. It may just be ineffective because I didn't actually have a good lower bound on all the nodes.

**Comment by Joao-Dionisio** [comment]
Hello, @BrannonKing! Sorry I haven't replied earlier, but it wasn't an easy issue :) 

Are there any updates on this? Did your code manage to do what you wanted in the end?

**Comment by BrannonKing** [comment]
> Are there any updates on this? Did your code manage to do what you wanted in the end?

I believe that my code above (replacing the relaxexec) call works fine. Let's get it into master.

**Comment by Joao-Dionisio** [comment]
I like your enthusiasm, @BrannonKing! Can you create a PR with your code?
