### ISSUE TITLE
Increase memory usage

### ISSUE THREAD

**Issue by macky168** [scipopt/PySCIPOpt#736]
Hello,

Memory usage of PySCIPOpt is low and I want to increase memory usage to increase calc speed.
[The document](https://www.scipopt.org/doc/html/PARAMETERS.php) says `memory/arraygrowfac` affects it, but I could not see any change in memory usage when I set it.
Are there any params or methods?

Thanks.

**Comment by Joao-Dionisio** [comment]
Hello, @macky168! I think the parameter that limits the memory usage is ```limits/memory```, but it seems that the default setting is the maximum.

Do you know how much memory you're using at the moment?

**Comment by macky168** [comment]
Hello, @Joao-Dionisio  Thanks for your reply.
The memory usage is 8GB / 128GB when PySCIPOpt is solving a problem.
I make sure that I don't set `limits/memory`. Umm..., Any ideas?

**Comment by Joao-Dionisio** [comment]
Hey, @macky168, sorry for the delay! 

Hmm... Can you maybe share details about your setup? Is it possible that you are not allowed to access all the memory due to some permissions or something like that?

**Comment by mmghannam** [comment]
Hi @macky168, I think there might be a misunderstanding here. SCIP is _not_ limiting memory usage by default. To improve speed, you would either need to do parameter tuning or use the `solveConcurrent` method (for which you'd need to compile SCIP with task processing interface).
