### ISSUE TITLE
 DLL load failed while importing scip

### ISSUE THREAD

**Issue by santinabardengo** [scipopt/PySCIPOpt#741]
Hello! 
I have just installed Pyscipopt from pip in Windows, the 4.x version. Also I have installed SCIP (the 8x version) and I have the path to scip/bin in the eviromental variables. However, when I try to run one example as diet.py, the terminal shows this message: Traceback (most recent call last):
  File "c:\Users\Santi\OneDrive\Documentos\ProyectoDeInvestigacion_2023\Optimizacion_Tareas\OptimizacionTareas.py", line 5, in <module>
    from pyscipopt import Model, Conshdlr, SCIP_RESULT, SCIP_PARAMEMPHASIS, SCIP_PARAMSETTING
  File "C:\Users\Santi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscipopt\__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: DLL load failed while importing scip: No se puede encontrar el m�dulo especificado.  I do not know what to do. If you can, please, help me. Looking forward to your answer. Thanks.

**Comment by Joao-Dionisio** [comment]
Hello, @santinabardengo! Does your scip installation work? Also does your SCIPOPTDIR path have the folder specified in the [installation](https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md) page?

Finally, is installing with anaconda a possibility? From my experience, it's the simplest way to install pyscipopt in windows. We have someone working on a clean pip installation of pyscipopt, but it will take a little bit.

**Comment by Joao-Dionisio** [comment]
Hello, @santinabardengo! Has this issue been solved?

**Comment by santinabardengo** [comment]
Hi! Yes, thank you very much.

**Comment by Joao-Dionisio** [comment]
Glad to hear it! Feel free to open other issues with problems you're facing.
