### ISSUE TITLE
Get cuts added by scip at the root node

### ISSUE THREAD

**Issue by prachishah6795** [scipopt/PySCIPOpt#742]
Dear team, 

I am using the pyscipopt and want to get the cuts added by scip at the root node of a MIP (I don't care about actually solving the instance). At the same time, I want to restrict cut generation to one round of separation cuts only at the root and disable all presolving processes and restarts. What would be the best way to do so? 

Many thanks for your help!

**Comment by Joao-Dionisio** [comment]
Hello, @prachishah6795! Regarding your first question, of getting the cuts, I think that is not possible to do in PySCIPOpt yet, we need to interface the scip functions ```SCIPgetCuts``` and ```SCIPgetNCuts```.

As for your second question, there is a parameter for restricting the number of rounds as you want. You need to add ```model.setParam("separating/maxroundsroot", 1)```. You can see the other scip parameters [here](https://www.scipopt.org/doc/html/PARAMETERS.php). 

As for disabling presolving, you need to ```import SCIP_PARAMSETTING``` and add ```model.setPresolving(SCIP_PARAMSETTING.OFF)```. As for disabling restarts, you also have two parameters for this. ```estimation/restarts/restartpolicy``` (set to 'n'), and ```estimation/restarts/restartlimit``` set either '-1' or '0'. I don't know whether these two parameters do the same thing in this case, and what the difference between setting the second one to -1 or 0 will be, play around with them a little bit until you get what you want.

Hope this helps!

**Comment by prachishah6795** [comment]
Hi, thanks for your prompt response, this is very helpful. With regard to getting the cuts at root node, I tried the following - 
I set limits/nodes = 1 so that it would not solve beyond the root node. Then I called model.getLPRowsData() and looked at rows with origintype equal to 3 indicating these were added by a separator. What are these rows? Would these be the cuts added at the root?

**Comment by Joao-Dionisio** [comment]
Hey, @prachishah6795! I am not sure, but I think your reasoning makes sense. I would just be careful while looking at this type of data to make sure that it's referring to the original variables and not some kind of transformation that SCIP does to the problem. Sorry for not being able to help out more :/

**Comment by Joao-Dionisio** [comment]
Hey, @prachishah6795! I think I got a better answer to this problem.

You can loop through the rows of the problem with ```getLPRowsData```, and then call ```getOriginType```. If the result is "sepa", then you know that this row was added by a separator, meaning it's a cut.

Can this issue be closed?

**Comment by prachishah6795** [comment]
Hi @Joao-Dionisio! Thanks for the clarification. This really helps!
