### ISSUE TITLE
How to connect scip with other lp solvers in pyscipopt?

### ISSUE THREAD

**Issue by dxyzx0** [scipopt/PySCIPOpt#747]
I searched the documentation but only find the way I can connect with other lp solvers in C/C++ but not in pyscipopt.
Is there any instructions about how to accomplish this task?
Thanks.

**Comment by Joao-Dionisio** [comment]
Hello, @dxyzx0! Unfortunately, I think that that is not possible to do at the moment. The way this works now is you need to build SCIP (which is the actual solver, PySCIPopt is just an interface), with the correct options.

Here is the link for the installation [instructions](https://scipopt.org/doc/html/md_INSTALL.php). The relevant variable would be ```-DLPS```. By default it's Soplex, but according to this page, it's also possible to use gurobi, xpress, mosek, cplex, and glob. Let me know if you're having trouble with this part!

In the future, however, it would indeed be pretty cool to be able to choose which lp solver to use without the need to build SCIP every time, with something like ``` model.setParam("lp/solver", "solverxXYZ"), but that's more on the SCIP side that PySCIPOpt. Of course you would need all of the solvers on your machine, but that's not too bad.

**Comment by dxyzx0** [comment]
If I build scip with other lp solvers, how can I connect scip to pyscipopt?

**Comment by Joao-Dionisio** [comment]
Hey @dxyzx0, has this issue been solved?

**Comment by mmghannam** [comment]
Closing this for now, @dxyzx0 feel free to reopen if you still have questions.
