### ISSUE TITLE
Issue to install PySCIPopt on Colab

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#756]
Dear support team,

I have used SCIP on Colab and it worked very well. Nowadays when I want to import Pysicpopt I encounter the following message:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-3-753be5363cf8>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from pyscipopt import Model
      2 
      3 model = Model("Example")
      4 
      5 x = model.addVar("x", "C")

[/usr/local/lib/python3.10/site-packages/pyscipopt/__init__.py](https://localhost:8080/#) in <module>
      9 # export user-relevant objects:
     10 from pyscipopt.Multidict import multidict
---> 11 from pyscipopt.scip      import Model
     12 from pyscipopt.scip      import Benders
     13 from pyscipopt.scip      import Benderscut

ImportError: libscip.so.8.0: cannot open shared object file: No such file or directory

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

I was wondering if, how can I fix that? (An editable [MRE](https://colab.research.google.com/drive/15CeDkBEOzUJJFuFNWSSiyCRax8oZi11-?usp=sharing) is here)

Best regards
Abbas

**Comment by mmghannam** [comment]
Thank you for bringing this to our attention! It's an issue with syncing the latest release of SCIP with pyscipopt, @ju-manns is working on it and will write back as soon as it is solved.

**Comment by abb-omidi** [comment]
Dear @mmghannam,

Thank you so much for your attention. I am looking forward to hearing from you. 

Regards

**Comment by mmghannam** [comment]
Should be fixed now! @abb-omidi feel free to reopen if you still have an issue.

**Comment by abb-omidi** [comment]
@mmghannam, 

Of course. I can see it on the SCIP mailing list. I tested it and it works fine now.
Thank you so much for your response to inform us.

All the best
Abbas
