### ISSUE TITLE
How to define one's own branching process

### ISSUE THREAD

**Issue by qhu-Zero** [scipopt/PySCIPOpt#768]
Hello, I am currently implementing a function that only calculates the scores of some candidate variables during the branching phase and finds the best candidate variables for branching.

This is the vanillafullstrong branching method that I referred to:

    class PolicyBranching(Branchrule):
        def branchexeclp_vfsb(self, allowaddcons):
            
            result = self.model.executeBranchRule('vanillafullstrong', allowaddcons)

            return {'result': result}

It can run well.
This is the code I implemented myself:

scip.pyx:

        def getCandsVsbScores(self, cands):

            cdef int ncands = len(cands)

            # get current LP objective bound of the local sub problem and global cutoff bound
            cdef SCIP* scip = self._scip
            cdef SCIP_Real lpobjval = SCIPgetLPObjval(scip)

            cdef np.ndarray[np.float32_t, ndim=1] lp_datas
            lp_datas = np.empty(shape=(ncands, ), dtype=np.float32)

            # initialize strong branching without propagation
            PY_SCIP_CALL( SCIPstartStrongbranch(scip, False) )

            # compute downgain/upgain scores
            cdef SCIP_VAR* var
            cdef SCIP_Real val
            cdef SCIP_Bool integral
            cdef SCIP_Real down, up
            cdef SCIP_Real downgain, upgain
            cdef SCIP_Bool downvalid, upvalid
            cdef SCIP_Bool downinf, upinf
            cdef SCIP_Bool downconflict, upconflict
            cdef SCIP_Bool lperror
            cdef SCIP_Bool idempotent
            cdef int temp_int
            idempotent = True

            for i in range(ncands):
                var = (<Variable>cands[i]).scip_var
                val = SCIPvarGetLPSol(var)
                
                integral = SCIPisFeasIntegral(scip, val)

                up = -SCIPinfinity(scip)
                down = -SCIPinfinity(scip)

                if integral:
                    PY_SCIP_CALL(SCIPgetVarStrongbranchInt(scip, var, 2147483647, idempotent,
                            &down, &up, &downvalid, &upvalid, &downinf, &upinf, &downconflict, &upconflict, &lperror))
                else:
                    PY_SCIP_CALL(SCIPgetVarStrongbranchFrac(scip, var, 2147483647, idempotent,
                            &down, &up, &downvalid, &upvalid, &downinf, &upinf, &downconflict, &upconflict, &lperror))
                    
                down = max(down, lpobjval)
                up = max(up, lpobjval)
                downgain = down - lpobjval
                upgain = up - lpobjval
                lp_datas[i] = downgain * upgain

            return lp_datas

branch.py:

    class PolicyBranching(Branchrule):
        def branchexeclp_my_sbScores(self, allowaddcons):

            cands, *_ = self.model.getPseudoBranchCands()
            action_set = [c.getCol().getLPPos() for c in cands]
            lp_scores = np.array(self.model.getCandsVsbScores(cands))

            best_cand = int(lp_scores.argmax())

            self.model.branchVar(cands[best_cand])

            result = SCIP_RESULT.BRANCHED
            return {'result': result}

It cannot complete the work.

Later, I will change the getCandsVsbScores function to:

    if integral:
        # PY_SCIP_CALL(SCIPgetVarStrongbranchInt(scip, var, 2147483647, idempotent,
        #         &down, &up, &downvalid, &upvalid, &downinf, &upinf, &downconflict, &upconflict, &lperror))
            lp_datas[i] = 0
            
    else:
        PY_SCIP_CALL(SCIPgetVarStrongbranchFrac(scip, var, 2147483647, idempotent,
                &down, &up, &downvalid, &upvalid, &downinf, &upinf, &downconflict, &upconflict, &lperror))
        
        down = max(down, lpobjval)
        up = max(up, lpobjval)
        downgain = down - lpobjval
        upgain = up - lpobjval
        lp_datas[i] = downgain * upgain

It can complete branch work, but the search tree size for solving problem instances has increased by three times, indicating a decrease in branch quality.
I don't know how to solve this problem, nor do I know how to implement my ideas. If you have any ideas, please feel free to leave a message. Thanks!

**Comment by Joao-Dionisio** [comment]
Hello, @qhu-Zero! What do you mean when you say that your original ```getCandsVsbScores``` cannot complete the work? Does SCIP return an error? Or does it simply get stuck in a loop?

At the moment I can't catch any mistakes in your code. Maybe take a look at #662, another user created a very similar function, maybe it can help out.

**Comment by mmghannam** [comment]
Hello @qhu-Zero! Are you sure that your branching method is called? I could spot some errors in your code: 
1. The branching rule callback method should be called `branchexeclp` without a postfix.
2. The function to get the branching candidates should be `getLPBranchCands`. 
3. you should include the branching rule in your model and give it enough priority, you can check this [file](https://github.com/scipopt/PySCIPOpt/blob/3861380ba3b22af2e1dc1ee0d49f2fe5a334e13a/tests/test_branch_probing_lp.py) for an example.

**Comment by Joao-Dionisio** [comment]
Hey @qhu-Zero! Are you still having problems?

**Comment by Joao-Dionisio** [comment]
I'm closing this issue to clear the issue page, but feel free to reopen if you're still having problems!
