### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by zsasan** [scipopt/PySCIPOpt#770]
Hello,

I've been working with PySCIPOpt on an optimization problem and have encountered some performance issues. When running scenarios with moderate problem sizes, I've noticed that the execution time is quite prolonged, despite the CPU usage being around 30% and RAM consumption being approximately 1GB. My current machine specifications are – an Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz and 8GB of RAM. 

To improve performance, I'm seeking advice on the following:

1 - Is PySCIPOpt primarily CPU-intensive or RAM-intensive in its operations?

2- Does PySCIPOpt support parallel execution to leverage multi-core processors more effectively?
3- Could you please advise on which hardware aspect is more critical for running PySCIPOpt more efficiently? Specifically, should I focus on a stronger CPU, more RAM, or other components? 
Any guidance on optimizing performance for larger problems would be greatly appreciated.

Thank you for your assistance.

Sasan,

**Comment by Joao-Dionisio** [comment]
Hey @zsasan! Someone else should pick this up in the meantime, but I can answer some of your questions. 

2 - Yes, you can use the ```solveConcurrent``` method. However, for that, you need to build SCIP with the task process interface. Some information can be found [here](https://www.scipopt.org/doc/html/CONCSCIP.php), but what you need is the option ```tpi=tny```, I believe.

To answer your guidance comment: From my experience, increasing the solving speed of optimization problems can be obtained by, in decreasing order of importance, better models  (the existence of symmetry and of numerical instabilities has a significant impact, for example), faster algorithms, and only then better hardware. Of course, I'm not implying that the first two cases show up in your model. 

Can you share the size of your problem (number and type of variables and constraints) and the time it takes to solve it?

**Comment by mattmilten** [comment]
To answer the question on CPU vs RAM for MIP solvers: You simply need "enough" RAM to process the model and solver data - having more does not help. Fast RAM is important, though, and can improve solve times. The same holds for a fast CPU. Here, the single-core performance is more important than having more cores. PySCIPOpt by itself does not make use of multiple cores, but depending on how the underlying SCIP solver is configured, you may be able to efficiently use multi-threading.
To give an analogy to the CPU vs RAM issue: The CPU is like the speed or power of an engine while RAM is like the amount of stress the engine can take before it overheats. So it's generally not a good idea to max out the RAM usage 🔥

**Comment by mattmilten** [comment]
To improve the performance of the solver for a given model, You should focus on these areas in descending priority:

1. Model improvements and reformulations
2. Parameter settings of the solver
3. Hardware improvements

It's crucial to read and analyze the log file to understand and identify possible bottlenecks and areas for improvement. I can recommend [Gurobi's parameter guidelines](https://www.gurobi.com/documentation/current/refman/parameter_guidelines.html) to get started on that.

**Comment by zsasan** [comment]
> To improve the performance of the solver for a given model, You should focus on these areas in descending priority:
> 
> 1. Model improvements and reformulations
> 2. Parameter settings of the solver
> 3. Hardware improvements
> 
> It's crucial to read and analyze the log file to understand and identify possible bottlenecks and areas for improvement. I can recommend [Gurobi's parameter guidelines](https://www.gurobi.com/documentation/current/refman/parameter_guidelines.html) to get started on that.



> Hey @zsasan! Someone else should pick this up in the meantime, but I can answer some of your questions.
> 
> 2 - Yes, you can use the `solveConcurrent` method. However, for that, you need to build SCIP with the task process interface. Some information can be found [here](https://www.scipopt.org/doc/html/CONCSCIP.php), but what you need is the option `tpi=tny`, I believe.
> 
> To answer your guidance comment: From my experience, increasing the solving speed of optimization problems can be obtained by, in decreasing order of importance, better models (the existence of symmetry and of numerical instabilities has a significant impact, for example), faster algorithms, and only then better hardware. Of course, I'm not implying that the first two cases show up in your model.
> 
> Can you share the size of your problem (number and type of variables and constraints) and the time it takes to solve it?


Thank you for your responses.

Based on your insights, I've noticed that running the code on my machine doesn't fully utilize the CPU and RAM capacities. Considering this, I'm thinking that reformulating the problem and tuning the solver parameters might be beneficial in enhancing the speed and overall performance of the process. Lastly, I'm considering the option of utilizing better and faster hardware to further optimize the performance.

I'm currently tackling a mixed integer optimization problem that involves three binary and two integer decision variables. In the model, these variables are defined in a dictionary format, with keys based on the size parameters of the problem: M, U, and T. Notably, the T parameter represents a Timing Window, which is central to the scheduling aspect of my problem. Are there different methodologies or best practices in variable definition for mixed integer optimization problems, particularly when dealing with scheduling, that I might not be aware of?

Any suggestions or guidance would be greatly appreciated.
Thank you in advance for your help!

Best regards,
Sasan

**Comment by abb-omidi** [comment]
@zsasan,

Just as an attempt, is it possible to show the model notation? Or at least a mathematical definition of the decision variables?
For example, if you have $x_{c,v,t}$ which stands for assigning customer $c$ in vehicle $v$ at time $t$, you should consider this kind of formulation, namely time_indexed models, known as the difficult models in practice and you will need having special solving procedure like column generation at all. 

All the best
Abbas
