### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by marklit** [scipopt/PySCIPOpt#772]
**Describe the bug**

The gcp.py example is using an out-dated time.clock() call.

**To Reproduce**

```bash
$ python3.8 examples/finished/gcp.py
```

```
Traceback (most recent call last):
  File "gcp.py", line 149, in <module>
    tinit = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

**System**
 - OS: Ubuntu for Windows
 - Version 20 LTS
 - SCIP version v4.4.0
 - How did you install `pyscipopt`? ``pip install pyscipopt``

**Comment by Joao-Dionisio** [comment]
Thanks, @marklit!
