### ISSUE TITLE
Creating a model directly from the arrays

### ISSUE THREAD

**Issue by SanPen** [scipopt/PySCIPOpt#774]
Hi, 

Is it possible to create the model from the coefficient matrix and the other arrays like in C++?

i.e. like using `SCIPcreateConsBasicLinear` , `SCIPaddCons` , `SCIPsetObjsense`, ...

**Comment by Joao-Dionisio** [comment]
Good morning, @SanPen! 

PySCIPOpt does have the [```addConsCoeff```](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#a1daee0132c18c38417b2f884b38e046d) method, which allows you to add a variable multiplied by a coefficient to a particular constraint. It's not exactly what you asked, but it might not be too far off.

So assuming you have a coefficient matrix ```M```, you could do something like:

``` 
from pyscipopt import Model

model = Model()
y = model.addVar(lb=0,ub=0) # dummy variable to initialize constraint

x = {}
for j in range(len(M[0])):
    x[j] = model.addVar(obj=????) # the coefficient of variable x[j] in the objective function

cons = {}
for i in range(len(M)):
    model.addCons(y <= 0)

for i in range(len(M)): 
    for j in range(len(M[0])):
        model.addConsCoeff(cons[i], x[j], M[i][j]) # the coefficient of variable j in constraint i

model.setMaximize() # the objective sense is minimize by default
model.optimize()
```
I think this works, but I haven't tested it.

You have PySCIPOpt's documentation in this [link](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html). Usually the names of the methods are the same as in SCIP, without the SCIP prefix (SCIPaddCons -> addCons).

Is this what you wanted, @SanPen?

**Comment by SanPen** [comment]
Yes! I think so. I'll have to digest it, but if the C++ methods are available here as well I believe I'll manage.

thanks!

**Comment by Joao-Dionisio** [comment]
Great! :) I'll be closing the issue then, but feel free to reopen if you're still having problems!
