### ISSUE TITLE
Solve MINLP with SCIP

### ISSUE THREAD

**Issue by uvutna** [scipopt/PySCIPOpt#775]
**Describe the bug**
I'm using CVXPY with solver `SCIP` to solve mixed integer nonlinear programming problems (MINLPs). I have a problem with a constraint that contains `log` function.

My constraint is as below:

```
for k in range(A):
   temp1 = 0
   for b in range(B):
       temp2 = 0
       for i in range(C): 
           temp2 += p[i,k,b]*z[(i,k,b)]
       temp1 += W*(cp.log(1+ temp2))
   constraint.append(temp1 >= R * x)
```

**Expected behavior**
If I comment that constraint, it can compile, solve my problem and show status whether it is feasible or not
![30ed4b7a5146fa18a357](https://github.com/scipopt/PySCIPOpt/assets/14975260/2d05eca5-9fee-41b5-9f7f-1678f3db77a3)

If I keep it, CVXPY doesn't compile my problem and shows non_feasible immediately

![971e716d6e51c50f9c40](https://github.com/scipopt/PySCIPOpt/assets/14975260/61d53cbf-3a5a-4320-a90e-5a8c4cf49165)

I also test with another solver and it is feasible

**System**
 - OS: Window 10
 - SCIP version: 8.0
 - How did you install `pyscipopt`? I use `pip install PySCIPOpt`

**Comment by Joao-Dionisio** [comment]
Good morning, @uvutna!

Have you imported the log function from pyscipopt? Usually you would have something like this in your file:

```from pyscipopt import Model, log```

Just be careful that this is the natural logarithm, and you might need to do some basis change.

I've never done constraints the way you are doing (with ```constraint.append```), so I'm unsure whether that might also be a problem.

**Comment by Opt-Mucca** [comment]
I don't think this is a PySCIPopt issue. @uvutna should raise this as an issue with cvxpy.

If I've understood the output correctly, then SCIP has not even been called at at the time of failure. The failure may also be because the instance is simply infeasible.
