### ISSUE TITLE
Failed building wheel for pyscipopt

### ISSUE THREAD

**Issue by MichaelBlanchet** [scipopt/PySCIPOpt#777]
Trying to install pyscipopt on Windows 11 and it fails on the build. It appears to not have reference to the include directory. I have installed the setuptools and downloaded PySCIPOpt 6.0.2.exe, extracted and installed to C:\Program Files\SCIPOptSuite 6.0.2 

I have set the env variable SCIPOPTDIR="C:\Program Files\SCIPOptSuite 6.0.2" - and set an INCLUDE="C:\Program Files\SCIPOptSuite 6.0.2\include"

I am getting the following error on my pip install

      creating build\temp.win-amd64-cpython-312\Release\src\pyscipopt
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I. "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcsrc\pyscipopt\scip.c /Fobuild\temp.win-amd64-cpython-312\Release\src\pyscipopt\scip.obj
      scip.c
      src\pyscipopt\scip.c(772): fatal error C1083: Cannot open include file: 'scip/type_retcode.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyscipopt
Failed to build pyscipopt
ERROR: Could not build wheels for pyscipopt, which is required to install pyproject.toml-based projects

**Comment by Joao-Dionisio** [comment]
Hello, @MichaelBlanchet! It seems that you have a very quite old version of SCIP (6.0.2).

Did you install PySCIPOpt according to the instructions in [Installation from PyPI](https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md#installation-from-pypi)?

**Comment by MichaelBlanchet** [comment]
Thank you for contacting me Joao.

I have installed 8.1.0 of SCIP and removed version 6.0.2.

Btw - Microsoft identified the SCIPOptSuite exe download as suspect due to
very few downloads. You might want to contact them?

I did attempt to install PySCIPOpt according to the instructions.
Unfortunately, I get the same error.

Should I downgrade my Python to 3.11?

**Comment by Opt-Mucca** [comment]
@MichaelBlanchet Can you post the error you're getting with SCIP 8.1.0 (even if it is the same)?

My quick suggestion: Downgrade to Python 3.11. We had issues with Python 3.12 when attempting to package SCIP automatically via pip. I'm not sure yet if these issues extend to all installation possibilities yet.

**Comment by MichaelBlanchet** [comment]
Hi Mark

Thank you for getting back to me.

I had 3 versions of Python installed - I removed all of them and also
cleaned up my VS environment.

I reinstalled Python from the Microsoft App Store - updated Pip to the
latest and installed pyscipopt-4.4.0 without a problem.

Thank you
Michael Blanchet
