### ISSUE TITLE
chore: INSTALL.md link broken on https://pypi.org/project/PySCIPOpt/

### ISSUE THREAD

**Issue by dzmitry-lahoda** [scipopt/PySCIPOpt#782]
**Describe the bug**

Visit https://pypi.org/project/PySCIPOpt/ and press INSTALL.md

404

**Expected behavior**

Open link.

**Comment by Joao-Dionisio** [comment]
Hey, @dzmitry-lahoda, thanks for the issue! I think all of the links that are pointing to something in the repo are broken (CHANGELOG.md, examples, tutorials, contribution guidelines). I think fixing the links to point to the pages in the repo should be fine, but I don't know how to edit the page. I'll see if I can figure it out.
