### ISSUE TITLE
"python setup.py build" fails

### ISSUE THREAD

**Issue by bremner** [scipopt/PySCIPOpt#790]
**Describe the bug**

Build fails with the attached log.

[log.txt](https://github.com/scipopt/PySCIPOpt/files/14315766/log.txt)

**To Reproduce**

python3.12 setup.py build

**System**
 - OS: Debian
 - Version 13
 - SCIP version. 8.1.0 
 - How did you install `pyscipopt`?
  from source
**Additional context**
Cython is 3.0.8 from Debian (pip installed cython is the same)
I get the same errors with v4.4.0 or master `5e6a747e8db0`

I reported the build problem from Debian testing. I checked in Debian stable (12), and it seems to work there.
The default version of python changed to 3.12, although "python3.11 setup.py build" seems to yield similar results in Debian testing.

**Comment by Joao-Dionisio** [comment]
Hello, @bremner! I'm not too knowledgeable about this stuff, can you please share a bit more context into what you did and what you're trying to do, to see if I can help?

Sorry if this doesn't help at all, but when I build PySCIPOpt, I think I run ```pip install .```.

**Comment by bremner** [comment]
João Dionísio ***@***.***> writes:

> Hello, @bremner! I'm not too knowledgeable about this stuff, can you
> please share a bit more context into what you did and what you're
> trying to do, to see if I can help?

I am just trying to build the package (but see below).

I think it should work to run "cython3 scip.pxi"

In Debian 12 (debian stable) it works. In Debian testing (to be 13), it
generates the messages in question. Now that I look a bit closer it
looks like cython went from 0.29.32 to 3.0.8. Have you built pyscipopt
(without relying on pre-built .c files) with the latest stable release
cython?


>
> Sorry if this doesn't help at all, but when I build PySCIPOpt, I think I run ```pip install .```.
>

I am trying to build packages for Debian, so I cannot access the network
during the build. For this reason I cannot use pip or rely on a prebuilt
.c file.

**Comment by bremner** [comment]
David Bremner ***@***.***> writes:

> João Dionísio ***@***.***> writes:
>
>> Hello, @bremner! I'm not too knowledgeable about this stuff, can you
>> please share a bit more context into what you did and what you're
>> trying to do, to see if I can help?
>
> I am just trying to build the package (but see below).
>
> I think it should work to run "cython3 scip.pxi"
>
> In Debian 12 (debian stable) it works. In Debian testing (to be 13), it
> generates the messages in question. Now that I look a bit closer it
> looks like cython went from 0.29.32 to 3.0.8.

It seems I have encountered the following issue

https://cython.readthedocs.io/en/stable/src/userguide/migrating_to_cy30.html#exception-values-and-noexcept
