### ISSUE TITLE
Precision errors when converting python floats to SCIP_REALs

### ISSUE THREAD

**Issue by Joao-Dionisio** [scipopt/PySCIPOpt#794]
Conversion of Python types to C types sometimes yields precision errors. It's not clear to me when and why this happens. 

```
m = Model()
x = m.addVar()
m.setObjective(15.32*x)
m.writeProblem("model.cip")
```

![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/26415581-5c21-4a9e-9357-c73f0363170b)

The values stay correct right up the call to ```SCIPchgVarObj``` in [L1347](https://github.com/scipopt/PySCIPOpt/blob/ea15747ed0a4e087a05980dbee9b40ab6826c9b7/src/pyscipopt/scip.pxi#L1347)

Interestingly, if we set the objective at variable creation, the same doesn't happen.

```
m = Model()
x = m.addVar(obj=15.32)
m.writeProblem("model.cip")
```

![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/856a7993-7c3c-4c1b-87d7-371ea532aede)

**System**
 - OS: Ubuntu
 - Version 22.04
 - SCIP version 8.1.0
 - How did you install `pyscipopt`? Source

**Comment by leoneifler** [comment]
The number `15.32` is not exactly representable in binary floating-point format. Why this does not happen if you set it at variable creation I have no idea, but I am guessing this is the overall reason for observing this effect.

**Comment by Joao-Dionisio** [comment]
Hey @leoneifler, thanks for looking into this! That is true, but at least in Python the precision is much higher:

![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/cf83e7b7-2ee7-482b-9645-7672234b47b0)

In this [PR](https://github.com/scipopt/PySCIPOpt/pull/789) we reverted manual variable typing, which seems to be the cause for this. See here:

![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/feb596b3-c10d-4f61-8417-dd5c564424bd)
![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/8f5f424c-8e71-4063-a3f0-01ac00376aac)


Me and Mo discussed this yesterday, we have a feeling it might be due to calls to ```float``` in other files, like ```expr.pxi```. In fact, I played around with some of this (but I can't tell for sure what I did :disappointed:) and the error above no longer appears:

![image](https://github.com/scipopt/PySCIPOpt/assets/57299939/bffe283d-b0ac-4a26-9db0-c3da5cec292e)

I have encountered this behavior in other circumstances as well, that's why I haven't created a PR.

Does this all seem reasonable, Leon? What do you think?

**Comment by DominikKamp** [comment]
Just for interest, I would like to ask what the actual reason for this was. It looks like a reversion is considered as a fix. Maybe it makes sense to try `cdef double` instead of `cdef float` because the Python float rather behaves like a C double, even more consistent would be `cdef SCIP_Real` if this is somehow possible.

**Comment by Joao-Dionisio** [comment]
Oh, hey @DominikKamp! Yeah this was pretty old, and I couldn't reproduce it anymore, I think the "fix" was just what you described.

And thanks for the tip, SCIP_Real is definitely possible to use in PySCIPOpt. I'll test this out over the coming days.

**Comment by DominikKamp** [comment]
Did it work?

**Comment by Joao-Dionisio** [comment]
Okay, I managed to fail nearly 100% of the tests 😄 

![Image](https://github.com/user-attachments/assets/8572fb31-7c71-462a-8ab3-a01838aa1346)

End of this morning might have been too optimistic.

**Comment by DominikKamp** [comment]
It is not urgent, I just thought some easy performance would be nice for the next release, but maybe it is more involved.

**Comment by Joao-Dionisio** [comment]
The performance gain should be quite small, as it only affects model creation for most people (and then some stuff on the callbacks, but again somewhat minimal gain). But yeah, I think it makes sense to do this, even if just to justify my inclusion in the release report :D
