### ISSUE TITLE
WARNING: ignore partial solution (0) because unknown rate is too large (0.996856 > 0.85)

### ISSUE THREAD

**Issue by fengshaoA** [scipopt/PySCIPOpt#795]
I believe that after providing initial values to the model, the model’s solution should start calculating from the initial values I provided. Theoretically, the GAP value should start from 120% based on the initial values. However, I found that even though I provided initial values, the GAP value started from ‘inf’. After analyzing the solution log, I discovered that the initial values I provided did not take effect, and the following message was prompted:
WARNING: ignore partial solution (0) because unknown rate is too large (0.996856 > 0.85)
After the prompt for the issue, the initial values I provided did not take effect. Could you please explain what is going on here?
![image](https://github.com/scipopt/PySCIPOpt/assets/24955395/cef2496e-8220-4f2b-accd-22738e566352)
![image](https://github.com/scipopt/PySCIPOpt/assets/24955395/f28a7fb9-e21d-48cf-b0fa-8024aace14a0)

**Comment by Joao-Dionisio** [comment]
Looking at this [OR-overflow question](https://or.stackexchange.com/questions/6240/or-tools-partial-solution-ignored-due-to-unknown-rate-is-too-large), I think what happened is that your partial solution is too incomplete for the default SCIP parameters.

Maybe try calling ```model.setParam("heuristics/completesol/maxunknownrate", 1)```. That way SCIP will always accept a partial solution, no matter how incomplete it is.

**Comment by fengshaoA** [comment]
> Looking at this [OR-overflow question](https://or.stackexchange.com/questions/6240/or-tools-partial-solution-ignored-due-to-unknown-rate-is-too-large), I think what happened is that your partial solution is too incomplete for the default SCIP parameters.
> 
> Maybe try calling `model.setParam("heuristics/completesol/maxunknownrate", 1)`. That way SCIP will always accept a partial solution, no matter how incomplete it is.

Okay, thanks. I’ll give it a try.

**Comment by Joao-Dionisio** [comment]
This this end up working, @fengshaoA? Can we close the issue?

**Comment by fengshaoA** [comment]
> This this end up working, @fengshaoA? Can we close the issue?

Indeed, this method has taken effect and has been useful for my model’s solution; the reason for the excessive heuristic solutions is that I introduced many intermediate variables in the process of model solving. These intermediate variables, like the decision variables, are all boolean, leading to the decision values given by the heuristic being incorporated into the model for solving, which raises that issue.
