### ISSUE TITLE
Releasing SCIP 9 and connecting with PySCIPopt

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#797]
Dear support team,

As the SCIP team recently released its latest version, 9, would you please, how long does it take to adapt this new version with PySCIPopt?

All the best
Abbas

**Comment by Joao-Dionisio** [comment]
Hey, @abb-omidi! People are already working on it in PR #785. I can't tell you exactly how long it will take, but not too long, I'd say.

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Thank you so much and I am looking forward to hearing from you.

All the best
Abbas
