### ISSUE TITLE
@Opt-Mucca Could you please elaborate more here? so that in the future people would know what needs to be done

### ISSUE THREAD

**Issue by mmghannam** [scipopt/PySCIPOpt#799]
@Opt-Mucca Could you please elaborate more here? so that in the future people would know what needs to be done

_Originally posted by @mmghannam in https://github.com/scipopt/PySCIPOpt/pull/785#discussion_r1506049780_

**Comment by jurgen-lentz** [comment]
After merging MR #785, could you please increase the version of pyscipopt? Pyscipopt v4.4.0 is not compatible with scip 9

**Comment by Opt-Mucca** [comment]
@jurgen-lentz This problem should be fixed now

**Comment by jurgen-lentz** [comment]
> @jurgen-lentz This problem should be fixed now

Can you also create a new tag?

**Comment by Opt-Mucca** [comment]
@jurgen-lentz The tag should be created now (sorry for this taking awhile)
