### ISSUE TITLE
How to use the addConsIndicator function?

### ISSUE THREAD

**Issue by fengshaoA** [scipopt/PySCIPOpt#810]
I want to implement the following constraint: 

```
if bus_first_task_start[v2,j] - bus_first_task_start[v1,i] >= 0 then
    bus_end_task_start[v2,j] - bus_end_task_start[v1,i] >= 0
```

When I write it in this format:

```
y1 =md.addVar(vtype="B")
y2 = md.addVar(vtype="B")
md.addCons(y2>=y1)
md.addCons(bus_first_task_start[v2,j]-bus_first_task_start[v1,i]>=(1-y1)*1000000)
md.addCons(bus_end_task_start[v2,j]-bus_end_task_start[v1,i] >=(1-y2)*1000000)
```

there is no problem,
 but when I write it like this:

```
md.addConsIndicator(bus_first_task_start[v2,j]-bus_first_task_start[v1,i]>=0,bus_end_task_start[v2,j]-bus_end_task_start[v1,i] >=0)
```

An error occurs: ```Process finished with exit code -1073741819 (0xC0000005)```

Can you tell me the correct usage of this function?
Thanks

**Comment by Joao-Dionisio** [comment]
Hey @fengshaoA! I updated your comment for readability, but feel free to revert the changes if you don't like them :)

I can't give you a proper answer right now, but did you look at the documentation of the function? [Link](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#a0d216d1bf2fc744be35c3dae3c3f1734)

**Comment by Joao-Dionisio** [comment]
As it says in the documentation, the first argument should be the conditional constraint, as you have it, and the second argument should be a binary variable (let's call it ```x```). Any solution where ```x == 1``` must satisfy this conditional constraint. So you need something like

```
x = md.addVar(vtype="B")

md.addCons(x >= bus_first_task_start[v2,j] - bus_first_task_start[v1,i])

md.addConsIndicator(bus_first_task_start[v2,j]-bus_first_task_start[v1,i]>=0, x)

```

I think the logic is right, but please verify it yourself.

**Comment by fengshaoA** [comment]
> As it says in the documentation, the first argument should be the conditional constraint, as you have it, and the second argument should be a binary variable (let's call it `x`). The indicator constraint will ensure that any solution where `x == 1` will satisfy the conditional constraint. So you need something like
> 
> ```
> x = md.addVar(vtype="B")
> 
> md.addCons(x >= bus_first_task_start[v2,j] - bus_first_task_start[v1,i])
> 
> md.addConsIndicator(bus_first_task_start[v2,j]-bus_first_task_start[v1,i]>=0, x)
> ```
> 
> I think the logic is right, but please verify it yourself.

Okay, thank you for your reply, I’ll give it a try.

**Comment by fengshaoA** [comment]
> > As it says in the documentation, the first argument should be the conditional constraint, as you have it, and the second argument should be a binary variable (let's call it `x`). The indicator constraint will ensure that any solution where `x == 1` will satisfy the conditional constraint. So you need something like
> > ```
> > x = md.addVar(vtype="B")
> > 
> > md.addCons(x >= bus_first_task_start[v2,j] - bus_first_task_start[v1,i])
> > 
> > md.addConsIndicator(bus_first_task_start[v2,j]-bus_first_task_start[v1,i]>=0, x)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think the logic is right, but please verify it yourself.
> 
> Okay, thank you for your reply, I’ll give it a try.

my qustion is :
```
if bus_first_task_start[v2,j] - bus_first_task_start[v1,i] >= 0 then
    bus_end_task_start[v2,j] - bus_end_task_start[v1,i] >= 0
```
I followed your advice, but I still get an error when running the code, and it prompts: Process finished with exit code -1073741819 (0xC0000005).

**Comment by fengshaoA** [comment]
> Can you please provide a minimal reproducible example? A small-ish snippet of code that contains your error that I can look at.

`from pyscipopt import Model, quicksum, multidict
m = Model()
is_meal = m.addVar(vtype='B')
meal_time = m.addVar(vtype='I',lb=5,ub=30)
m.addConsIndicator(meal_time<=20,is_meal)
m.setObjective(meal_time,'maximize')
m.optimize()
sol = m.getBestSol()
print(sol[is_meal])
print(sol[meal_time])`

`SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 0.00
Solving Nodes      : 0
Primal Bound       : +3.00000000000000e+01 (3 solutions)
Dual Bound         : +3.00000000000000e+01
Gap                : 0.00 %
-0.0
30.0`
It works fine in simple cases; I think it must be my own issue. I’ll study it more carefully.

**Comment by Joao-Dionisio** [comment]
Any updates @fengshaoA?

**Comment by fengshaoA** [comment]
> Any updates @fengshaoA?

I apologize for the late reply. I have already understood how to use this function, thank you!
