### ISSUE TITLE
When does SCIP call the cut plane selector?

### ISSUE THREAD

**Issue by zslztms** [scipopt/PySCIPOpt#812]
From the previous [issue](https://github.com/scipopt/PySCIPOpt/issues/763), I understood when the cut plane selector was called at the root node, but did not know when the cut plane selector was called at other nodes. 

> 1.SCIP can call separators multiple times in the root node itself. If significant changes happen (due to various components of SCIP) in the root node relaxation after a round of separation call, then the separators may be called again in the root node. This can result in follow up calls to the cutting plane selector.
2.SCIP has the ability to restart the instance solving for various reasons (as mentioned above by @Joao-Dionisio), such as, the estimated remaining tree size is too large or good number of global fixings have happened recently, among other reasons. Whenever a restart occurs, a new tree is constructed on the reduced instance resulting in a new root node. So, the separators may be called again in this root node along with a follow up call to the cutting plane selector.

I want to know how the cut plane selector is called on the other nodes.I have a few questions

1. Does each node generate many cut planes through the separator？
2. Does each node call the cut plane selector?

From my observation, the separator and selector calls do not go together, and both seem to be influenced by random numbers based on probability.

**Comment by zslztms** [comment]
Thank you for your answer, I also want to know if there are any parameters so that all nodes will call the separator and selector?

**Comment by Opt-Mucca** [comment]
Set all the frequency parameters for each separator to 1

**Comment by Joao-Dionisio** [comment]
Hey @zslztms! Can this issue be closed?

**Comment by zslztms** [comment]
Yes
