### ISSUE TITLE
getStatus() does not return SCIP_STATUS

### ISSUE THREAD

**Issue by elkrari** [scipopt/PySCIPOpt#816]
Hi everyone,

`getStatus()` of `Model` returns string values, which are different from `SCIP_STATUS` values (integers).

For example, after solving (to optimality) a model, `getStatus()   == SCIP_STATUS.OPTIMAL` will be `False`.

I have to compare it with "optimal" to find out if the model is solved, which is not the best way to make it.
My code includes testing other statuses for which I don't know their string values.

Is there any alternative to either `getStatus()` or `SCIP_STATUS`? 

Cheers

**Comment by Joao-Dionisio** [comment]
Hey @elkrari! There is the [getStage()](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#a89c5f78430ffa12848455fb7eaa1094c) method, which returns an integer. But I agree that the nomenclature should be more intuitive.
