### ISSUE TITLE
The issue to use Eventhdlr

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#820]
Dear support team,

I hope you are doing well. I am working on the problem and am implementing an `Eventhdlr` to capture some behavior of the solver. 
The template I am using is as follows:

```
class MyEvent(Eventhdlr):

  def __init__(self):
    pass 

  def eventinit(self):
    ...

  def eventexit(self):
    ...

  def eventexec(self, event):
    ...

def model_opt():
  # create solver instance
  s = Model()
  eventhdlr = MyEvent()
  s.includeEventhdlr(eventhdlr, "...", "...")

  return s

def run_event():
  # create solver instance
  s = model_opt()
  # optimization model and solve that
```
When the code is run, I have gotten the following errors that I really do not recall I have seen in the previous version of SCIP. 

```
---------------------------------------------------------------------------
ReferenceError                            Traceback (most recent call last)
[<ipython-input-51-d32610f29da5>](https://localhost:8080/#) in eventexit(self)
     14   def eventexit(self):
     15     calls.append('eventexit')
---> 16     self.model.dropEvent(SCIP_EVENTTYPE.BESTSOLFOUND, self)
     17 
     18   def eventexec(self, event):

ReferenceError: weakly-referenced object no longer exists
Exception ignored in: 'pyscipopt.scip.PyEventExit'
Traceback (most recent call last):
  File "<ipython-input-51-d32610f29da5>", line 16, in eventexit
ReferenceError: weakly-referenced object no longer exists
[event.c:235] ERROR: Error <0> in function call
[set.c:5438] ERROR: Error <0> in function call
[scip_solve.c:1841] ERROR: Error <0> in function call
[scip_solve.c:3380] ERROR: Error <0> in function call
[scip_prob.c:706] ERROR: Error <0> in function call
[scip_general.c:349] ERROR: Error <0> in function call
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
src/pyscipopt/scip.pxi in pyscipopt.scip.PY_SCIP_CALL()

Exception: SCIP: unspecified error!
Exception ignored in: 'pyscipopt.scip.Model.__dealloc__'
Traceback (most recent call last):
  File "src/pyscipopt/scip.pxi", line 261, in pyscipopt.scip.PY_SCIP_CALL
Exception: SCIP: unspecified error!
```

I should say the callback seems to work well and shows the desired results:

`['eventinit', 'eventexec', 'eventexec']`

I am wondering if, how to fix the complaint.

> Successfully installed pyscipopt-5.0.0
> SCIP 9

All the best

**Comment by Joao-Dionisio** [comment]
Hey @abb-omidi! Can you please provide the code so we can play around with it a little bit?

You are saying that you think it was the SCIP upgrade that created this problem, right? Does your code still run if you downgrade your SCIP/PySCIPOpt?

**Comment by Joao-Dionisio** [comment]
Thanks @abb-omidi! This is quite strange because it seems the code runs to the end, the error doesn't alter things. I'll look into it more later.

With the provided link, I just wanted to say that we changed some things related to events that might have been causing an issue.

**Comment by Joao-Dionisio** [comment]
Hey @abb-omidi, can you take a look at this? [How to add event handlers](https://github.com/ds4dm/ecole/discussions/193)

I think it might solve your problems, and it's also very interesting for my own work :)

**Comment by Joao-Dionisio** [comment]
I'd probably wait for someone more knowledgeable to answer, @abb-omidi, but my guess is that for some reason the PySCIPOpt model is already deleted by the time it should be calling ```eventexit```. I don't know what the consequences of not calling ```eventexit``` are, but maybe try out your code that way, and see if you get other problems, or if it's okay. 

Sorry for not being to help out more at the moment. If you haven't seen it, there's also SCIP's [How to add event handler page](https://www.scipopt.org/doc/html/EVENT.php).

**Comment by abb-omidi** [comment]
@Joao-Dionisio,

Thanks for your attention, and do not worry. It will eventually be solved. 😊

Best regards
