### ISSUE TITLE
Are there any APIs to sort the constraints and variables according to their names?

### ISSUE THREAD

**Issue by haoyangliu123** [scipopt/PySCIPOpt#831]
Dear support team,
       The variables and constraints in the scip.Model() are stored in the default order. I want to sort the constraints and variables according to some predefined rules, such as their names. Could you please provide some advice? I would appreciate your help!

Best wishes

**Comment by Opt-Mucca** [comment]
As in you want SCIP internally to store them in some order? If so then I would suggest simply adding the variables and then constraints in the order that you want.

If you just want to access the PySCIPOpt objects in some order, then you should use something like lambda expressions:
```
scip = Model()
...
scip_vars = scip.getVars()
scip_vars.sort(key=lambda a: a.name)
```

**Comment by haoyangliu123** [comment]
Thanks for your reply! The problem has been solved.
