### ISSUE TITLE
How to speed up the solution process.

### ISSUE THREAD

**Issue by fengshaoA** [scipopt/PySCIPOpt#850]
Recently, when using SCIP to solve optimization problems of slightly larger scale, the solving speed is relatively slow. I am unsure if this is due to my lack of mastery of a parameter design technique in SCIP’s solving process. Therefore, I would like to ask if there are any effective parameter settings that can accelerate the solving speed during SCIP’s solution process.

**Comment by leoneifler** [comment]
Of course it is possible to tune the parameters for better performance for your specific application. But giving any advice here without more information is impossible. Could you elaborate on what types of problem you are trying to solve?

**Comment by fengshaoA** [comment]
> Of course it is possible to tune the parameters for better performance for your specific application. But giving any advice here without more information is impossible. Could you elaborate on what types of problem you are trying to solve?

Alright, I am currently working on a public transit vehicle scheduling problem, which is a mixed-integer programming model. I am hoping to find a feasible solution rather than the global optimal solution.

**Comment by fengshaoA** [comment]
> > Of course it is possible to tune the parameters for better performance for your specific application. But giving any advice here without more information is impossible. Could you elaborate on what types of problem you are trying to solve?
> 
> Alright, I am currently working on a public transit vehicle scheduling problem, which is a mixed-integer programming model. I am hoping to find a feasible solution rather than the global optimal solution.

Or rather, for general mixed-integer programming problems, are there several key parameters that, by adjusting them, can speed up the problem-solving process?

**Comment by leoneifler** [comment]
If you are mostly interested in finding feasible solutions, then I would suggest  setting the heuristics to aggressive using `setHeuristics(AGGRESSIVE)` (I think that is the correct syntax but please double check). If you don't care about optimality at all, then you might also experiment with disabling cutting planes, for example. In general, there is no one-fits-all solution for parameter tuning. It all depends on the type of problem and specific problem structure that you have.

**Comment by Joao-Dionisio** [comment]
Hey @fengshaoA! You can also try looking at [setEmphasis](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#ae20e15972fd7cbf119372f340539dfed) (the corresponding SCIP [documentation](https://www.scipopt.org/doc/html/group__ParameterMethods.php#gab2bc4ccd8d9797f1e1b2d7aaefa6500e)). 

You can try doing 

```
from pyscipopt import Model, SCIP_PARAMEMPHASIS

model = Model()
model.setEmphasis(SCIP_PARAMEMPHASIS.PHASEFEAS)
``` 

I believe this tells SCIP to focus on finding feasible solutions rather than proving optimality.

**Comment by fengshaoA** [comment]
I tried the two methods mentioned above, and setEmphasis() worked best. Without adding this parameter, the time taken was over 3000 seconds. After adding it, the time spent ranged from 575 to 870 seconds. Using SCIP_PARAMEMPHASIS.PHASEFEAS took approximately 870 seconds, and SCIP_PARAMEMPHASIS.FEASIBILITY took about 570 seconds. 
Thank you!

**Comment by leoneifler** [comment]
Another, slightly more involved thing you can try is to look at the SCIP logfiles. If you repeatedly solve similar problems and you see that some SCIP components take a long time (such as specific heuristics or cutting planes) but never find anything, then disabling those can save a lot of effort in future solves.

**Comment by fengshaoA** [comment]
> Another, slightly more involved thing you can try is to look at the SCIP logfiles. If you repeatedly solve similar problems and you see that some SCIP components take a long time (such as specific heuristics or cutting planes) but never find anything, then disabling those can save a lot of effort in future solves.

Thank you! In fact, I often encounter this during the solving process, but I’m not sure what causes it. Following your advice, I should focus on analyzing the log files to determine the slowest parts and then optimize them.
