### ISSUE TITLE
pypi does not have the lastest version

### ISSUE THREAD

**Issue by bmw2142** [scipopt/PySCIPOpt#853]
Pypi does not have the lastest version.
The lastest version is 5.0.1, but pypi still 5.0.0.
Please update, thank you.

https://pypi.org/project/PySCIPOpt/

**Comment by Opt-Mucca** [comment]
We're working on this. Currently having pipelines issues and are trying to incorporate new plugins.

**Comment by Opt-Mucca** [comment]
@bmw2142 This should hopefully be fixed now. We've uploaded a new version to PyPI
