### ISSUE TITLE
Example - SDP relaxation - https://arxiv.org/pdf/2305.00203

### ISSUE THREAD

**Issue by andrewcz** [scipopt/PySCIPOpt#856]
Hi Team,

Would you be able to create or point me in the direction of an example that uses an SDP relaxation.

I am trying to re-create the below paper.

https://arxiv.org/pdf/2305.00203

Any help would be greatly appreciated. 

Best,
Andrew

**Comment by Joao-Dionisio** [comment]
Hello @andrewcz! I had no clue this existed, but apparently, there is [SCIP-SDP](https://github.com/scipopt/SCIP-SDP). In the README you have a bunch of documentation, which can help you start out. 

I believe Marc Pfetsch is behind the project, so perhaps he can be helpful as well.

**Comment by Joao-Dionisio** [comment]
I'm closing the issue to clear the issues page, but feel free to reopen if you're still having problems!
