### ISSUE TITLE
Version 4.4.0 is not available through pypi.org

### ISSUE THREAD

**Issue by BionicoWB** [scipopt/PySCIPOpt#875]
In the releases page related to the project the version 4.4.0 is absent and I am not be able to import the dependency using pip.

https://pypi.org/project/PySCIPOpt/1.1.2/#history

**Comment by Joao-Dionisio** [comment]
Hello, @BionicoWB. Sorry for this, but we removed both 4.4.0 and 5.0.0 because of licensing issues. You can read a bit more about it in issue #863.

**Comment by BionicoWB** [comment]
Isn't there a 4.x version that overcomes the licensing problem and avoids backward compatibility problems?

**Comment by Opt-Mucca** [comment]
@BionicoWB There's sadly no 4.x version that comes with the automatic SCIP installation and overcomes the licensing problems. 4.4.0 was the final release before 5.0.0.
