### ISSUE TITLE
Can we check and change the number of cores that solver is using?

### ISSUE THREAD

**Issue by adover134** [scipopt/PySCIPOpt#882]
I am using a computer with CPU which has enough cores to use solveConcurrent(). So, I was expecting that solving should be much faster, but seems SCIP is using only few cores. Can I change or check the number of cores?

OS version : Windows Server 2012 R2 Standard

**Comment by adover134** [comment]
https://scipopt.org/doc/html/PARAMETERS.php

In this page, I found 'parallel/minthreads' and 'parallel/maxthreads'. Basic value of the max threads was too small. I think changing this will be work.

**Comment by Joao-Dionisio** [comment]
These are my favourite issues :D
