### ISSUE TITLE
Describe setting emphasis settings in docs

### ISSUE THREAD

**Issue by mmghannam** [scipopt/PySCIPOpt#908]

**Comment by Joao-Dionisio** [comment]
Gregor's slides on it: [Working with SCIP parameters
SCIP Workshop 2014](https://www.scipopt.org/workshop2014/parametertuning.pdf)

**Comment by mmghannam** [comment]
yeah I meant the use of `SCIP_PARAMSETTING` but add the emphasis modes would be good too :)
