### ISSUE TITLE
Set the limits of a variable from a set of intervals

### ISSUE THREAD

**Issue by Grenby** [scipopt/PySCIPOpt#919]
Dear support team,

I want to know how to set the limits of a variable from a set of intervals.

For my task, I want to set the working hours of the stores during the week (for example, from 9 to 18) and I want the car to arrive in the intervals (9 + 24*k, 18 + 24*k), where k is some number of days.

Can you tell me how to do this using  pyscipopt without additional variable like days?

**Comment by Grenby** [comment]
I will describe the problem in more detail:
I have set points where it is necessary to distribute cargo, sometimes the distance between the points is more than one day, and car should arrive during working hours (from 9 to 18 on any day). I think that for this purpose it is possible to limit the permissible values ​​of the arrival time to intervals (9,18), (9+24, 18+24)...
I described a special case of introducing intervals for permissible values ​​of a variable. In my opinion, such a problem can be solved by introducing a new variable "day", but is it possible to set interval values ​​using the scipopt?

**Comment by Joao-Dionisio** [comment]
If you were to do that directly, the problem would be disjoint no? Meaning that you would need to solve an optimization problem for each day and then compare the optimal solutions. I'm almost sure there is no solver that supports modeling these things directly.

I think the other approach I suggested should work. Just ignore the non-working hours, and start thinking of days as only having 9 hours. So if the solution you get is 5, you know that it's actually 13h00 of the 1st day. If it is 21, you know it's 12h00 of the 3rd day. Here is a picture to help illustrate what I mean

![image](https://github.com/user-attachments/assets/13db1595-939c-4b8c-8973-0f015e63308d)
