### ISSUE TITLE
How to add a new column in the column generation procedure 

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PySCIPOpt#922]
Dear support team,

I am having some difficulties understanding and investigating how the Farkas certificate can work on the problem and how a new column may be added to the master problem. Let me explain a bit more:

I am working on the problem in which the master problem contains two constraints. When the algorithm works in an iteration I got the farks error and the procedure is stoped. Now, my questions are: 

1) How the Farkas method works and when should we expect to get `return price(farkas=False))` (price is a method to call farkas)?

2) I want to add a new column in the master problem. Can the following method update the new columns in both constraints (the subproblem contains only one structural constraint that reproduces the shifts)?
```
            new_var = self.model.addVar(vtype="B", name=f"{shifts}", obj=1, pricedVar=True)
            for item in shifts:
                item_constraint = self.constraints[item]
                item_constraint = self.model.getTransformedCons(item_constraint)
                self.model.addConsCoeff(item_constraint, new_var, 1)

            for item_ in shifts:
                item_constraint_ = self.constr1[item_]
                item_constraint_ = self.model.getTransformedCons(item_constraint_)
                self.model.addConsCoeff(item_constraint_, new_var, 1)
                
    where, constraints and constr1 are the matsre problem constraints.
```   
3) If there is a constraint in the master with the dual array of zero in the current optimal solution of the master problem, is it caused the infeasibility and returns `Farkas = False` I asked in my first question? (It is a bit strange!)

All the best

**Comment by Joao-Dionisio** [comment]
Hey @abb-omidi. 

1. Farkas Pricing solves the pricing problem with a zero objective cost, in order to generate feasible columns to fix the current RMP's infeasibility. SCIP handles the communication itself, but one should use `pricerfarkas` when this is needed. When the RMP is feasible but not optimal, then `pricerredcost` should be called (which I assume should happen when calling `price(farkas=False)`).
2. Yes, that should work. 
3. When you are doing farkas pricing and you solve the pricing problem, if the optimal solution is non-negative (assuming minimization), then the master problem is infeasible. If you are certain that your problem is feasible, then you might have a problem in your code. You should make sure that when doing Farkas' pricing, then the duals are given by `getDualfarkaslinear`, and when not doing it, using `getDualSolVal`.

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Thanks for your prompt response as well as your answers. 
Please, let me check something based on your hints, and I will get back to you.

Best regards

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

When I debugged the model, I found that the pricing objective function has a special structure. The main variable in the model is ($x_{j,s,p}$) where $j$ is referred to the tasks, $s$ indicates the stations, and $p$ counts the columns that came from the pricing. The problem is being decomposed based on $s$ and the objective function of the pricing problem has the following form:

$$ z_{sp}  = \quad 1 - (\sum_{j} \pi_{j} * x_{j}) - (\sum_{j,k \in Arc_{j,k}} s * (x_{j} - x_{k}) * \sigma_{j,k})$$

Now, by defining the variable $x$ as:
```
    x = {}
    for i in range(len(sizes)):
        x[i] = m.addVar(vtype="B", name=f"x{i}")
```
and its `obj` attribute as:
```
obj=(values[i] + sum(s * values_[(j,k)] for s in range(m) for (j,k) in precedence)))
```
where `values` and `values_` are duals of the first and the second constraints in the master problem respectively, and `m` is the number of stations, I am pretty sure, it cannot produce the correct reduced cost. 

Would you tell me please, how can we define the variable $x$ and its `obj` attribute based on my mentioned objective function?

Regards

**Comment by Joao-Dionisio** [comment]
Your pricing objective can be formulated as

$$
m.setObjective(1 - sum(pi[i] * x[i] for i in whatever_your_first_iterator_is) - sum(s*(x[i] - x[j]) * sigma[i,j] for (i,j) in whatever_your_second_iterator_is)
$$

It seems like you are adding your pricing variables correctly.

If you think the reduced cost is not being computed correctly, start with a toy instance and compare the results when you do it by hand, or with another solver. You might have forgotten to say that the master constraints are modifiable with `modifiable=True`.

I'm closing the issue, as the original question was answered.

**Comment by abb-omidi** [comment]
Dear @Joao-Dionisio,

Can I write the objective function of the pricing problem as a separated expression like you wrote?
Is it possible to update the coefficient of variable $x$ in the separated form? (In the original coding, it is written in a column-wise form and I thought the only way to update the coefficient would be based on!).

Thanks

**Comment by Joao-Dionisio** [comment]
The pricing problem is just a SCIP model. You can add objectives to SCIP model in a separate expression. You don't need to do it column-wise. If you want to update the coefficients from one iteration to the next, you can just set a new objective.

**Comment by abb-omidi** [comment]
Ah, that's right. If I understand correctly, what I need is to write my specific objective function in the pricing model, like what I wrote in GAMS, then SCIP can automatically update what the model needs in each iteration in a way like a column-wise definition.
Am I standing in the right way? If so, it would be so straightforward way!

Best

**Comment by Joao-Dionisio** [comment]
Yes, that's right Abbas.

**Comment by abb-omidi** [comment]
Thank you so much for your help.
All the best
